### ISSUE TITLE
Block reach, Simple Rpg

### ISSUE THREAD

**Issue by Qefixe** [Lothrazar/Cyclic#1006]
Minecraft version & Mod Version: 1.12.2 1.17.10
---------------------------------
Single player or Served:Single
---------------------------------
Describe problem (what you were doing / what happened):
1)Enchant block reach, i cant break blocks.*
2)Conflict with SimpleRPG (HP only 20, but before the upgrade everything worked* and it was 45 HP)
* worked up to version 15, have to play at 14 :(
* this bug is in version 14 and 17
----------------------
Crash log (if any):No

**Comment by Qefixe** [comment]
I can't find out which mod is conflicting because I have 143 mods at the moment

**Comment by Qefixe** [comment]
And sorry for my broken english :)+

**Comment by Qefixe** [comment]
Ok. i fixed block reach (delete potioncore) but simplerpg conflict is still conflict :(

**Comment by Lothrazar** [comment]
Needs investigation

also reference  https://minecraft.curseforge.com/projects/simple-rpg/issues/1

**Comment by Lothrazar** [comment]
Sadly i dont think this will get fixed 

1. the Simple RPG mod appears to have been abandoned in December 2017

2. no responses to issues created on simple rpg tracker

3. Their mod is closed source 
 
if any of those three things ever changes we can revisit this
