### ISSUE TITLE
If you have Climbing Gloves in your inventory and in your bauble slots, the ones in your inventory take damage too

### ISSUE THREAD

**Issue by aaronhowser1** [Lothrazar/Cyclic#1007]
Minecraft version & Mod Version:
1.12.2, 1.17.10

Single player or Server:
Server

Describe problem (what you were doing / what happened):
![image](https://user-images.githubusercontent.com/15698722/49281271-c639b880-f451-11e8-945f-de75c9e1ce3f.png)
The Climbing Gloves in my inventory take damage when I use the one in my bauble slot.

**Comment by Lothrazar** [comment]
after looking into this. i think its working as intended.  the gloves cant look for other gluves, but each one knows it has been turned on and the player is climbing. can turn them off with right click then they wont be damaged
