### ISSUE TITLE
Responsive Scaffolding does not drop itself when destroying itself.

### ISSUE THREAD

**Issue by KalaMiDeviL** [Lothrazar/Cyclic#1009]
Minecraft version & Mod Version:
MC     1.12.2
Forge 14.23.4.2749
Cyclic 1.17.0

Single player or Server:
Single

Describe problem (what you were doing / what happened):
When I break a responsive scaffolding block, the adjacent ones do get destroyed, but not dropped.
EDIT: The one destroyed by me gets dropped.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312
