### ISSUE TITLE
Antidote charm not clearing poison particle effects on cure

### ISSUE THREAD

**Issue by xenoflot** [Lothrazar/Cyclic#1010]
Minecraft version & Mod Version:
1.12.2
1.17.7
14.23.5.2768

Single player or Server:
SSP

Describe problem (what you were doing / what happened):
When the Antidote Charm cures cave spider poison, the poison particle effects remain active until the player dies (or relogs). /effects @p clear has no effect on the particles "no effect to clear".

To reproduce:
Have an active Antidote Charm in your inventory
Get bitten by a cave spider
Slay cave spider without mercy
Get rejected by your puppy because you still smell bad :(

**Comment by Lothrazar** [comment]
Works as intended in current version, i must have fixed it in the past since then  
![safe poison](https://user-images.githubusercontent.com/621529/54094493-86427580-435e-11e9-9fc5-165f18751ebe.gif)
