### ISSUE TITLE
Scythe Compatibility w/ Extra Utilities' Red Orchid

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1011]
Minecraft version & Mod Version:
Forge v14.23.4.2772-1.12.2
Cyclic v1.17.10
[Extra Utils](https://minecraft.curseforge.com/projects/extra-utilities) v1.9.8

Describe the problem (what you were doing / what happened):
The sycthe can't harvest the red orchid from ExtraUtils.
![2018-11-29_23 01 48](https://user-images.githubusercontent.com/12000593/49560500-4b045680-f8d8-11e8-99ec-6b81d2e0f549.png)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312

**Comment by WenXin20** [comment]
I just wanted to let you know that the scythe will harvest the Red Orchid now, but it won't replant it. Maybe because it has to be planted on redstone ore?
