### ISSUE TITLE
Dice Texture

### ISSUE THREAD

**Issue by AVileIdiot** [Lothrazar/Cyclic#1012]
The dice block has a lighter outline for the 1 than for any of the other 5 sides
![2018-12-09_18 09 25](https://user-images.githubusercontent.com/38671980/49704193-e8fc6780-fbdd-11e8-9b65-4d50b6f291c0.png)

**Comment by Lothrazar** [comment]
oh yeah it is noticeably a different shade

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312
