### ISSUE TITLE
Give an explanation of what the "Extended Inventory Tool Belt" is/does

### ISSUE THREAD

**Issue by mahilo3550** [Lothrazar/Cyclic#1013]
Minecraft version & Mod Version:
1.12.2 & Since 1.17.1

Single player or Server:
Either

Describe problem (what you were doing / what happened)
People easily see: "Extended Inventory Tool Belt" under Controls Menu between Extended Inventory and Inventory Crafting Table, but the only explanation I know of is the Changelog saying: "New keyboard wheel shortcut that re-uses your extended inventory to hot-swap your items toolbelt style."

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
hopefully, once the two key bindings are unlocked and are both tried out it is self evident,  default R is tool belt mode. updated JEI text and added a tooltip in a certains pot

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312
