### ISSUE TITLE
Spawner Seeker not working - eye stands still and doesn't vanish on server start

### ISSUE THREAD

**Issue by gabeux** [Lothrazar/Cyclic#1015]
Minecraft version & Mod Version: 1.12.2 & 1.17.10
Single player or Server: Server
Describe problem (what you were doing / what happened): When using the Spawner Seeker, the purple 'projectile' stays in place, and doesn't move. The projectile stays at the same location for a long time, and restarting the server doesn't clean up all the purple eyes.
Crash log (if any): No crashes.

I'm running a further modded All The Mods 3 modpack on Forge 2768. 
Let me know if there's any tips for cleaning up the purple eyes that are hovering on my base! :T

Love the mod - thanks!

**Comment by josephcsible** [comment]
As a workaround, you can use `/kill @e[type=cyclicmagic:dungeonbolt]` to get rid of them.

**Comment by Lothrazar** [comment]
They have an internal clock where they die off eventually.  also they die when hit the goal, but the /kill works too.

Sounds like youre having some sort of error when they vanish and something isnt cleaned up, maybe an error in the logs when that happens would help


Or maybe a recording of how it looks?
https://screentogif.com

I went on a low resource server and it works like this for me. when spawners are in range. when not in range i get the message.

https://i.imgur.com/0zX17Ps.gifv

**Comment by Lothrazar** [comment]
Closed due to no response and working fine in latest versions. Come back any time with new issues/info
