### ISSUE TITLE
Xp Pylon server->client desync display (?)

### ISSUE THREAD

**Issue by yuri0r** [Lothrazar/Cyclic#1018]
Minecraft version & Mod Version:

minecraft 1.12.2
cyclic 1.17.10

Single player or Server:
server only

Describe problem (what you were doing / what happened):
as in #894 the problem occurs when filling the xp pylon on a Server.
fastest way to replicate: join a server place a xp pylon give your self 2000xp and and fill the pylon with those. result as in the picture

the picture was taken on a local server with only cyclic and forge installed. pylon ist filled with 2000 XP.
![2018-12-22_02 53 40](https://user-images.githubusercontent.com/9966894/50369384-13163800-0595-11e9-8d3e-f38a024e0043.png)

**Comment by Old-Man-D** [comment]
I noticed the same thing yesterday, running Enigmatica 2 Expert on a personal server.  What I observed was that Waila showed a positive number when looking at the pylon, but the UI showed a negative number.  If I dumped all my current experience into it, it would correct itself and gauge would show the green bar.

**Comment by Lothrazar** [comment]
closing for being stale, can reopen or new issue if anything breaks

**Comment by embeddedt** [comment]
Just ran into this issue on a dedicated server with 1.20.11, however, it seems to only be a visual glitch. If you change to "Spray Orbs" within the GUI the right value shows up again. I presume therefore that the XP is still being stored properly in the block itself, which is good enough for me.

**Comment by Lothrazar** [comment]
ah yeah sounds like a desync from server-> client so yeah only the gui widget is wrong sometimes or doesnt get updated

**Comment by Lothrazar** [comment]
on the way is v1.20.12 found a fix
