### ISSUE TITLE
Server Crash in version 1.17.11

### ISSUE THREAD

**Issue by CritFlaw** [Lothrazar/Cyclic#1022]
Minecraft version & Mod Version:
Minecraft - 1.12.2
Cyclic - 1.17.11

Single player or Server:
Server

Describe problem (what you were doing / what happened):
The server crashes on startup.

Crash log (if any):
https://hastebin.com/opevobegec.rb

**Comment by Lothrazar** [comment]
Thanks for the report.   When i click that link its just a blank blue screen with no text. maybe ill try again later  .

It might be the same as this one https://github.com/Lothrazar/Cyclic/issues/1019

**Comment by CritFlaw** [comment]
It works for me, maybe try on a different browser?

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2652098
