### ISSUE TITLE
Whitelist to Brush Scythe

### ISSUE THREAD

**Issue by CritFlaw** [Lothrazar/Cyclic#1026]
Brush Scythe should have a whitelist where you can add additional things it can harvest. Currently Pam's Wee Flowers, and Natura to name a few, are not scyth-able.

**Comment by Lothrazar** [comment]
report back if it or something else bugs out https://minecraft.curseforge.com/projects/cyclic/files/2657989

**Comment by katubug** [comment]
Hey, I'm not sure if you've fixed this already, but NetherEx recently changed the mod name from `nex` to `netherex`, in case you wanted to change the default config value. :)
