### ISSUE TITLE
BUG - Water Candle Spawn Rules - Light Level

### ISSUE THREAD

**Issue by G3R0N1M079** [Lothrazar/Cyclic#1027]
Minecraft version & Mod Version:
MC 1.12.2
Cyclic 1.17.12

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Hi,
Sorry for bother you but in my opinion the water candle doesn't function yet.
First of all it breaks again the LIGHT RULES.
In a complete flat platform and during the day with all the blocks at light of 15, hostyle mobs can spawn.
Second sometimes  hostyle mobs could spanw inside the platform floor (inside a block) and can't move or jump.

I think i understood that breaking light rule is not intended.
i May be wrong.

Could you look into it, please?
Thank You very much for this mod and you effort.
Enrico

Crash log (if any):
Not present

**Comment by Lothrazar** [comment]
I found one bug, which is that sometimes when its checking spawn rules it was using the location of the candle, instead of the target location it randomly picked to place the monster. also explains why they spawn in walls

**Comment by G3R0N1M079** [comment]
Hi Lothrazar.
AHHAHAHAHa Nice check.
I hope you can find a solution.
I love your semi random stuff and the way they are crafted with unusual material.
Very good mod.

Enrico

**Comment by Lothrazar** [comment]
thanks i just make whatever and try to make it unique. 

report back if anything bugs out https://minecraft.curseforge.com/projects/cyclic/files/2657989

**Comment by isavegas** [comment]
Having this issue in 1.17.16 in the Stoneblock 2 modpack. I have a big spawn room with the adjacent room well lit. Mobs are routinely spawning inside walls and in the lit room. I took a look at the code in your commit squashing the bug, but can't see where it's going wrong. I did notice that you put your debug messages (which aren't showing up in my console) in the wrong conditions, though. :)

**Comment by pikero24** [comment]
I have a water candle and mobs are spawning in my walls around me! Does anyone know if there's a fix?
