### ISSUE TITLE
Laser Cell - Laser graphic is hidden when block out of view

### ISSUE THREAD

**Issue by TinkererKhane** [Lothrazar/Cyclic#1030]
Minecraft version & Mod Version:
Stoneblock 1.0.31
Minecraft 1.12.2
Cyclic 17.9

Single player or Server:
Server

Describe problem (what you were doing / what happened):
The graphic the Laser Cell produces disappears when the block is not within the users direct field of view. This is specific to the BLOCK being outside of the view of the player, causing the graphic (laser) to disappear.
![cyclic1](https://user-images.githubusercontent.com/18114212/50643103-34c5e500-0fc1-11e9-8c55-c251bfbc991d.PNG)
![cyclic2](https://user-images.githubusercontent.com/18114212/50643105-355e7b80-0fc1-11e9-856b-7774c7e4f16b.PNG)

Crash log (if any):

**Comment by TinkererKhane** [comment]
Thanks mate! I'll try and report anything else I come across. Really awesome, useful mod :)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2657989
