### ISSUE TITLE
fluid extraction cable resets flow value on world load and maybe visually on chunk load

### ISSUE THREAD

**Issue by Xetaxheb** [Lothrazar/Cyclic#1034]
Minecraft version & Mod Version:
1.12.2 / Cyclic-1.12.2-1.15.12.jar little outdated as you might see, so sorry if it's been fixed already.
I'm using the Forever Stranded: Lost Souls pack.

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
If I leave the area and come back, even if they're chunkloaded, the GUI resets to 150 until I open and close and reopen it. Not sure if it affects flow rate.
If I save and quit and go back in (or restart game) they reset to 150 and for sure affect actual flow rate.

---
Another issue that this is unrelated to, but it's possible this other problem could be caused by the way FEC's handle transfers internally. https://github.com/vadis365/Mob-Grinding-Utils/issues/113

**Comment by Lothrazar** [comment]
yep this was fixed in a previous version, newest is 1.17.__ :) :)
