### ISSUE TITLE
[Big Feature Request] Multifunctional HOME Block!

### ISSUE THREAD

**Issue by GrzechuGrek** [Lothrazar/Cyclic#1037]
Hello. After long time I'm had at last come with untypical idea. Someday ago I did suggest for you a way to prevent spawn hostile mobs. Other day ago, I did suggest you to add a chunk loader, and you did tell me that this must to be a something innovative. 
Well... I always wanted to have a safe and functional area for base/home in a wild and dangerous MC world. I thinked about it a sometimes and at last I did got a idea! A Home block!

This is a one block only, but incredible usefull, maybe even must-have for each, who set a own place for base or home.
This block/machine does have a few very nessesary function suitable for home area, whose does: 
- dynamically loads active chunks area, like a chunkloader. 
- prevent a monsters from spawn in darknes, just like a magnum torch or peace candle.
- display a MC time, MC days that have passed from create mc world and display a real time.
- shows a affected area by home block's, like a preview from construction machine or use machine from Cyclic mod.
- any time when player enter or leave home area, a chat message will be displayed like "Welcome in Home, (player name)!", "Welcome back", or "Have a nice trip", "Good luck and watch out for creepers!" etc. 
- maybe will set a personal player's spawn.
- other things, whose can be invented.

Of cource these functions will can be a turn off, chunkloading function may request a fuel/power, etc. 
And this special block will be expensive to craft, and affect a 3x3 chunks area by default, but after upgrade may will affect 5x5, and after final upgrade will affect for 7x7 chunk area.

By mine idea, cunkloading function will request a fuel/energy, and monster's spawn prevent function will be work for free, however powered with redstone will turn off this.

**Comment by Lothrazar** [comment]
This would make sense especially there would only be allowed one per player per world, and a second wouldnt work.  Does sound like a lot of complex ideas :)

**Comment by GrzechuGrek** [comment]
> 
> 
> This would make sense especially there would only be allowed one per player per world, and a second wouldnt work. Does sound like a lot of complex ideas :)

In case multiplayers servers, yes, you right. But in single player mode, I don't see this restrictions to be needed.
