### ISSUE TITLE
[Feature/Item] Auto feeder for player

### ISSUE THREAD

**Issue by washinoboku** [Lothrazar/Cyclic#1038]
I was looking for this feature and there is not so much mods that feed the player automatically (1.12), so was thinking that gona be awesome to have in Cyclic.
Some item to put in baubles slot, like a bag or cointainer for food (like a tupperware) with some inventory to save different types of food and feed the player when need it, checking and replenish only the hunger bar with the hunger value of the item itself, ignoring saturation like FeederHelmet does.

I apologize if my english if bad, I'm native spanish speaker.

**Comment by Lothrazar** [comment]
Like a lunchbox or something that you fill with food and it auto feeds you.  Makes sense, i have seen similar items before
