### ISSUE TITLE
Cyclic::ItemGlowingHelmet_onEntityUpdate

### ISSUE THREAD

**Issue by RainOfPain125** [Lothrazar/Cyclic#1039]
Minecraft version & Mod Version:
1.12.2 - Cyclic-1.12.2-1.17.4.jar

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Biggest cause of lag according to my timings report. The description is simply "Cyclic::ItemGlowingHelmet_onEntityUpdate"

https://timings.aikar.co/?id=a2bd5fdedcb84ed2a6f0e3cdd9ecee15#timings

Crash log (if any):
N/A

**Comment by Lothrazar** [comment]
Hmm ill see if theres something I can do

Screenshot for backup reference 
![helmet update tick](https://user-images.githubusercontent.com/621529/51434368-db41f500-1c13-11e9-8cd2-b68d594679d5.PNG)

**Comment by Lothrazar** [comment]
It doesnt seem to be doing anything crazy. it has to fire to know when you remove the helmet to turn the effects off.  

It does not need to run every tick, i could turn that down, but then the player might feel some delay after changing it.  Maybe theres something i can optimize



https://github.com/Lothrazar/Cyclic/blob/c3d732c8cbf5fe3884ec64aeda3690c39591f5de/src/main/java/com/lothrazar/cyclicmagic/item/equipment/ItemGlowingHelmet.java#L73

**Comment by RainOfPain125** [comment]
Can't help at all, interesting to hear, glad to hear you'll be looking into it.

**Comment by Lothrazar** [comment]
I made some changes in the latest version, is the lag still the same? Is it better or worse?  https://minecraft.curseforge.com/projects/cyclic/files/2663412

 Also how do i record timings like this in single player for testing is this possible

**Comment by RainOfPain125** [comment]
@Lothrazar "I made some changes in the latest version, is the lag still the same? Is it better or worse?"

I mean, the entire modpack would have to be updated unless I wanted to manually go out and try to start up the server on the new version, then install the new ver on my computer. Which, my server machine can't handle both the normal and devtest servers running at the same time. And if I only ran the devtest version, nobody could connect unless they went through the hassle of installing the new cyclic. Generally hard for me to do any testing.

"Also how do i record timings like this in single player for testing is this possible"

I used a forge server running Sponge as a mod. Sponge comes with the great timings thing built into it. You can start timings by doing /sponge timings on, and then waiting ~10 minutes before doing /sponge timings paste

If you want to try and re-do the kind of behaviour we had, we were using Wooden Mob Spikes from Extra Utilities 2 until the mobs health hit zero, and let them sit there and bundle up until we came over and killed multiple of them in one hit.

If you think more mods are required to re-create it, or if you just want to download the entire pack in general and try to do it, the modpack was All The Mods 3. I'm actively trying to talk to the devs and get many things fixed within the pack so that real servers can be made around it. Previously things like Sponge were completely unsupported.

**Comment by Lothrazar** [comment]
Closing because bug is stale, code changes have been applied in an old version.  Can revisit in future with new samples if this re-occurs https://minecraft.curseforge.com/projects/sampler
