### ISSUE TITLE
Can't automate ender library.

### ISSUE THREAD

**Issue by PongoSapiens** [Lothrazar/Cyclic#1045]
Minecraft version & Mod Version: 1.12.2 1.17.15

Single player or Server: Server

Describe problem (what you were doing / what happened):
You can't "pipe" enchanted books in to the ender library, I've tried hoppers, cyclic item pipes, thermal expansion ducts, and refined storage exporters. With several of those, books were lost.

Crash log (if any):
N/A

**Comment by Lothrazar** [comment]
Yeah, it was never designed to work with pipes which is basically an oversight.  It was modeled after Storage Drawers but even that you can connect to the main controller.  

Ill have to upgrade the library with IO functionality that takes in enchanted books and outputs emtpy. Possibly with a GUI

**Comment by Lothrazar** [comment]
Update looks like this so far: no GUI for the controller but you can pipe books in and out 
![autom](https://user-images.githubusercontent.com/621529/52325491-0a898d80-299a-11e9-9762-1f6aa2e7a48b.gif)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2679842

**Comment by jc2008** [comment]
I love your ender library. I have some fishing farms pumping books, bows and fishing poles into it. The piping gets "stuck" when one of the enchantments reaches [64]. I have to manually take enchantments out the stack of 64 in the library to get it working again. Even with plenty of free space to make new holes, or making a new block with the same enchantment, it only seems to try to put into the first one which is full at 64.   Am I doing something wrong?

**Comment by DizzyDJW** [comment]
Still having this issue, but rather it's the Ender Library will at some random point stop accepting any enchanted books, whether there are open areas for them to go, or matching areas.

**Comment by dariusgemini** [comment]
> Still having this issue, but rather it's the Ender Library will at some random point stop accepting any enchanted books, whether there are open areas for them to go, or matching areas.

Probably because you have to pipe the empty books back out.

**Comment by DizzyDJW** [comment]
Already doing that, so unless there's some empty book clogging up the connection between the Ender Library and the bookshelves I'm out of ideas

**Comment by resetium** [comment]
Playing sf4, my ender library simply stopped accepting books after taking in exactly 5 shelves worth of books, even though normal books are being pumped out.
