### ISSUE TITLE
Monster Ball may not capture mobs but turn them into invisible

### ISSUE THREAD

**Issue by GoldenHashtag** [Lothrazar/Cyclic#1047]
Minecraft version & Mod Version:
1.12.2/17.15

Single player or Server:
Applies to both

Describe problem (what you were doing / what happened):
If you throw a Monster Ball, sometimes the mob won't be captured but they will become invisible until quit to title and load game / login server again. F3 + A won't work.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)
Suggestion:
Client side shouldn't do anything about making mobs invisible, leave server handle it.

**Comment by GoldenHashtag** [comment]
Here's a video explaining this better (Loading was trimmed):
[New video_Medium.zip](https://github.com/Lothrazar/Cyclic/files/2806380/New.video_Medium.zip)

**Comment by Lothrazar** [comment]
https://i.imgur.com/njvjyIv.gifv

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2679842

**Comment by Sonic1305** [comment]
Seems like the bug is still present but it happens only with specific entities. In our case it was the frost stalker from Alex's Mobs and some mob from Blue Skies.  (Playing on Server)
Cyclic Version 1.7.1
Minecraft: 1.18.2
TNP Limitless 5 Modpack.
