### ISSUE TITLE
(Suggestion) There should be a blacklist of which blocks can't be broken with Excavation enchantment

### ISSUE THREAD

**Issue by GoldenHashtag** [Lothrazar/Cyclic#1048]
When you break a log block from Dynamic Tree using Axe with Excavation enchantment, game crashes instantly, a blacklist solves this.

**Comment by GoldenHashtag** [comment]
> Do you have a crashlog? works for me
> ![works dyanm](https://user-images.githubusercontent.com/621529/52173466-16771480-273a-11e9-804f-2368ffa80f49.gif)

nevermind, i updated dynamic tree(0.8.2) to latest version (0.9.4) and it doesn't crash anymore, maybe it was a mod compatibility issue and its author fixed this issue.
but hey, a blacklist will help even if that issue still presents, cuz' i think there're still mods that don't work with excavation enchantment.

**Comment by Lothrazar** [comment]
A blacklist would be useful i suppose. However, trying to wrap everything up in a stable version without adding more feature creep. non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.
