### ISSUE TITLE
Ender Book Waypoints Incorrect

### ISSUE THREAD

**Issue by Bellamour** [Lothrazar/Cyclic#1050]
Minecraft version & Mod Version:
-Minecraft 1.12.2
-Cyclic 1.12.2-1.17.12
-Forge 14.23.5.2796

Single player or Server:
-Single Player

Describe problem (what you were doing / what happened):
-The Waypoints, that the Ender Book creates, are not accurate. I was teleported into the Mining Dimension while trying to teleport from one Overworld location to another Overworld location (Pictures below show one example). Each time I try to teleport somewhere, I am teleported to a different location in the mining dimension.

This is where I set the Waypoint
![mc cyclic bug 1](https://user-images.githubusercontent.com/47158736/51939051-93be2480-23dc-11e9-98e4-b5087f102a90.png)

I moved a couple blocks west and tried teleporting home, however this is where I ended up.
![mc cyclic bug 2](https://user-images.githubusercontent.com/47158736/51939063-9a4c9c00-23dc-11e9-8055-e4ab0772f306.png)

Crash log (if any):
-No

Extras:
-I thought it might have been only a dimension issue but since the coordinates do not match, I'm unsure where the issue lies or if there is anything I can do to correct this. I can do more testing if required.
-I realized with the Ender Book open, it was difficult to see my location, I changed the pictures.

**Comment by Bellamour** [comment]
Another thing to note, this does not happen if I'm mining from/to in another dimension. So if I'm in the End teleporting to somewhere in the end, it works properly, same for starting in the mining dimension. It's only the overworld that is messed up.

**Comment by Lothrazar** [comment]
Thats weird im testing this out now.

Overworld and nether seem ok at least in my test world. ill have to try mining dimension.


What modpack was this?

Also your base looks so amazing especially that archway

**Comment by Lothrazar** [comment]
Sorry, hopefully this was just a fluke becuas its been stable so far. in most modpacks ive been using it in.  PS love your build
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.
