### ISSUE TITLE
(Suggestion) Automatic user option to hold use/attack

### ISSUE THREAD

**Issue by gregoriousbig** [Lothrazar/Cyclic#1051]
I would love an option for the automatic user to hold down use and attack.

This was an option in the autonomous activator but that block doesn't exist in 1.12 version of thermal expansion/dynamics.

This allows blocks which has a longer activation time to be used in the automatic user.

I can't find any other mod which includes such feature anymore so I think it would fit this mod.

**Comment by Lothrazar** [comment]
I can try to see if this can be added.  Though, i would expect it would work the same with the timer slider set low such as 1 tick.

Can you give me an example of a modded block that works for hold-down-use, and one for hold-down-attack so i can test?

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.
