### ISSUE TITLE
Ender Book waypoints missing [also: add way to clone into another book]

### ISSUE THREAD

**Issue by InThayne** [Lothrazar/Cyclic#1052]
Minecraft version & Mod Version:
1.17.12
E2E pack

Single player or Server:
single

Describe problem (what you were doing / what happened):  
Loss of all waypoints currently stored.
Have backups but not sure where the waypoints might be located.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
The waypoints are currently just stored in the NBT data of the book, no outside storage. so exactly the same way enchants are stored.  Sadly i dont think theres a way to recover if they are gone.

I will look into a add a way to copy waypoints from one book to another to prevent this from future and allow in-game backups

**Comment by InThayne** [comment]
Ah, that makes sense- I must have wiped the NBT somehow.  Thanks for the fix.
