### ISSUE TITLE
having some trouble with the config

### ISSUE THREAD

**Issue by inconsistent-brick** [Lothrazar/Cyclic#1053]
First of all thank you, the config options is truly powerful and quite user friendly. I'm having some trouble finding some things in the list though.  Not sure if that's because they aren't there, are filed under something else or I'm just blind. If need be I can remove the recipe I guess, but if possible using cyclic's own config would be ideal.

so far I can't find engraved thunder, fluid tank, 
cyclic version 1.17.16

**Comment by Lothrazar** [comment]
Yeah at some point the item s got retextured and renamed, but i wasnt able to rename the configs, so some of them have bad names.  I will be redoing the whole config file in 1.13 but for now its kind of stuck.

Tanks are B:BucketBlocks
thunder is i think B:EnderLightning

**Comment by inconsistent-brick** [comment]
Thanks for clearing this up!
