### ISSUE TITLE
Ender library does not update display when automated.

### ISSUE THREAD

**Issue by Godisemo** [Lothrazar/Cyclic#1054]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.17.13

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
As already noted in #1045 the ender library is not able to be automated, however this can be done using some sort of automated user. The issue is that when this is done the displays on the ender bookshelf does not update the current number of enchants stored. The correct numbers are displayed in the chat when clicking on the respective shelf though.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Im fixing this as part of this other feature.  It may not always work with the user, but once the update is out it will work with hoppers & pipes, and it does refresh right away 

https://github.com/Lothrazar/Cyclic/issues/1045

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2679842
