### ISSUE TITLE
Add an option for the reverse of Pulse in the Password Trigger block

### ISSUE THREAD

**Issue by GreatestFool** [Lothrazar/Cyclic#1055]
Add another option for Password Trigger block. Currently there is only On/Off and Pulse mode. A mode that is the opposite (redstone signal wise) of the Pulse mode would be greatly appreciated. So that it sends out a redstone signal until the password is received before turning off for a little and then turning on again. Essentially a reverse redstone pulse.

Currently I'm building something in a tiny confined space, and cyclic is an amazing mod, but I sadly can't make the build work properly without repeating the password twice to close the door behind me. I'd greatly appreciate if this can be added, it'd help out a lot.

_**e:**_ While I can just place a redstone torch on top to do it (which I didn't think about until now), that does require an extra block of space, which can be detrimental. It would also be nice to be able to increase or decrease how long the pulse lasts if possible, but that's far from necessary should it be a pain to implement.

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports
