### ISSUE TITLE
Walking into an Interdiction Pulsar pushes away and suffocates Players

### ISSUE THREAD

**Issue by ConnorMiner** [Lothrazar/Cyclic#1056]
Minecraft version & Mod Version:
Minecraft: 1.12.2
Forge: 14.23.5.2781
Cyclic: 1.17.15

Single player or Server:
Single Player (may also affect servers)

Describe problem (what you were doing / what happened):
When flying into a bunch of interdiction pulsars on a single block, a 2D render of the block was displayed and suffocation damage was received. Upon walking into the side of the block headfirst, damage was received, and the player was pushed back. Walking into it without putting the head in the block yielded a similar knockback (without the damage). Flying into the bottom of the block had no unusual effects.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2679842
