### ISSUE TITLE
Hydrator Dupe & Recipe Issues

### ISSUE THREAD

**Issue by NillerMedDild** [Lothrazar/Cyclic#1059]
Minecraft version & Mod Version:
- Minecraft 1.12.2
- Cyclic-1.12.2-1.17.15 (Nothing in the changelog indicated changes to the Hydrator)

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
First issue: A good example of this is the Sponge recipe. 
The Sponge requires 4 items, Yellow Wool, Soulsand, Prismarine Shards and Slime Balls.
Yellow Wool is used in another recipe, Dyed Wool -> White Wool, because of that, the White Wool is created, and the rest of the inputs are ignored.

Second issue: If there is an item in the output slots, any Hydrator recipe will add to that item, instead of creating it's actual output. So any item that can be made with the Hydrator (except Sponges) can be duped.

Crash log (if any):

**Comment by Lothrazar** [comment]
after going back and forth on some things, and considering how the lock button tries to work,  the cleanest solution is this.

splitting into 2 machines, hydrator will be a 1-input only recipe 

new machine (unnamed) will be a 4x4 + liquid only crafter

**Comment by Lothrazar** [comment]
well maybe not. might not go that far. thoughts?

**Comment by NillerMedDild** [comment]
I would have the Hydrator wait 40-60 ticks before it activates, so the player has some time to input all ingredients. 

Additionally, I think 1 ingredient recipes should be blocked if there are more than 1 different ingredient in the Hydrators inventory. The same should go for 2 and 3 ingredient recipes.

**Comment by Lothrazar** [comment]
Right, so.  

if the left side has 2 slots filled, then only search through 2 - input recipes. same for 1,2,3,4  .

**Comment by NillerMedDild** [comment]
That would prevent the automation of 1 and 2 input recipes, as the left side would fill up. 
If the left side has two different items in it, only search through 2 input recipes, same for 1-4.

**Comment by Lothrazar** [comment]
In the process the recipes all might end up as shapeless. kind of an improvement really

**Comment by NillerMedDild** [comment]
Agreed :)

**Comment by JakeMoe** [comment]
If I understand this correctly, then a) this is why when I'm trying to make grass blocks, I'm losing 1 grass and gaining 1 farmland (the actual recipe is 1 dirt to 1 farmland, but the dirt is in the bottom two slots), and b) this should be fixed when Cyclic 1.18.0 is released?

**Comment by CritFlaw** [comment]
Yeah I'm having an issue where it won't make grass blocks, only farm-land, on version 1.17.16. Not sure if it's related to this.

**Comment by Lothrazar** [comment]
1.18.0 is out now fixing this, please report anything else https://minecraft.curseforge.com/projects/cyclic/files/2679842

**Comment by NillerMedDild** [comment]
Thank you.

**Comment by CritFlaw** [comment]
Thanks!
