### ISSUE TITLE
[Question] Configurable Uncrafting Grinder Speed?

### ISSUE THREAD

**Issue by Andronomos** [Lothrazar/Cyclic#1062]
Minecraft version & Mod Version:
1.12.2-1.17.15

Single player or Server:
SP

I've asked this back in 2018 but haven't heard much about it since. Is a config option for the speed planned? This is the only thing really keeping me from using the Uncrafting Grinder in real set-ups.

With a tier 5 spawner from SoulShardsRespawn, a Mob Masher from MobGrindingUtils and the LootBags mod installed I can easily get hundreds of items a minute. A lot of which can be ground down into valuable resources and other grindable items.

At the moment the grinder takes like 10 to 15 seconds per item which causes my system to get backed up and the world to lag when mob loot has no where to go and piles up on the ground.

Using more grinders is of course an option but not really a viable one in my opinion. I find it difficult to keep them powered if I don't give them each a high tier energy cell from ThemalExpansion and I would probably need a few hundred of them to process all of the items I can get from 1 farm.

Another option is to use an item that speeds up ticks in an area. This isn't too bad of an option but items like these can be finicky when it comes to game performance.

**Comment by Lothrazar** [comment]
The time is in config near where the RF power settings are, around line 1180 


        # Number of ticks needed to perform one action by this machine [range: 1 ~ 9000, default: 150]
        I:uncrafting_block=150

**Comment by Andronomos** [comment]
Oh, awesome! Wasn't there the last time I looked many version ago. I should've checked first. My bad.
