### ISSUE TITLE
Being kick when using Ender Wing

### ISSUE THREAD

**Issue by sandtechnology** [Lothrazar/Cyclic#1065]
Minecraft version & Mod Version:
1.12.2&1.17.16

Sponge version:
[1.12.2-2768-7.1.5(the latest stable version)](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2768-7.1.5/spongeforge-1.12.2-2768-7.1.5.jar)

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Install Sponge and Cyclic on your server,open your inventory,right-click the Ender Wing ,and you will be kicked.
I think it is same as this issue:https://github.com/SpongePowered/SpongeForge/issues/2301

log (if any):https://paste.ubuntu.com/p/kW2qBYJS57/

**Comment by Lothrazar** [comment]
Apparently net.minecraft.util.CooldownTracker  is not threadsafe for the player (maybe just sponge, maybe both).  Regardless it looks like a small fix

**Comment by Lothrazar** [comment]
I wasnt able to replicate or test this fix, but the issue should be resolved based on links and log
