### ISSUE TITLE
Redstone Clock setting resets on leaving/reentering world

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/Cyclic#1066]
Minecraft version & Mod Version:
MC: 1.12.2
Cyclic: 1.18.0

Single player or Server:
SP

Describe problem (what you were doing / what happened):
I have a redstone clock set to require redstone to activate. When I leave that world and reopen it the setting is back to "Always on". It seems like this setting is not saved.

Crash log (if any):
N/A

Thanks!
Darkosto

**Comment by Lothrazar** [comment]
1.18.0 released on curse with this fix
