### ISSUE TITLE
CTD activating or deactivating spikes

### ISSUE THREAD

**Issue by xenoflot** [Lothrazar/Cyclic#1067]
Minecraft version & Mod Version:
Stoneblock 1.0.33
1.12.2 
Cyclic-1.12.2-1.17.9 

Single player or Server:
Single 

Describe problem (what you were doing / what happened):

I've had a few ConcurrentModificationException CTDs when working with a largeish (16x3) group of diamond spikes. Spikes were placed on Stone with an array of EnderIO redstone conduits under the stone. When I'd break one of the conduits, or flip the lever, I'd hear the spike sound then the game would freeze and CTD. I didn't have issues when working with a small (3x3) group of spikes. I've had very few crashes with this pack except when toggling the spikes. Breaking the spikes when they were inactive didn't cause a crash.

Cheers!

Crash log (if any):
https://gist.github.com/xenoflot/5094648b4ec20a03a500a25fc598ce15

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Weird, no direct lines of code but its related somehow to playing sound . needs investigating

at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:252)

**Comment by Lothrazar** [comment]
sound system still seems solid, very hard to replicate.  Also seems identical to this "caused by forge/vanilla" issue https://github.com/Lothrazar/Cyclic/issues/704
