### ISSUE TITLE
BUG: Disabling heart_food causes food_step and inventory_food to be lost on death.

### ISSUE THREAD

**Issue by spdkils** [Lothrazar/Cyclic#1069]
Minecraft version & Mod Version:
1.12 Forge
Latest I think .16 and .15

Single player or Server:
Both

Describe problem (what you were doing / what happened):
Every death you lose the step bonus, confirmed with NBT viewer etc.

Crash log (if any):
No crash

After spending several hours on a custom server build (Enigmatic 2 Expert) and testing every mod for compatibility, and doing a ton of tests... I figured out that if you disable hearts in the config, you lose all buffs when you die every time.

Even if you ONLY have cyclic mod installed, no hearts, no NOTHING once you die. All tags re-written.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2679842
