### ISSUE TITLE
[Request] Config option to allow grinding enchanted items 

### ISSUE THREAD

**Issue by Andronomos** [Lothrazar/Cyclic#1070]
Would you be willing to add a config option to the grinder to allow it to grind enchanted items? The enchantments can be discarded, no need to add a book to the result.

Since currently the grinder doesn't support enchanted items and I am unable to find any reliable methods for disenchanting or filtering large amounts of items with lots of different damage values and nbt data from my mob farm my only option is to trash them. Being able to grind them into useful resources would be much appreciated.

**Comment by Lothrazar** [comment]
You can use the Void Anvil to strip off and delete all enchantments, and just feed them in :)

**Comment by Andronomos** [comment]
Oh wow, that works really nicely. I need to spend more time looking through the mod before I make requests, sorry to keep pestering you.
