### ISSUE TITLE
[suggestion] bounce/hit with multi-jump?

### ISSUE THREAD

**Issue by Seth0067** [Lothrazar/Cyclic#1071]
I'd like to propose a new level to multi-jump that damages mobs. You did such a good job making the sfx sound like mario, that I want the full package.

Bonus points to make coins drop on death, especially if you can melt them down in tinkers. I'll do the art if you need some.

**Comment by Lothrazar** [comment]
Sounds fun, maybe a bit overpowered.  Kind of like spike boots

**Comment by Seth0067** [comment]
Well, leave the damage tweakable, maybe? Just a thought!

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.  Can use bounce potion effect for something similar
