### ISSUE TITLE
[Question] Grinder Texture Location

### ISSUE THREAD

**Issue by Andronomos** [Lothrazar/Cyclic#1072]
I'm interested in adding Cyclic to a private custom resource pack but I am unable to find the texture files for some of the blocks like the grinder and automated user inside the jar or the repo here.

What am am I missing?

**Comment by Lothrazar** [comment]
Many blocks are pulling in vanilla textures as part of their model.

SO to do this in a resource pack you just need to copy in the block model JSON file and change the textures it points to

https://github.com/Lothrazar/Cyclic/blob/c3d732c8cbf5fe3884ec64aeda3690c39591f5de/src/main/resources/assets/cyclicmagic/models/block/uncrafting_block_south.json

**Comment by Andronomos** [comment]
Oh, damn. I didn't know that was something you could do. Thank you.

**Comment by Andronomos** [comment]
I've managed to get texture replacement working now I'm working on altering the models. If I ever get the resource pack to a state I'm happy with would I be allowed to share it?
