### ISSUE TITLE
Item Transfer Node

### ISSUE THREAD

**Issue by jackrtades** [Lothrazar/Cyclic#1074]
Minecraft Version:  1.12.2

Mod Version:  1.18.0

Single Player or Server: Single Player

Describe the problem (what you were doing / what happened):
Using the Item transfer node it's not accepting items.

Log file (text block or link):

Video/images: (links are great; GitHub also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2685793
