### ISSUE TITLE
Sack of Holding Config Does Not Blacklist Correctly

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/Cyclic#1077]
Minecraft Version: 1.12.2

Mod Version: 1.18.1

Single Player or Server: SP

Describe problem (what you were doing / what happened):
adding "parabox:parabox" to the sack of holding blacklist "deletes" the block and produces and error:

The log is Parabox complaining, not cyclic. but this is the text on screen when the sack is used on the parabox

"Error on Pickup - Null block state or tile entity"

**Comment by Lothrazar** [comment]
I cant replicate this in 1.18.1, it just works fine as is. Regular click opens the GUI, sneaking click just shows this popup shown below.  

Im using these versions, maybe outdate? 

Parabox-1.12.2-1.0.0-the-one-that-has-better-info.jar
Prestige-1.12.2-1.1.0-the-one-that-compensates-for-things.jar

(but while investigating i found a simlar issue where an empty line in that config crashes the game)


![1182](https://user-images.githubusercontent.com/621529/54075150-a6840e80-4250-11e9-94ef-5242aaa8eb2a.gif)

**Comment by Darkosto** [comment]
I’ll need to test this in a new world. The world may have been broken for the paradox. We can close this issue for now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
