### ISSUE TITLE
Uncrafting Grinder mod compatibility with blocks that use NBT instead of metadata

### ISSUE THREAD

**Issue by Freebi85** [Lothrazar/Cyclic#1079]
Minecraft Version: 
1.12.2
Mod Version: 
1.17.16

Single Player or Server:
Signle Player

Describe problem (what you were doing / what happened):
Dupe bug with Uncrafting Grinder from Cyclic. You can put "Basic Bin" from Mekanism in there and it gives you 2 Atomic Alloys, Elite Bin and one Ultimate Control Circuit. o_O

Log file (text block or link):

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment]
OOF i hate mods like mekanism that use NBT for items instead of metadata. so annoying.  Its not a dupe bug its because all 5 bins have the exact same block id AND same block name AND same block metadata

**Comment by Lothrazar** [comment]
Also you can just blacklist these items too if you need to

**Comment by Freebi85** [comment]
Haha yes I hate that too when I have to code recipes with mekanism.  But no problem I blacklisted the whole mod 😉

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2685793
