### ISSUE TITLE
Diamond Anvil no longer repairs Tinkers Construct items

### ISSUE THREAD

**Issue by pneuma163** [Lothrazar/Cyclic#1080]
Minecraft Version: 1.12.2

Mod Version: 1.18.1

Single Player or Server: Single Player

Describe problem (what you were doing / what happened): I'm playing Enigmatic 2 Expert which just updated to 1.57. In 1.56 the Diamond Anvil from Cyclic repaired tools from Tinkers Construct and PlusTiC exactly as Vanilla items are repaired there. In 1.57, which I think updated to Cyclic 1.18.1, the slightly damaged tool moves over to the right side of the Diamond Anvil's GUI as if it is done being repaired but no change in the tool's damage has taken place. As far as I can tell, this is not a config change by the developers of E2:E - the black list for the Diamond Anvil in the Cyclic config file only includes items from other mods (the default settings, in fact).

Log file (text block or link):

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by KingCookiee** [comment]
I can confirm that this also happens on servers and extends more than tinker tools, It extends to tools like the hammer from immersive engineering and cutters from IC2 and even coffee from pam's harvestcraft. but still works on items like chisel. I could not find any documentation if this feature was intended.

**Comment by RealGrep** [comment]
I think I see the problem (thanks to jmoiron on the Enigmatica 2 Discord for finding it). I think it's in this change:

https://github.com/Lothrazar/Cyclic/commit/d754d02af5472b67c2df9ccd700c1562b0f388bc

The logic seems a little flipped. You're using a new canRepair function to detect if it's done and put the item in the output slot, right? Logically, that should be if it can't repair, so !canRepair(...) seems correct.

But also the logic in that function is flipped a bit. It returns the result of this:

```
inputStack.isItemDamaged() == false ||
inputStack.getItem().isRepairable() == false ||
isBlockAllowed(inputStack) == false
```

Being as the function is called "canRepair", part of the logic is wrong. If it can repair it, then it should be damaged, and so inputStack.isItemDamaged() == false should be looking for true, not false. But other clauses there are correct, so they don't match. If the item is not repairable, then canRepair should return false. Anyway, hopefully you see the problem now.

**Comment by MaxNeedsSnacks** [comment]
The logic in general seems to be pretty odd, I just... feel like there's an exclamation point missing before the if statement lol

**Comment by Lothrazar** [comment]
Yeah i will have to add a config for this.


the new way is correct. since the tinker tools say "I AM NOT REPAIRABLE"

But i can see the use case for some modpacks to want to allow this.  so with a config override a modpack dev can say 

"YEs allow it to repair non-repariable items:

**Comment by MaxNeedsSnacks** [comment]
Oh that's good to know, I actually thought it was unintentional.

Quick question though, is there any reason in particular why the method names are the opposite of what their return value indicates?

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2685793
