### ISSUE TITLE
[1.12.2] Soul Stone doesn't account for Absorption or any Damage Reduction. It also ignores the Focus Sash from Dark Utilities.

### ISSUE THREAD

**Issue by Z-Tunic** [Lothrazar/Cyclic#1081]
Minecraft: 1.12.2
Forge: 14.23.5.2808

Mods: 5
Bookshelf-1.12.2-2.3.573
Cyclic-1.12.2-1.18.1
DarkUtils-1.12.2-1.8.0
ScalingHealth-1.12.2-1.3.33+135
SilentLib-1.12.2-3.0.13+167

-----

The Soulstone which revives you with 6 health appears to not take into account for Absorption as well as any damage reductions meaning that if you have a lot of absorption or defense but low health and you take damage... the Soulstone will revive you. An example...

![](https://cdn.discordapp.com/attachments/377171551155650560/553262333426925569/cyclicabsorbsoulstone.PNG)

Top part I have 1 health and 44 Absorption. I take damage from the Diamond Spikes which deals 5.0 with no damage reductions. The results? The Soulstone procs putting my health to 6 and applies the usual potion effects as shown on the bottom part.

Now in this next example I am wearing a full set of Diamond Armor which will reduce the damage from the Diamond Spikes from 5.0 to 1.25.

![](https://cdn.discordapp.com/attachments/377171551155650560/553263052493946933/cyclicarmorsoulstone.PNG)

Top part I have 3 health and wearing a full set of Diamond Armor. I take damage from the Diamond Spikes which should only deal 1.25 damage due to the armor I'm wearing but instead... the Soulstone seen it as a fatal attack so it revives me as shown in the bottom part.

Damage was NOT scaled via Scaling Health during these tests.

One more thing to mention is that it appears the Soulstone has a higher priority which conflicts with the Focus Sash from Dark Utilities. The Sash leaves you with 1 health if you took a fatal hit at full health but if you have a Soulstone... it will ignore the Sash.

If I used a Totem of Undying instead... the Sash procs first and then the Totem if you took damage after it saved you.

**Comment by Lothrazar** [comment]
Im not sure how its supposed to work with focus sash but i fixed with absorption. does this look right

![soulstone](https://user-images.githubusercontent.com/621529/54093045-85a2e280-4350-11e9-96d4-2620de9f17c0.gif)

**Comment by Lothrazar** [comment]
i set soulstones event to LOWEST priority and it cancels it if it gets consumed which should help compatibility

**Comment by Z-Tunic** [comment]
It might've been the way the priority works which is why the soulstone procs before the sash. As for it working... I'll have to check with the damage reductions I've used when I encountered the issue. Such reductions were Angel of Vengeance's Shield of Faith spell which cuts all damage taken by 50%.

In that image... you need to have 1 health remaining and have any Absorption Hearts, since cactus deals 1 damage and even if you had like 50 absorption but with 1 health it will proc the soulstone.

**Comment by Z-Tunic** [comment]
Absorption with low Health appears to be fixed now. However...

Soul Stone still only accounts for the original damage value instead of the reduced damage value via damage reductions such as Armor, Protection, Resistance Potion effect, modded reductions like Angel of Vengeance's 'Shield of Faith' spell which cuts all damage taken by 50%, RPG Inventory's Buff'd Gloves which gives a 20% Damage Reduction, Living Enchantment's Damage Reduction which reduces damage by a certain percent depending on it's level.

A full set of Protection IV Diamond Armor Set VS Diamond Spikes = 0.45 damage taken. No Armor VS Diamond Spikes = 5.0 damage taken.

If my overall health is 5... and I touch the Diamond Spikes with a full set of Diamond Armor with Protection IV... the Soul Stone will proc even though the damage was less than 1... or 0.45 to be exact which isn't fatal. If I was using the 'Shield of Faith' spell but with no armor... that 5.0 damage lowers to 2.5 damage which... will still procs the Soul Stone despite the hit not being fatal.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2685793

**Comment by Lothrazar** [comment]
Ill follow up based on your latest comment , reopened issue

**Comment by Z-Tunic** [comment]
https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/177

So... I've opened an issue about it on "Dark-Utilities" side and the Soul Stone uses 'entityHurtEvent' which is perhaps why the Focus Sash doesn't work as the Soul Stone takes over when you get hurt.

Try changing Soul Stone's event from 'entityHurtEvent' to 'livingDeathEvent'?

**Comment by Lothrazar** [comment]
@darkhax can we DM about this sometime?  i set it to lowest priority, not sure if theres anything we can fix.

**Comment by Z-Tunic** [comment]
Tested the new version, Soulstone now works correctly with the Focus Sash as well as accounting for damage reductions, even modded damage reductions.

**Comment by Lothrazar** [comment]
Thanks for responding and confirming the fix!
