### ISSUE TITLE
Hydrator "caching" old recipe

### ISSUE THREAD

**Issue by xenoflot** [Lothrazar/Cyclic#1082]
Minecraft Version: 1.12.2

Mod Version: 1.17.16 (Stoneblock 2, 1.7.0-1.12.2)

Single Player or Server: SSP

Describe problem (what you were doing / what happened):
I had been using a Hydrator to turn Terracotta into Clay. It was a bit sporadic with the inventory and I needed to move things about from time to time to get it to start processing again. I think that got fixed in bug report #1059  This issue may be related.

I put some Gray Concrete Powder into the Hydrator and it started turning it into Clay. I took it out and put it into the EnderIO tank underneath which then hydrated it correctly however because the tank was feeding water to the Hydrator, it also passed the Gray Concrete up and the Hydrator started turning it into Clay as well!

I broke the Hydrator and re-placed it and it's now ignoring the Concrete as expected.

Log file (text block or link):
None

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment]
This is how it works in 1.18.1 .  I think this is ok in this version, what do you think can you test it too

![hyd cache](https://user-images.githubusercontent.com/621529/54076208-d1289400-425d-11e9-8cda-fde914ef41d1.gif)

**Comment by glepet1962** [comment]
I can confirm that updating to the latest release (1.18.2) worked for me. Thanks!
