### ISSUE TITLE
Labeling Error?

### ISSUE THREAD

**Issue by Yonk316** [Lothrazar/Cyclic#1083]
Minecraft Version: 1.12.2

Mod Version: Cyclic-1.12.2-1.18.1

Single Player or Server:SP

Describe problem (what you were doing / what happened):
Mislabeled Crystal Pickaxe
![2019-03-08_10 43 16](https://user-images.githubusercontent.com/42360206/54038925-b7b91680-418f-11e9-8842-c5d0da4acdee.png)

Log file (text block or link):

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Yonk316** [comment]
![2019-03-08_11 04 40](https://user-images.githubusercontent.com/42360206/54039979-42027a00-4192-11e9-8ec2-a8358635a95a.png)

**Comment by Yonk316** [comment]
second screenshot is with cyclic loaded only

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2685793
