### ISSUE TITLE
Harvester doesn't harvest ender lilies from extra utilities 2

### ISSUE THREAD

**Issue by XxZajoZzO** [Lothrazar/Cyclic#1084]
Minecraft Version: 1.12.2

Mod Version: 1.18.1

Single Player or Server: SP

Describe problem (what you were doing / what happened):
Harvester doesn't harvest ender lilies from extra utilities 2 (Pack is enigmatica 2)
Might be realted to https://github.com/Lothrazar/Cyclic/issues/1024

Log file (text block or link):

Video/images: 
![Screenshot](https://user-images.githubusercontent.com/13818400/54153527-1d332e80-4440-11e9-964f-6d657d63fbf0.png)

**Comment by Lothrazar** [comment]
I'm pretty sure the ender crop mod works.
https://minecraft.curseforge.com/projects/ender-crop

ill see about adding a patch to work with the EXU2 version .  Luckily its open source now so it should be easy based on https://github.com/rwtema/Extra-Utilities-2-Source/blob/846a0a59f603c4a60f02d3a6fedc4e468e4ea229/1.10.2/src/main/java/com/rwtema/extrautils2/blocks/BlockEnderLilly.java#L44
