### ISSUE TITLE
Nether ores not disableable

### ISSUE THREAD

**Issue by DelviousCrafts** [Lothrazar/Cyclic#1085]
Minecraft Version: 1.12

Mod Version: 1.18.2

Single Player or Server: Both

Describe problem (what you were doing / what happened): 
Nether ores no longer following the generation rules set in the configs. I've tried setting global rules to false and setting everything to false and zero spawn, and doing both and still have nether ores spawning in the nether and enabled in game. And for the sake of completeness yes the Dim -1 folder was deleted each time.

Log file (text block or link): 

[latest.log](https://github.com/Lothrazar/Cyclic/files/2954034/latest.log)
[cyclic_ores.txt](https://github.com/Lothrazar/Cyclic/files/2954046/cyclic_ores.txt) (set as text to upload here, but is proper unsupported for drag and drop cfg file in configs.)

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)
![2019-03-11_13 25 26](https://user-images.githubusercontent.com/46658624/54155433-5d26f100-4401-11e9-9817-10a10ab0e533.png)
![2019-03-11_13 25 45](https://user-images.githubusercontent.com/46658624/54155434-5dbf8780-4401-11e9-8db8-0be74700fcfd.png)
![2019-03-11_13 26 07](https://user-images.githubusercontent.com/46658624/54155435-5dbf8780-4401-11e9-9fe6-fcef0422f130.png)
![2019-03-11_13 26 14](https://user-images.githubusercontent.com/46658624/54155436-5e581e00-4401-11e9-91fd-42456fd59909.png)

**Comment by Lothrazar** [comment]
If you set these to false in the main config (line 300 ish) the blocks will be totally deleted.   



        # Generate ore in the end.
        B:"End Ore"=false
   

        # Generate ore in the nether.
        B:"Nether Ore"=false

**Comment by Lothrazar** [comment]
![delete](https://user-images.githubusercontent.com/621529/54411308-1e689380-46ac-11e9-9a5c-994cdc2a8b71.PNG)

**Comment by DelviousCrafts** [comment]
Perhaps then consider making a point to put that in the ore's config to help alleviate confusion possibly. thank you for pointing this out to me.

**Comment by Lothrazar** [comment]
I know the configs are not great.  and confusing.  In 1.13 ill be reorganizing the config and also making all the ores a standalone mod
