### ISSUE TITLE
Controlled Miner have Mining Level Problem

### ISSUE THREAD

**Issue by Fireztonez** [Lothrazar/Cyclic#1086]
Minecraft Version: 

Mod Version: I have currently the version 1.8.0 installed on my modpack, but Darkphan have the 1.8.2 and the issue is exactly the same... So, the problem is there for multiples versions now...

Single Player or Server: Both... I have try on Single Player, but I saw Darkphan having the same issue during is live and is playing on server.

Describe problem (what you were doing / what happened): When the miner try to mine a block it tyake a lot of time and if the block need to have a certain mining level to drop, it will just break and doesn't drop anything... 

To be more clear, I have make a little video question to show you the issue: https://streamable.com/hzai3

Logs is not needed for that issue, but, heres the mod list I have now, if it can help you (Sorry, I don't have the mod list of the Darkphan Modpack):
https://gist.github.com/Fireztonez/282214842a0b04115c9fedb5b7f062ee

If you need something else, just ask me and I will try my best to help you with that!
Fireztonez

**Comment by Lothrazar** [comment]
Thanks for the video and very detailed report.

Looks like it doesnt have any tools equipped, so its mining with an empty fist.  It should be able to use any tool

![equip](https://user-images.githubusercontent.com/621529/54411102-5ae7bf80-46ab-11e9-9792-a085b8bbea99.PNG)

**Comment by Fireztonez** [comment]
:o that's why... you have to provide a tool and the miner use the tool to mine things...
I'm just dump... 

And last thing, I don't know if you already know that issue, but is there for long time, the energy bar on machines doesn't show correcly the amount when you play on server and I saw again this issue during the stream of Darkphan... I can't make a video right now for that, but, if you whant I can create a new issue for that and give you the most detail possible and make a video when I can...

**Comment by Lothrazar** [comment]
Thanks, im checking on the server power issue now.  I have no memory of anyone mentioning it to me, but maybe darphan said it on stream and i forgot

**Comment by Fireztonez** [comment]
Yeah I see,
I saw that bug a lot of time, and I always think somebody have already reported that and I think everyone with that issue think the samething but nobody have take a look!

The classic, most people doesn't report anything and the the rest assume frequently that the problem is probably already reported! I shouldn't know that and stop assuming things like that...
