### ISSUE TITLE
Powered Diamond Anvil Power display wrong [Server only: energy RF display bars are desync from client. affects many machines]

### ISSUE THREAD

**Issue by dagantang** [Lothrazar/Cyclic#1087]
Minecraft Version: 1.12.2

Mod Version: 1.18.3

Single Player or Server:Server

Describe problem (what you were doing / what happened):
Powered Diamond Anvil Power display wrong

Log file (text block or link):

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment]
All you said was "wrong" . sorry i dont understand. whats wrong about it precisely? What did you exactly do and what was meant ot happen? Where was its power coming in from?


This is how it looks to me

![wat](https://user-images.githubusercontent.com/621529/54480613-aacba100-47e7-11e9-9442-2d5a95662005.gif)

**Comment by Lothrazar** [comment]
Nevermind i did find an issue thanks to some feedback over here https://github.com/Lothrazar/Cyclic/issues/1086

**Comment by dagantang** [comment]
I am so sorry for too less word for the description. 
![2019-03-17_04 16 33](https://user-images.githubusercontent.com/32885622/54481151-0b9cbd00-486c-11e9-96f2-86ff5779d51b.png)
![2019-03-17_04 17 00](https://user-images.githubusercontent.com/32885622/54481152-0b9cbd00-486c-11e9-9136-e335931f08b7.png)
![Uploading 2019-03-17_04.17.04.png…]()
when i first time open Anvil is no problem but when the second time opened it then its disappear.
Sorry for my poor english.

**Comment by dagantang** [comment]
![2019-03-17_04 17 04](https://user-images.githubusercontent.com/32885622/54481217-c927b000-486c-11e9-98e1-d8ac40bf6e30.png)

**Comment by Lothrazar** [comment]
Thanks for all the updates and screenshots, im on my way to a fix
