### ISSUE TITLE
[Help] Changing Blockstates with Resource Pack

### ISSUE THREAD

**Issue by Andronomos** [Lothrazar/Cyclic#1090]
I'm trying to make a texture for the on and off state of the Wireless Transmitter/Receiver. I've put the model and textures files in my pack but as you can see in the GIF only the Wireless Receiver works.

[![Image from Gyazo](https://i.gyazo.com/0f5c94893603ec69299d113af6accc5e.gif)](https://gyazo.com/0f5c94893603ec69299d113af6accc5e)

### Texture
\resourcepacks\my_resource_pack\assets\cyclicmagic\textures\blocks\wireless_transmitter_on.png
[![Image from Gyazo](https://i.gyazo.com/19c46e28819a316d2bed4b61564e55f1.png)](https://gyazo.com/19c46e28819a316d2bed4b61564e55f1)

### Model
\resourcepacks\my_resource_pack\assets\cyclicmagic\models\block\wireless_transmitter_on.json

`{
    "parent": "block/cube_all",
    "textures": {
        "all": "cyclicmagic:blocks/wireless_transmitter_on"
    }
}`

### Blockstate
I am not including a blockstate file in my resource pack because the native file already has a powered variant included so in theory I should only need to include the model file it's pointing to. But just to make sure I also tried including the blockstate in my resource pack to no avail.

\resourcepacks\my_resource_pack\assets\cyclicmagic\blockstates\wireless_transmitter.json**
`{
    "variants": {
        "powered=true":  { "model": "cyclicmagic:wireless_transmitter_on" },
        "powered=false": { "model": "cyclicmagic:wireless_transmitter_off" }
    }
}`

I've read through the Minecraft Wiki about models and resources packs. I've also googled a lot about blockstates and other resource pack tid bits and everything I've found leads me to believe I've done everything correctly. So I'm really confused as to why it's not working. Any help you could provide would be much appreciated.

**Comment by Andronomos** [comment]
@Lothrazar Don't want to be a pain just hoping you can take a look at this.

**Comment by Lothrazar** [comment]
Hey thanks for your patience  i have time to sit down for this now.  Ill drop your versions in code and see whats up, they look right

**Comment by Lothrazar** [comment]
Hmm , looks like  its because its not supported in code . 

In one of the blocks it sets the blockstate in code https://github.com/Lothrazar/Cyclic/blob/c3d732c8cbf5fe3884ec64aeda3690c39591f5de/src/main/java/com/lothrazar/cyclicmagic/block/wireless/TileEntityWirelessTr.java#L62 but in the other it doesnt.

So ill add a default texture and a code change for the blockstate so this is supported in both blocks

**Comment by Lothrazar** [comment]
when 1.18.6 is released i made the fix 
![newstate](https://user-images.githubusercontent.com/621529/55291372-c8296f00-5392-11e9-944b-15cef0465e45.gif)

**Comment by Andronomos** [comment]
Sweet, thank you!
