### ISSUE TITLE
Item Cable is really laggy and can probably caused a lot of Server Lags.

### ISSUE THREAD

**Issue by Fireztonez** [Lothrazar/Cyclic#1092]
Minecraft Version: 1.12.2

Mod Version: Cyclic 1.18.4
Forge: 14.23.5.2823

Single Player or Server: Test in Single Player, but on server it will be probably the same...

Describe problem (what you were doing / what happened):
I test multiples pipes with LagGoggles, and the Item Cable from Cyclic is really extremly laggy... The amount of us/t is really really high, so I think you should look to optimized the Item Cable and Extraction Cable because on Server it have big chance to cause insane amount of lags if used a lot... For now, I have turn off into my modpack (Because is made specifically to work on server). This is bad, because I really really enjoy Cyclic and this is fun to used something different than usual...

For this test I have used Storage Drawer, 1 with Creative Vending Upgrade (At the left) and 1 with Creative Storage Upgrade (For the output, at the right of the picture,  So the drawer is never full...)

Take note, all cables here is top level with the max amount of upgrade (for AE2 and EnderIO, teh rest doesn't)... At the bottom of the Picture, you see Mekanism Ultimate Logistical Transporter (For 
 say true, but this is Mekanica (A new fork of Mekanism, more optimized) with the latest upgrade available at the this time, the 1.1.1)

I think I understand a bit why your Cable is soo laggy, if I compare to all other mods, your Cable transport about 1 item per Tick, and all other transport 1 stack at the time, each about 10 tick possibly. So, it caused a lot less refresh for a really higher transport rate!!

So, like you can see, Thermal Dynamics, EnderIO or Applied Energistics is just not register, because is less than 1 us/t, but the Item Extraction Cable have a value of 450us/t, and the rest of the pipe is at about 140 us/t with a place at 216 and the arrival at 185 us/t...

So, you can see with the screenshot of comparasion:
 ![Cyclic_compare](https://user-images.githubusercontent.com/19277301/54873744-b30d7880-4db3-11e9-89ef-46d7922b69eb.png)

I have try with the Universal Cable and if you  transfer item with it, this is the same than regular Item Cable from your mod.

Thank you very mutch again for your mod, you do a really good job!

**Comment by Fireztonez** [comment]
I just think about that, I forget the Item Transfer Node, set to send to a Storage Drawer again, with the same distance, the amount is at 270us/t, sometime it goes a more than 300us/t...

![cyclic_ietm_transfer_node](https://user-images.githubusercontent.com/19277301/54873922-557b2b00-4db7-11e9-98b2-a62a3e71c2b7.png)

**Comment by Lothrazar** [comment]
The lag is definately something i can look at.    And you made some good points in the tick rate.

Instead of moving 1 item per 1 tick, i could run every 20 ticks and try to move 20 items at a time, or some other similar ratio . and all see if theres any other code that could be updated

**Comment by Lothrazar** [comment]
How do you use lag goggles to give you those coloured previews in the world?

I ran it once for the 30 seconds , i think i clicked Player, but nothing showed up.


I ran it a second time and got a crash https://github.com/TerminatorNL/LagGoggles/issues/57

**Comment by Lothrazar** [comment]
@Fireztonez For real this mod doesnt even work what do i even do 
![nothing works](https://user-images.githubusercontent.com/621529/54967075-8f713c00-4f33-11e9-85bc-231c6f77ceb2.gif)

**Comment by Fireztonez** [comment]
This is strange because for me LagGoogle add the Color automatically and everithing work fine for me....

What version of Java are you using? I use personnally 1.8.0_201 64 bit, and start my modpack with MultiMC... After that I really can't help you because I never get any issue with that mod...

**Comment by Fireztonez** [comment]
you can see what I do exactly: https://www.twitch.tv/videos/400163249?t=01h27m49s

**Comment by Lothrazar** [comment]
Thanks for the video that helps a lot.  Helps me see your exact cable setup too.


Lag goggles helps but i did find cables being pretty slow, using something some other mod devs helped me out with.  TileEntityCableBase right at the top with 600MS which is half a second  
![target](https://user-images.githubusercontent.com/621529/55277917-ad87c500-52c2-11e9-9d37-58e07017fef6.PNG)

**Comment by Fireztonez** [comment]
Great, I'm really happy to have been able to help you, for the optimization of your mod! Other things I noticed that could be changed, to be able to optimize your cable;
I noticed that your cables and Item Item Extraction Cables contain items. Possibly using a similar way to EnderIO (Either simply making an instantaneous transfer from one inventory to another can be less cumbersome than moving one item after another).

Also, something that I noticed very often and who is to pay attention (during the profilings), it is when something is blocked (because the exit is full or does not accept a kind of item), the The amount of checks performed is often heavier (usually on most mods) than when the machines are running normally. So this is a point also paid special attention.

**Comment by Lothrazar** [comment]
Here is a test version if you can see if its any better https://github.com/Lothrazar/Cyclic/releases/tag/1.12.2-1.18.6-alpha0


" it is when something is blocked (because the exit is full or does not accept a kind of item), the The amount of checks performed is often heavier (usually on most mods) than when the machines are running normally. "

This is a good point, maybe we can think of a way to be less heavy when its blocked.    Maybe it can somehow remember if its blocked or at a dead end and then check less frequently.  Normally it checks every tick to keep the flow going, but if its blocked maybe it sleeps for a full second or something?

**Comment by Lothrazar** [comment]
see previous 1.18.6 commit.  added https://minecraft.curseforge.com/projects/sampler to issue template for future
