### ISSUE TITLE
Ender Wings sometimes don’t work

### ISSUE THREAD

**Issue by Dimentive** [Lothrazar/Cyclic#1094]
Sometimes, when using the Ender Wing or Ender Wing Prime, I am not teleported to spawn or my bed; rather, I am teleported to the same location I was already in, and the world loads really slowly (which is fixed by using F3 + A to reload the chunks).

Recently, the wings haven’t been working at all. I haven’t been able to teleport to spawn or my bed no matter how many times I use either Ender Wing. Additionally, when I try to use them and this bug occurs, they don’t use durability.

I am playing on a locally hosted multiplayer server with one other person. The Ender Wings have been working perfectly fine for my friend when he’s used his.

I’m not sure if this bug is the same as #559. That person didn’t mention not being able to teleport, only the chunks not rendering, although they have been experiencing the same bug.

I’m getting this in the console whenever I try to use an Ender Wing:
`[Server thread/WARN] [minecraft/NetHandlerPlayServer]: Dimentive moved wrongly!`

It looks like the server isn’t allowing me to teleport all of a sudden. I tried adding the mod [MTQFix](https://minecraft.curseforge.com/projects/mtqfix) to the server, which removes the server-side check for players moving too quickly, although it seems as though it doesn’t cover “move wrongly”; only “moved too quickly,” as the Ender Wings still didn’t work after adding this mod.

**Minecraft version:** 1.12.2
**Forge version:** 14.23.5.2781
**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version 1.62)
**Cyclic version:** 1.18.0

**Comment by Dimentive** [comment]
After being killed in-game for the first time in a while, my Ender Wings started working again. I’m not sure if being killed had something to do with it, but I tried the Wings earlier today, and they didn’t work, but now they do. Sometimes, they still fail and do as described (teleport me to the same location, render the chunks slowly, and not use durability), but it seems to work every time now, at least.

This is still a bug you’d probably want to look into, though.

**Comment by Lothrazar** [comment]
Was the chunk with your bed in it unloaded? And were there any logs or errors in the logs bout it? 

It should try to ping and load the chunk before moving you

**Comment by Dimentive** [comment]
The chunk with my bed was loaded.

I didn’t see any errors other than the aforementioned “Dimentive moved wrongly!”; however, I also forgot to check my _client_ log.

Now, the Ender wings always work for me. They haven’t not worked since my comment five days ago, after days of _never_ working. Weird.

**Comment by Dimentive** [comment]
Why was this closed?
