### ISSUE TITLE
Fan sound causing other sounds to cut off

### ISSUE THREAD

**Issue by Yamza** [Lothrazar/Cyclic#1095]
Minecraft Version: 1.12.2

Mod Version: 1.18.2

Single Player or Server: Single Player

Describe problem (what you were doing / what happened): 
Having too many fans running breaks game sounds. I believe the player was using 4 sets of 10 fans (40) and discovered that game sounds were not working properly as seen here: https://clips.twitch.tv/PricklyCreativeQuailPicoMause
Turning the fans off resolved the issue.

Log file (text block or link):
https://gist.github.com/generikb/cb6b0a77e806d85ace3d8db39ff6e9df
Don't think there's anything relevent in there other than sound system crashing

**Comment by Lothrazar** [comment]
Ill see if i can make a fix, but with so many sounds playing at once it might just be too much for the sound system. 

I can always add a silent mode button to the block as well
