### ISSUE TITLE
Config Confusion

### ISSUE THREAD

**Issue by lynaevm** [Lothrazar/Cyclic#1097]
Love that the configs are so extensive but it is often very hard to connect the name used for an item in the config with the name it is called ingame, or even tell if the config is referring to an item or a feature.   It would be great if the ingame name of items or a brief description could be added to the config in the cases where they are not obvious.

Examples: BucketBlocks (is this a block or an ability?), is Chaos Reaper and Chaos Siren the same thing?, is combat dynamite DynamiteSafe?,What does EnderWool refer to? I could go on.

**Comment by Lothrazar** [comment]
Yeah unfortunately i cant change the config keys since then old configs will break.

I know what i can do, i need to tag the Item ID onto the description so its clear and easy to find

**Comment by Lothrazar** [comment]
For example with the new changes it will have

`+        # wand_hypno Set false to delete - requires restart [default: true]
         B:ChaosSiren=true`
