### ISSUE TITLE
Structure Builder can caused intense lags, even in Single Payer... 

### ISSUE THREAD

**Issue by Fireztonez** [Lothrazar/Cyclic#1098]
Minecraft Version: 1.12.2

Mod Version: 1.18.5
Forge Version: 14.23.5.2823

Single Player or Server: Single Player... On Server, the server will crash for sure!

Describe problem (what you were doing / what happened): 
If you select a large region to build with the Structure Builder and preview, your FPS will probably fall to 1 or 2 or less (at least that's what happened to me!). And if you start the build, it will use a lot of server resources to do the work, enough pop to make the entire game lagger, although little is happening at the same time on the game !! Solo, my game is put to lag much time to place the blocks... I start a Lag Goggle during this time and you can see the result! I think this is something else you have to look question of optimization...

Video/images: 
![Guinnes_records_Cyclic_Builder](https://user-images.githubusercontent.com/19277301/55267958-1ab43f80-525c-11e9-9279-532668b9c3c0.png)
![structural_builder_cyclic](https://user-images.githubusercontent.com/19277301/55267960-1ee05d00-525c-11e9-9424-44f39a8d5548.png)

PS: I think, adding Forge Version to your Issue Template should be a good idea... Sometime the version of Forge can make a big difference for somes issues!!

**Comment by Lothrazar** [comment]
Ok so.  Either lag goggles doesnt work. or im using it wrong. or i get zero lag on my computer.  

I really want to fix it but if i cant test it i don't even know what to start.


Am i doing this right
![lagwat](https://user-images.githubusercontent.com/621529/55271424-b7c9a500-5269-11e9-88bf-9862b6da5caa.gif)

**Comment by Lothrazar** [comment]
5 seconds in the gif but the same thing happens if i do 30

**Comment by Lothrazar** [comment]
found another lag profiler. may take some time but work is in progress https://visualvm.github.io/

**Comment by Fireztonez** [comment]
I really don't understand why your LagGoggle doesn't work. Like I say, I do exactly what you do, and it show the result after 1 or 2 second in the world habitually, after the end of the profiling... I just try in a fresh pack with only 2 mods install Cyclic and LagGoogle, and LogGoogle still work for me...

Like I say in the other issue, I don't know your version of java and everything, but, it should work, if not, this is possibly a LagGoggles issue with your configuration, I really can't say anything more about that... You can possibly try on a server, I ear people saying LagGoggles works sometime better on a server than Single Player...

But question of Profiling and get the more information about where your should work question of optimization, I think you should try with JProfiler or something Similar ...

I know you can setup JProfiler and JVisualVM directly on MultiMC question of be able to run Good profiling and see exactly what's happen, what packets take so much juice or make so much refresh or thing like that... I have try my self with that tool, this is really powerful, but, I'm not Java Programmer, so I don't really know where I need to look up and everything... I have still a lot of thing to learn I think ;). But, with that you can probably get a lot of information!!

For say true, when I do that profiling today I have a lot of thing running in my computer, with 2 instances of my modpack, so this is possibly why I get so much lags, but, the rest of profiling in the world for cables, pipes and everything is pretty similar to what it is normally... 

I have try back the preview in my fresh modpack, and it still lagging a lot if you select Solid with the bigger size possible... But strange enough, I cant get bigger than 64, when in my other modpack I have select 122, like you can say in the screenshot... Again, for preview, you an possibly take inspiration from other mods Like EnderIO, Industrial Foregoing or other mods like that... I never get any lags when I press to show the preview... (The big difference I saw, you show a lot of small transparent cube, when most mods show all the area like a big cube, so this is a lot less graphic information to process, and it look a lot more cleaner I think)...

If it can help you to do things, with better optimization, you can probably look about EnderIO Conduit, Thermal Dynamics Pipes and everything.. Both is really really good optimized... Or you can possibly talk to Mekanica Dev, how work now to optimized all the pipes from Mekanism... I can say, this is really really nice Dev and you can possibly ask somes question on discord to get somes good tricks!! And for the Structure Builder, you can for sure, look the Builder from RFTools... All that mods is open sources and Sources code is directly available in GitHub...

If you need help, if you have questions or want to talk a little more, you can come to see me in my discord. As I say, I really appreciate Cyclic so if I can help you have a better mod, more optimized and powerful, it would be great! 
https://discord.gg/AJSJuv

Anyways, now I really have to go sleep, after the end of that roman!!
Fireztonez

**Comment by Lothrazar** [comment]
Thanks for all the details.   Ill install RF tools and do a comparison.

So far i just have a very simple test, i told it to build a talls hame and had miners mine out the blocks so its always building.

So far is good (4 milliseconds) but ill keep digging
![controlled miner](https://user-images.githubusercontent.com/621529/55279890-7d005500-52db-11e9-9a4b-1ca75633963c.PNG)

**Comment by Lothrazar** [comment]
This was resolved in 1.18.6 as seen in previous commits.

Added sampler mod to issue template for future lag issues https://minecraft.curseforge.com/projects/sampler
