### ISSUE TITLE
Sack of holding breaks Immersive Engineering’s garden cloche

### ISSUE THREAD

**Issue by Dimentive** [Lothrazar/Cyclic#1099]
I used the sack of holding on the [garden cloche](https://ftb.gamepedia.com/Garden_Cloche) from Immersive Engineering, and when I placed it, it created an invisible one block-tall block. Breaking it and re-placing it gave me my cloche back but removed all its data (energy, items, water, and fertilizer), defeating the purpose of using the sack of holding in the first place. I still had multiple invisible one block-tall garden cloches placed by the sack of holding that I had not broken and re-placed yet, and when I logged out of the server and logged back in, they were just gone completely; I did not have them in my inventory.

**Minecraft version:** 1.12.2
**Forge version:** 14.23.5.2781
**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version 1.63a)
**Cyclic version:** 1.18.4

**Comment by Lothrazar** [comment]
There is a blacklist for this item, so we will have to add it here. I dont think i can get a multiblock like this to work


    # Containers that cannot be lifted up with the Empty Sack of Holding.  Use block id; for example minecraft:chest [default: [extracells:fluidcrafter], [extracells:ecbaseblock], [extracells:fluidfiller], [refinedstorage:disk_drive], [parabox:parabox]]
    S:SackHoldingBlacklist <
...

**Comment by Lothrazar** [comment]
Whats the item ID tag i can add it to the default

**Comment by Dimentive** [comment]
My apologies for the late reply. The ID for the garden cloche is `immersivengineering:metal_device1`.

**Comment by Dimentive** [comment]
My apologies for the late reply. The item ID for the garden cloche is `immersivengineering:metal_device1`.
