### ISSUE TITLE
[Suggestion] Config option to disable magic beans as loot

### ISSUE THREAD

**Issue by Dimentive** [Lothrazar/Cyclic#1101]
Could you please add a config option that makes it so that magic beans cannot be found as loot (dungeon chests, blacksmiths, etc.); only crafted?

That would be fantastic.
I love the mod, by the way! 👍

**Comment by Lothrazar** [comment]
Releasing a fix soon, with that the error is gone with multiple items


Hydrator.removeShapedRecipe(<minecraft:grass>);
Hydrator.removeShapedRecipe(<minecraft:grass_path>);
Hydrator.removeShapedRecipe(<minecraft:clay_ball>);
Hydrator.removeShapedRecipe(<minecraft:concrete>);

**Comment by Dimentive** [comment]
I think you meant to post that comment on #1100.

**Comment by Lothrazar** [comment]
haha oops

**Comment by Lothrazar** [comment]
So i do have this feature, but its not item-per-item.  With the following, all cyclic items will be removed from all chest loot tables. including this and other stuff




    "world generation" {
        # If true, then enabled items and blocks from this mod can appear in loot chests [default: true]
        B:ChestLoot=true



For finer grain control you will have to get one of the LootTableTweaker mods

**Comment by Dimentive** [comment]
I don’t want to disable every Cyclic item as loot. I’ve never used a loot table tweaker mod before.
It’d be pretty neat if there could be a config option that just disables magic beans as loot, but I understand if you won’t add it. If you won’t, I’ll look into a loot table tweaker.
