### ISSUE TITLE
Fluid Storage tanks not retaining storage

### ISSUE THREAD

**Issue by onlybentley** [Lothrazar/Cyclic#1104]
Minecraft Version: 
1.12.2
Forge Version: 
2831
Mod Version: 
1.19.0
Single Player or Server:
Single Player
Describe problem (what you were doing / what happened):
Breaking the Fluid storage tank with Stone pickaxe, diamond pickaxe or paxel from pickle tweaks empties tank full of lava, water or any fluid I've tested.

Log file (text block or link):
N/A

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment]
1.19.2 https://minecraft.curseforge.com/projects/cyclic/files/2698577

**Comment by Immortalin** [comment]
@Lothrazar regression happening again on 1.16 with Tetra pickaxes.

**Comment by trunksbomb** [comment]
Probably better to open a new issue and tag this one as related since this issue is old and for a different version.
