### ISSUE TITLE
Crash and world corruption caused by Entity Detector

### ISSUE THREAD

**Issue by Brettflan** [Lothrazar/Cyclic#1107]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2822

Mod Version: 1.18.5

Single Player or Server: singleplayer

Describe problem (what you were doing / what happened):

I tried and was able to replicate this, so it should hopefully be easy enough. I am using the "Dungeons, Dragons and Space Shuttles" modpack version 4.9.

1. Place a door. I've tested a vanilla Acacia Door, and an Iron Glass Door (from Malisis).
2. Place an Entity Detector (from Cyclic) on top of it.
3. Right-click the Entity Detector, and lower the "Count before trigger" on the right side to 0.

The game immediately crashes with an NPE, linked below.
Attempting to load back into that world will result immediately in the same crash. I was able to use MCEdit to remove the tile entity from the Entity Detector block so that I could safely access that world again.

Log file (text block or link):
https://paste.dimdev.org/xozekezaxo.mccrash

EDIT:
Replaced log file link above, was pointing to crash log for Malisis door, switched to crash log with vanilla acacia door.
And as I see Malisis is still indicated in the stack trace, it may actually be the main culprit.

**Comment by Brettflan** [comment]
OK, I just tested removing Malisis Doors and Malisis Doors and tried again. Got a crash again:
https://paste.dimdev.org/metiwevofu.mccrash

So it does appear to be Cyclic specifically, not Malisis.

**Comment by Lothrazar** [comment]
Thanks for the second follow up post

**Comment by Lothrazar** [comment]
patched in https://minecraft.curseforge.com/projects/cyclic/files/2700679
