### ISSUE TITLE
[1.12.2] Model oddity with the Spikes.

### ISSUE THREAD

**Issue by Z-Tunic** [Lothrazar/Cyclic#1108]
Minecraft: 1.12.2
Forge: 14.23.5.2824

Mods: 2
Cyclic-1.12.2-1.19.4

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/568334544932044802/cyclicspikemodelbug.PNG)
I noticed that the modeling for the spikes tends to kinda bug out in a way, the odd thing with this is that the model sorta fixes but something else on it breaks. Like in this image the spikes are powered and I can see the holes & panel leaking through the spikes.

![](https://cdn.discordapp.com/attachments/377171551155650560/568334567707115550/cyclicspikemodelbugwithdeathmessage.PNG)
Another shot at a different angle with the Diamond Spikes... also a odd death message related to the diamond spikes.

**Comment by Lothrazar** [comment]
Ill be honest this isnt getting fixed. model was made by a pullrequest not by me, for one thing.  and looks completely normal in blockbench. so if its not caused by forge or vanilla i have no idea what to change. Thanks for the very good report, im glad we looked into it anyway
