### ISSUE TITLE
Pipes have no wrench

### ISSUE THREAD

**Issue by LukeIreland1** [Lothrazar/Cyclic#1110]
Minecraft Version: 

Forge Version: 

Mod Version: 

Single Player or Server:

Describe problem (what you were doing / what happened):

Log file (text block or link):

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment]
You can use a redstone torch to break any connection or block connection from any side of the pipe, after this you will see a YELLOW square on the cable.

If there is something else you need a wrench to do let me know

**Comment by LukeIreland1** [comment]
Okay, thank you, I couldn't find this anywhere. It may be worth adding to the pipe info in-game.
