### ISSUE TITLE
Fluid Placer Tick Crash

### ISSUE THREAD

**Issue by lildale03** [Lothrazar/Cyclic#1111]
Minecraft Version: 1.12.2

Forge Version:  14.23.5.2831

Mod Version: 1.0.6

Single Player or Server: Single Player

Describe problem (what you were doing / what happened):
Made an Obsidian Generator in SkyFactory 4. Have Lava Infused Stone, a Block Breaker, and a Fluid Placer, powered by a Redstone Clock to only place liquid in set time.

Log file (text block or link):
https://github.com/lildale03/Uploads/blob/master/Cyclic%20Crash%20Report

Video/images: N/A, continuous Crashing

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2701943
