### ISSUE TITLE
Crash with ticking block with Hydrator

### ISSUE THREAD

**Issue by JackRuby1** [Lothrazar/Cyclic#1112]
Minecraft Version: 1.12.2

Forge Version: 2831

Mod Version: Cyclic-1.12.2-1.19.4.jar

Single Player or Server: Server

Describe problem (what you were doing / what happened):
I was building a IF laser drill, then I crashed with the report below. I was like 90 blocks away with the Hydrator not even working on a recipe

Log file (text block or link):
https://pastebin.com/iqghnkQq

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by Lothrazar** [comment]
"Hydrator not even working on a recipe" Thanks for the report and all the details.

Having trouble replicating.  Was there anything piping water in or out of hydrator?  Even without ar ecipe did it have any items inside?

It doesnt do anything directly with NBT  and i cant replicate this, even loading/unloading chunks etc

**Comment by JackRuby1** [comment]
It was sitting idle, with I believe the recipe for a lilypad in it; grass, vines, seeds. That's the last time I used it. There was no water connected to it, but water inside of it, and the only pipe connected to it was a leadstone fluxduct from thermal

**Comment by Lothrazar** [comment]
I rewrote some stuff anyway in last few builds, and had it idling for a while as well.   Might happen again but log should different if it does anyway. so ill close for now https://minecraft.curseforge.com/projects/cyclic/files/2704643
