### ISSUE TITLE
Energy Draining

### ISSUE THREAD

**Issue by mc17336** [Lothrazar/Cyclic#1113]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: Cyclic-1.12.2-1.19.3.jar

Single Player or Server: Single Player

Describe problem (what you were doing / what happened):
If this is an intended part of the mod I apologise in advance. I've been playing SkyFactory4 and have just started using cyclic energy cables. I was getting an issue where one of the packagers I was connecting to the cables waste getting any energy so I was trying to fix this. While doing this, I disconnected all machines from my network and just had cables connected to a Basic energy cube that was full. Although nothing was connected to the cables, all the energy drained out of the full energy cube as soon as I placed it within a few seconds. I have no idea where its gone (and although it says in the book each cable stores a small amount of energy, my cable network isn't that big and I've replaced with full energy cubes to test and they keep getting drained). The photo below is the disconnected network of cables.

Photos:
![2019-04-19_11 38 29](https://user-images.githubusercontent.com/49783160/56420881-c66b1100-6297-11e9-92c5-d4fb607f449c.png)

**Comment by Lothrazar** [comment]
You can right click cable with an empty hand to see the quantity in the cable. A little text message will pop in.


What might be happening is that a cable in a dead end soaks up a ton of power instead of sending it back so ill have to do some tests.

**Comment by mc17336** [comment]
![2019-04-19_18 31 06](https://user-images.githubusercontent.com/49783160/56435733-73ae4b00-62d1-11e9-93d0-fcbc3f6b5aa0.png)
![2019-04-19_18 31 29](https://user-images.githubusercontent.com/49783160/56435734-7446e180-62d1-11e9-8393-fcb391d4812e.png)
![2019-04-19_18 31 30](https://user-images.githubusercontent.com/49783160/56435735-7446e180-62d1-11e9-8ac0-d525a7f88a85.png)
![2019-04-19_18 31 31](https://user-images.githubusercontent.com/49783160/56435736-7446e180-62d1-11e9-9325-d11eba4fb734.png)
Had a quick look - looks like there's a lot of energy just bouncing around in the cables back and forth trying to find somewhere to go?

**Comment by Lothrazar** [comment]
thanks for the update

**Comment by Lothrazar** [comment]
Forgot to update this with the fix, but in existing versions each cable block maxes out at 64k, instead of near infinite so it wont bunch up at the end node .
