### ISSUE TITLE
disabling health system 

### ISSUE THREAD

**Issue by Varg95** [Lothrazar/Cyclic#1115]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2796
Mod Version: 
Cyclic-1.12.2-1.19.4
Single Player or Server:
single player
Describe problem (what you were doing / what happened):
i would like to completly disable the hearth containers and limitation of amount of hearts cuz this is incompatible with minestrappolation system.  

Log file (text block or link):

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

thanks for yout time :)

**Comment by Lothrazar** [comment]
You can disable already with the HeartFood config, already in .

"incompatible with minestrappolation " , thats can be looked at, it works with various other systems.   incompatible  how and in what way? what version of minestrappolation

**Comment by Varg95** [comment]
yeah i tried disabling the heartfood item but that didn't fix my problem. 

if your mod is installed, i always start with 20 life. eventhough i changed it in your config. I cant get it to go higher with the heartfood item or the item from minstrappolation. When i remove your mod it works as it needs. i find that too bad cuz the other features in your mod really appeal to me. 
I used the  5.6.5 version of minestrappolation. 

I hope this is enough info. if not i could try to provide more.

**Comment by Lothrazar** [comment]
Resolved by https://github.com/Lothrazar/Cyclic/pull/1264 . it now stores a modifier instead of editing raw values.

More compatible this way, and if all health items and commands are changed the modifier is zero and not used
