### ISSUE TITLE
Request  [title edit: flowing water breaks cables/pipes]

### ISSUE THREAD

**Issue by Adam022695** [Lothrazar/Cyclic#1116]
Minecraft Version: 1.12

Forge Version: forge-14.23.5.2831

Mod Version: Skyfactory 4.0.2

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):

Currently flowing water causes pipes to break. Is that something we can look into making not happen?

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
Looks like this was a bug that was introduced recently.

Cables used to be material = LEAVES, which was useful except there was a bug where some other mod made them drop sticks.

I changed that to material = CIRCUITS. which fixed above, but now they act like redstone and break on water.

**Comment by Lothrazar** [comment]
:) https://minecraft.curseforge.com/projects/cyclic/files/2701943
