### ISSUE TITLE
Crafter can possibly caused Server lags

### ISSUE THREAD

**Issue by Fireztonez** [Lothrazar/Cyclic#1117]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2824

Mod Version: 1.9.5

Single Player or Server: Single Player World

Describe problem (what you were doing; what happened; what should have happened):
I just make somes test on my World to see if somes things can caused lags in server, and I saw the Auto-Crafter from Cyclic, with a Tick-rate of 687 uS/T... This is clearly a lot, and the machine doesn't do anything, because there ahve just no items for crafting the stuff...

Video/images/gifs (direct upload or link): 
![cyclic_crafter_lag_687](https://user-images.githubusercontent.com/19277301/56468167-4c9d6980-63f6-11e9-8382-5cfddd2c4a61.png)
![Cyclic_auto_crafter](https://user-images.githubusercontent.com/19277301/56468318-ccc4ce80-63f8-11e9-8126-9840cf33fedb.png)
![Cyclic_autocrafter-cable_lags687-939](https://user-images.githubusercontent.com/19277301/56468209-c7668480-63f6-11e9-9815-15181cd7c240.png)
![Cyclic_auto-crafter_lag_entitie687](https://user-images.githubusercontent.com/19277301/56468210-c7ff1b00-63f6-11e9-9e6d-089f527a7174.png)

And like you can see, the Cyclic Item Cable is still pretty bad in my world, with the newest version (1.19.5).

Version: 
Cyclic 1.19.5
Forge: 14.23.5.2824
Java: 1.8.0_201

If needed, I can possibly make somes profiling with sampler, if it can help you to find what caused that really high timing...

**Comment by Dimentive** [comment]
LagGoggles isn’t always to be trusted.

If your tick time and TPS (which you can check with the `/forge tps` command) are fine (i.e., a tick time of 50 ms or below and a TPS of 17–20, preferably 20), there’s nothing to worry about.

**Comment by Dimentive** [comment]
[LagGoggles](https://minecraft.curseforge.com/projects/laggoggles) profiles aren’t always to be trusted. It can often result in false positives.

If your tick time and TPS (which you can check with the `/forge tps` command) are fine (i.e., a tick time of 50 ms or below and a TPS of 17–20, preferably 20), there’s nothing to worry about.

**Comment by Fireztonez** [comment]
I know, LagGoggle is not perfect, but this is the best way I found for now, to look if something can caused somes lag on server. I make that profiling in single player, on a flat world I used for development. My tps is good in that world and when I play solo, but,    I just want to ask to take a look if the crafter can be optimized. If I compare a crafter showing about 700 vs one with the same used with about 10 or 20, there have possibly something to look at... I hope you understand my point.

I just want to help the dev to get a mod more optimized for server, because the modpack I made is made specially for run on a server.

If you have better solution than LagGoggle how I can find easily the machine or thing who take the more resources, let me know

**Comment by Fireztonez** [comment]
Ok, this time this is clearly the whorst number I never saw (Don't take it bad, I just say this because yeah, the number is really soo high, for nothing)... I have other things running, but nothing crazy nd the auto-crafter is still innactive, but have an incomplete recipe in the table and nothing in the input, and it now jump to 46 316 us/t...

![AutoCrafter_innactive_with_incompleterecipe](https://user-images.githubusercontent.com/19277301/56631801-cfa40700-6624-11e9-854f-71a69826479c.png)

![image](https://user-images.githubusercontent.com/19277301/56631763-aaaf9400-6624-11e9-96ad-fc070388d95a.png)

Still, my TPS is good, but, with number like that, i really don't whant to see that in my server, for sure with lot of thing goin on and multiple person playing at the same time, the server risk to lag... And I'm pretty sure a lot of person risk to let autocrafter like that one time or the other...

I have autocrafter from Mekanism and EnderIO in the same area, with similar setup and both is at less than 10 us/t, just for comparaison...

**Comment by Dimentive** [comment]
I don’t think this is anything to worry about. I have plenty of tile entities and entities with a high number around my base when profiling my world with LagGoggles, and my TPS is almost always 20, with a low tick time.

Unless you have a TPS of below 20, it’s impossible for you to experience server lag. However, if Lothrazar wants to optimize the auto-crafter (if it has to be optimized in the first place), that’s, of course, great.

**Comment by Fireztonez** [comment]
> I don’t think this is anything to worry about. I have plenty of tile entities and entities with a high number around my base when profiling my world with LagGoggles, and my TPS is almost always 20, with a low tick time.
> 
> Unless you have a TPS of below 20, it’s impossible for you to experience server lag. However, if Lothrazar wants to optimize the auto-crafter (if it has to be optimized in the first place), that’s, of course, great.

I can understand what you say, but I think you don't understand what I mean, LagGoogle still show what it take the most resource (Yes, sometime it can possibly be a little off, but in most case, it is a pretty good indicator), and when I saw an Auto-Crafter how do absolutely nothing (Bit is still on, but I think most people will probably never turn off...) and it show 50 000 us/t (yes, teh number is now at 50 000 in my last profile..), vs one at 5, sorry but I think something should be optimized on the one at 50 000... Do you think optimizing the mod is a bad thing?

The only thing I do here is to points what should probably look at question of optimisation, because, on a server with multiples players, and with a lot of thing running, I can garantee you, thing's like that matter... And, I experience that my self in my modpack when running on a server with like 7+ players, sometimes, I alreadu saw my server dropping at less than 10 TPS... I hate when people came and tell me I'm wrong because I point-out something. And, I think optimizing Cyclic is a really good thing, when I saw SkyFactpry 4 where Cyclic is one of the more used mod in the game for a lot of person, and when I saw multiple times streamers having big TPS issue in is server (Do you think all those streamer have really bad server??). So yeah, number like that matter if you have like 50 Auto-Crafter in the world (And I garantee you, 50 is clearly not a big number!!)

I don't say the TPS issue on SkyFactory 4 servers is all caused by Cyclic, but if you calcul a 50 000 there, plus a 15 000 for Simple Storage Network by example, for all cables and stuffs, plus Cyclic Items Pipe how is clearly not really optimized for server (I say that, the number is twice the number of what Mekanism Logistical Transporter have before, and a lot of person say on inetrnet, those pipe is bad for server, it caused lags, and this is totally true, the mod dev confirm, but his is a lot lot better now!).

All small number care on big modded server and big number can be really bad... For now I have remove the Auto-Crafter from the next beta update for my modpack, I really hope I can re-enable before the Final-Release!!

Sorry Lothrazar, don't want to pollute your issue tracker with discussion like that

**Comment by Lothrazar** [comment]
Heres the thing with that incomplete recipe; looks like the durability of the crystal wore out and now its incomplete.  But its still turned on, and it still has items inside of it.  So the machine is still processing as its been told to.  its turned on by the upper right button, so it has to do all the things such as validating its recipe, seeing its not valid, searching for a new recipe.  

when it finds the valid recipe, all it does is look in the two left columns to find the price.

If this was turned off with redstone, or empited out then it would not be working in the empty case.  I will concede other crafters may be more efficient   , but i dont see what to change here right now

Hopefully if you are all still playing the map a new sample can be made https://minecraft.curseforge.com/projects/sampler

Also i added that sampler mod link to new issues

**Comment by ktole1999** [comment]
can you test this in an actual server environment rather than ssp? you can get skewed numbers from ssp.

**Comment by Yamza** [comment]
This is pretty easily reproducible in SSP. Cyclic-1.12.2-1.19.12
Here is a spark report with this running on a server hosting ATM3 - Remix 1.3.2 https://sparkprofiler.github.io/#ygYsvbJOvh

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
