### ISSUE TITLE
Uncrafting Grinder : Recipe not found

### ISSUE THREAD

**Issue by LeQwouincy** [Lothrazar/Cyclic#1118]
Minecraft Version: 
1.12.2

Forge Version: 
14.23.5.2836 and 14.23.5.2768

Mod Version: 
1.19.5

Single Player or Server: Single player world

Describe problem (what you were doing; what happened; what should have happened):

Some of the Cyclic's items can't be uncrafted:
cyclic buildng scepter, ender book

And some if they haven't been use before(activate, desactivate, repaired):
Charms, climbing gloves, scepters

Looks like the uncrafting grinder can't find the recipes in thoses case.

Video/images/gifs (direct upload or link): 
![2019-04-21_13 31 25](https://user-images.githubusercontent.com/49834383/56469420-e9cdc180-6439-11e9-8948-76ad5b7f5d89.png)

**Comment by LeQwouincy** [comment]
Also unchanted item can't be uncrafted

**Comment by LeQwouincy** [comment]
Seems like it's due to the NBT tags, if it's present it won't work.
(unchanted items have a NBT tag = 0 and simple item don't have NBT tags)

**Comment by Lothrazar** [comment]
Yeah NBT is a tricky subject.

Some mods add NBT to an item, and it stays the same item regardless of what the NBT is.

Other mods use NBT to make completely different items.  

For example, theres a big tech mod i forget which one (maybe thermal or mekanism i forget) Where every machine has the same block id. same metadata damage, teh only difference between two machines is the NBT.  

Also , resource hogs.  each truffle or whatever has the same item id, same item meta damage, but only NBT is the only way to differ between diamond truffle and coal truffle https://minecraft.curseforge.com/projects/resource-hogs

So having it exactly match NBT is the safest way.

**Comment by Lothrazar** [comment]
I think the only way to deal with this is to have yet another config list.  Maybe if i do something like

` listOfItemsToIgnoreNBT = [
diamond_pickaxe
that_building scepter in your screenshot


] `

So by default it does exact match on NBT, but there are some items where its safe to ignore

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports.
