### ISSUE TITLE
Dehydrator crash

### ISSUE THREAD

**Issue by JackRuby1** [Lothrazar/Cyclic#1120]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: 1.12.2-1.19.6.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
I was dehydrating black concrete into concrete powder when I crashed, I believe it was done crafting and sitting idle when it crashed me, I was AFK.
My set up:
I have a Dehydrator connecting to power via a flux point on the back side of it, the front has a Thermal itemduct with items coming from a max sized compact chest, the right side has a Cyclic liquid extraction pipe into a black hole tank from Industrial Forging. The items are exiting out the top via a Thermal itemduct into a AE2 interface, the bottoms and the left side are empty of inputs.

I hope this is enough info, let me know if you need more details!

Log file link: https://pastebin.com/6L4eDM0q

Video/images/gifs (direct upload or link): 
A picture of it: https://i.imgur.com/JCN4E0Q.png

**Comment by Lothrazar** [comment]
Seems like whats happening is when the tank is empty its inserting water but somehow the fluid becomes null.  Even though when the fluid is null it should just replace.  Made a similar setup without replicating but from the log i can see a few places to check for that case i think

**Comment by Lothrazar** [comment]
so it crashed just the client not whole server it sounds like?

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2704643
