### ISSUE TITLE
Uncrafter doesn't accept power properly.

### ISSUE THREAD

**Issue by Darkhax** [Lothrazar/Cyclic#1121]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2831
Mod Version: 1.19.3
Single Player or Server: Server

I have an uncrafting Grinder that is powered by a Simple Combustion Generator. The Uncrafting Grinder is set to "Always On". It is consuming the power from the generator, however the progress and internal power buffer of the uncrafting are not shown. If I set it to "Requires Redstone" and then set it back to "Always On" it will update it's progress relative to the time it was in "Requires Redstone". 

Gif: [here](https://cdn.discordapp.com/attachments/333315894417817602/570123993307283459/uncrafting.gif)

**Comment by Lothrazar** [comment]
There might be a few issues here. but yeah seems like the clientside energy bar stops updating whenever redstone is off, even though the power is actually there

**Comment by Lothrazar** [comment]
the jump in action 
![the jump](https://user-images.githubusercontent.com/621529/56852525-5a109300-68d1-11e9-9213-5542759bdf0a.gif)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
