### ISSUE TITLE
Cannot repair AE2 items in the magma anvil

### ISSUE THREAD

**Issue by Dimentive** [Lothrazar/Cyclic#1122]
I cannot repair the Nether quartz cutting knife or the certus quartz cutting knife from [Applied Energistics 2](https://minecraft.curseforge.com/projects/applied-energistics-2) in the magma anvil. (I haven’t tested with the powered diamond anvil.)

#### Versions

**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.65a](https://minecraft.curseforge.com/projects/enigmatica2/files/2700051), latest)
**Minecraft version:** 1.12.2
**Forge version:** 14.23.5.2781
**Cyclic version:** [1.19.2](https://minecraft.curseforge.com/projects/cyclic/files/2698577)

**Comment by Lothrazar** [comment]
This is just the way AE2 is. non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle

**Comment by Dimentive** [comment]
Well, that took a while.
