### ISSUE TITLE
Trash Void - Feature request

### ISSUE THREAD

**Issue by MacAttack-UK** [Lothrazar/Cyclic#1123]
Minecraft Version: 1.12.2

Forge Version: 1.12.2-14.23.5.2831

Mod Version: Cyclic-1.12.2-1.19.4

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Using Thermal Expansions Itemducts to send items to the Trash void causes back stuffing.

Log file link: None

Would it be possible to tie into Termals API to prevent item oversending?

**Comment by ReillyBrogan** [comment]
Yeah this is something I encountered as well. It seems like the trash void only exposes so many empty item slots at once which causes the backstuffing issue. The solution is likely to make it so that the trash void exposes either an unlimited number of slots or a huge number of them.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2705255
