### ISSUE TITLE
Solidifier ignores fluid type in recipes

### ISSUE THREAD

**Issue by jollki** [Lothrazar/Cyclic#1124]
**Minecraft Version:** 1.12.2
**Forge Version:** 14.23.5.2795
**Mod Version:** 1.19.6
**Single Player or Server:** Single Player

**Describe problem (what you were doing; what happened; what should have happened):**

The solidifier ignores the type of the input liquid, and can use any liquid in any recipe. Only the item inputs matter.

for example:
-any liquid in tank + 4 sticks in item input will output obsidian.
-any liquid + bucket will give a bucket of milk.
-any liquid + iron nugget = crystallized obsidian.
etc.

**Comment by Lothrazar** [comment]
yeah stick + lava should not make ice for sure

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2704643
