### ISSUE TITLE
All Cables only hold a single item type and not multiple channels (old title:Packager not accepting more of the same item when input slots are full)

### ISSUE THREAD

**Issue by MacAttack-UK** [Lothrazar/Cyclic#1125]
Minecraft Version: 1.12.2

Forge Version: forge-1.12.2-14.23.5.2831

Mod Version: Cyclic-1.12.2-1.19.6

Single Player or Server: MP (Not tested on SP)

Describe problem (what you were doing; what happened; what should have happened):

Skyfactory 4 (v4.0.2)

When the input slots are full of part stacks of truffles it will not accept more of the same type of truffle unless you empty a slot then it springs back into life and accepts more to package up.

It should be able to add more of the same to package it up.

Log file link: None

Video/images/gifs (direct upload or link): 

![Cyclic - Packager](https://user-images.githubusercontent.com/13574886/56740903-b9ec2a00-6769-11e9-9949-5e1f87b17a55.png)

![Cyclic - Item Collector](https://user-images.githubusercontent.com/13574886/56740930-cb353680-6769-11e9-9af0-9b125d6743c4.png)

![Cyclic - Item Cables](https://user-images.githubusercontent.com/13574886/56740938-cf615400-6769-11e9-9fbd-48ca2f9cc7b0.png)

**Comment by MacAttack-UK** [comment]
After further testing it seems that the cables are the issue not the packager. I used another mods ducts and it solves the issue. I would guess the cables have some kind of buffer so it's unable to send new items until it's able to empty the current.

**Comment by Lothrazar** [comment]
maybe its the cable buffer then, getting blocked 
 i tried to replciate this without the collector or the pipes and , if its just a hopper it seems ok


![packager confusion only cables ](https://user-images.githubusercontent.com/621529/56859262-10f62880-693d-11e9-9fa8-0fd9ec71372c.gif)

**Comment by MacAttack-UK** [comment]
Yeah I can also confirm that the fluid pipes also suffer from the 'buffer' problem. If they had no buffering or were able to check if the target inventory was able to accept an item/fluid before loading it into the pipe they would be very powerful indeed as they are very fast. This together with the bundled version and if covers/facades became an option that could be made to look like any block maybe with conected textures would be awesome and very very useful.

Also additions for Gasses and Redstone (with multi channels) and some kind of filtering & black/white lists on the target would make them a serious contender IMO but I realise there may be a large amount of work involved so just something to consider moving forward.

Lastly, thank you for your hard work so far and good look with the mod, as a whole I'm finding a lot of the blocks very useful in SF4 :)

**Comment by Lothrazar** [comment]
The cables do have a buffer. So for example if the cables are full of iron ingots, and then gold ingots start to come in, they cant flow because theres an iron ingot blocking the path.

Each cable is like a chest with exactly one slot.

Whcih , yeah i think i will update to have more channels, maybe at least 6 one for each direction. but thats a big undertaking :)

**Comment by Lothrazar** [comment]
For now cables only hold one type of item.  1.14 wiill be a total rewrite so ill keep that in mind for the future
