### ISSUE TITLE
feature: GPS and ndes now use EnumFacing :: Energy Transfer Nodes not working with Energized Smelter / Crusher

### ISSUE THREAD

**Issue by n0ven** [Lothrazar/Cyclic#1126]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: 1.12.2-1.19.6

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
Using the Energy Transfer nodes and gps, does not input energy into machine type blocks, ie energized smelter or crusher, etc. Sorry if this has been brought up already or maybe I am not sure how to used it. But the Simulation Chamber from Deep Mob Farm does get RF. Thank you for checking into this.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by LezChap** [comment]
https://github.com/mekanism/Mekanism/issues/5433 Mekanism is saying this is Cyclic's fault for using a null facing...maybe modify the GUI with a button above every GPS marker allowing one to cycle through the facing directions?

**Comment by n0ven** [comment]
No dice I think. I placed a button over the machine, shift right clicked the gps and still nada.

**Comment by LezChap** [comment]
I was giving the developer a suggestion to code in a fix...not something that's going to work in-game right now.

**Comment by Lothrazar** [comment]
NULL is valid, and many machines accept it. The system was designed so this is valid.  Mekanism chose to ignore null direction connections, and it could be updated to allow this if they desired.

Regardless.

I guess instead of NULL i can pick a random of the 6 locations every time

**Comment by LezChap** [comment]
I agree...Personally I feel Mek is being snitty elitists about their "strongly sided" ideology while excluding "null" or "internal" as a "side"...but they're refusing to change. :(  Their adherence to such principles appears to have broken compatibility with several mods...I've seen complaints about Flux Network Points not connecting either.  Unfortunately they may be big enough to force a sided compliance into most smaller mods and create a new defacto standard that's not actually part of Forge, but might as well be. :(

**Comment by LezChap** [comment]
As for your proposed fix, that's be the quick and easy implementation that would take 2 seconds and fix the immediate issue...long term could I request something like this be added to the GUI: 
![GUI](https://imgur.com/yag1T15.jpg)

So: N = North, S = South...and I = Internal or null.

That way you can configure each GPS connection of each type of node insert into a given side...and in the end, would make your nodes compatible with just about anything that implements the appropriate Forge Capabilities, even if they want to be snitty about being "strictly sided" or, like AE2's Inscribers or Vanilla Furnaces which iirc are very side-dependent for which slot inputs end up in.

**Comment by uTired2** [comment]
Rather than assigning a random side, would it be possible to just assign it to the side of the machine you click the GPS onto? This may add extra work for yourself, but would be a lot more intuitive for users as using random sides means having to go into the config for machines such as Mekanism and try every single side until you find the one that the power is being fed into, it might also cause issues for some machines that may only allow power to be fed into certain sides (not that I can think of one that isn't configurable, but who knows).

**Comment by Lothrazar** [comment]
I like the idea of Sided inserts and exports.  Simple Storage Network does something similar with its Processing cable.

Even for vanilla blocks like Furnaces the side you use matters

**Comment by Lothrazar** [comment]
Going with the GPS data location instead of buttons 
![1126](https://user-images.githubusercontent.com/621529/58754992-aa11e500-848f-11e9-9124-288c988aabe2.gif)

**Comment by Lothrazar** [comment]
You will have to re-take your locations with the gps to get the side of course :) https://minecraft.curseforge.com/projects/cyclic/files/2719060
