### ISSUE TITLE
Automated User Error in Server log files

### ISSUE THREAD

**Issue by darkphan** [Lothrazar/Cyclic#1127]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: 1.19.6

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I believe someone on the server has a user trying to place blocks that it can't place (I have not tracked down the automated user in the world yet) and it generates a Null Pointer Exception as seen in the log snippet below.

Log file link: https://pste.me/#/6GNbM

**Comment by Lothrazar** [comment]
yeah hard to see what caused it from the logs, but it tells me the right place to try to add in a bandaid and more logging details

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2704643
