### ISSUE TITLE
Incorrect language key

### ISSUE THREAD

**Issue by sandtechnology** [Lothrazar/Cyclic#1129]
Minecraft Version: 1.12.2
Mod Version: 1.19.6
Single Player or Server:Both
Describe problem (what you were doing; what happened; what should have happened):
The lang files have a incorrect language key ：
> button.fan.speed.tooltip=Toggle Sound
> button.fan.range.tooltip=Control the range 
> button.fan.speed.tooltip=Control the speed

According to your [code](https://github.com/Lothrazar/Cyclic/blob/af09ca2ba45d70930d7dc679fbc53cea12326e5c/src/main/java/com/lothrazar/cyclicmagic/block/fan/GuiFan.java#L65)
"button.fan.**speed**.tooltip=Toggle Sound" should be "button.fan.**sound**.tooltip=Toggle Sound"

**Comment by Lothrazar** [comment]
I think it appears correct , now in latest branch. can you confirm?  

Sound is far left

Top is the Range

Bottom is the Speed

**Comment by sandtechnology** [comment]
emm...I think you are misunderstanding my expression,Is my expression not clear?
Not matter what,there is the thing I want to express:
The mistake is in the language files,not in your code.
In your code,the language key of toggling sound is "button.fan.sound.tooltip",but in your language files,is "button.fan.speed.tooltip",so you need to change it to "button.fan.sound.tooltip".

**Comment by sandtechnology** [comment]
I create a pull requst to solve the problem,plase review it:https://github.com/Lothrazar/Cyclic/pull/1144
