### ISSUE TITLE
Glowing chorus fruit flight timer counts down on incorrect conditions

### ISSUE THREAD

**Issue by SHsuperCM** [Lothrazar/Cyclic#1131]
Minecraft Version: 
1.12.2

Forge Version: 
14.23.5.2831

Mod Version: 
Cyclic-1.12.2-1.19.6

Single Player or Server:
Single Player

Describe problem (what you were doing; what happened; what should have happened):
The glowing chorus fruit should count down when flying but it actually counts down in other times.
If landing on a chest, you are still not "touching the ground" and it counts down.
Jumping ticks it down each time you're in the air.
Flying with an elytra also ticks it down.

It seems as if you're just checking if the player is on solid ground to determine if flying using the fruit or not when there is the easy check with `EntityPlayer::capabilities.isFlying` that I found in under a minute...

**Comment by Lothrazar** [comment]
i think 2 minutes is fine for now.  but yeah it should not count down when standing on a chest or using elytra that part makes sense at least.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2705255

**Comment by macks2008** [comment]
oh, this is fixed. glad I noticed this when setting the title for the issue I was about to create. Whoops!
Thanks for fixing this; I'll update the mod
