### ISSUE TITLE
Item Collector

### ISSUE THREAD

**Issue by SummaryPick** [Lothrazar/Cyclic#1132]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: 1.19.6

Single Player or Server: Single Palyer

Describe problem (what you were doing; what happened; what should have happened):

When the item collector receives an item on Sky Factory 4 the input changes from "Requires redstone" back to always on.  Worked with any item being interacted with in the item collector's inventory 

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
yep i see it now. in action: 
![inventoryRedstonbug](https://user-images.githubusercontent.com/621529/56859302-d640c000-693d-11e9-9b90-ee1d1737d587.gif)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2704643
