### ISSUE TITLE
Overlord Compatible issue

### ISSUE THREAD

**Issue by Lordbaane** [Lothrazar/Cyclic#1134]
Minecraft Version: 12.2

Forge Version: 2836

Mod Version: 1.19.8

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Unable to put milk bottles or buckets into the skeleton maker slot when creating new skeletons. No form of milk from any mod will go. Not sure what setting to disable to correct issue.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
You could try disabling Milk in the cyclicmagic.config, might fix it?

**Comment by Lordbaane** [comment]
That worked. Thanks. I appreciate your prompt response.

**Comment by Lordbaane** [comment]
It was Fluid milk to false for anyone else.
