### ISSUE TITLE
Allow for resetting of the GPS Marker location data

### ISSUE THREAD

**Issue by Dutchs** [Lothrazar/Cyclic#1135]
I'd be nice to be able to reset the stored coordinates of a GPS Marker so it stacks with other GPS Markers.
Either a shapeless crafting recipe or shift + rightclicking air could work for resetting it.

**Comment by Lothrazar** [comment]
Using it on air makes sense, like up in the sky.  maybe only when youre sneaking to avoid accidents?

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2719060
