### ISSUE TITLE
[Suggestion] Remote lever Right click in inventory

### ISSUE THREAD

**Issue by ilhamsitok** [Lothrazar/Cyclic#1136]
having fun with remote lever, I've been using it for a lot of stuff. I'm using satchel to store all of my remote levers and getting annoyed with pulling out the levers, right click it and put it back to the satchel. it'll be nice if you can do the right click in the inventory to toggle, may be having a special bag to store all of your remote levers

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2719060
