### ISSUE TITLE
EnchantXPBoost using EnchantWaterwalk config setting?

### ISSUE THREAD

**Issue by agrinder** [Lothrazar/Cyclic#1139]
https://github.com/Lothrazar/Cyclic/blob/e8c574bdfca38654dc5b933268adbd2e8cb6795a/src/main/java/com/lothrazar/cyclicmagic/enchant/EnchantXpBoost.java#L69

I noticed this while checking into the XP Boost gains from Ores. Looks like the rest of the enchants use their own config option while this one is using the Waterwalking enchant config in syncConfig?

I was able to get 20-25 levels (from 0) of XP from 6 diamond blocks using just Experience Boost III. I could not find a config setting to nerf this but did find a private constant XP_PER_LEVEL. Are there plans to be able to set the XP in the config and possibly add the option to enable/disable the enchant?

**Comment by Lothrazar** [comment]
this is a typo so yeah that config is broken and/or missing

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2719060
