### ISSUE TITLE
Item Sorter ignores rightmost slot in filters

### ISSUE THREAD

**Issue by Twoseventyone** [Lothrazar/Cyclic#1140]
Minecraft Version: 
1.12.2 SkyFactory 4.0.5
Forge Version: 
14.23.5.2831
Mod Version: 
1.19.8
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
When using Item Sorters, putting an item in the rightmost slot of any color causes the slot to behave as though there are no items, and the sorter ignores that slot's filter.
What should have happened: 
The Sorter checks the item filter in the last slot, and directs items accordingly.

Log file link:
https://paste.atlauncher.com/view/1a33c837

Video/images/gifs (direct upload or link): 

Test setup:
![2019-05-09_00 09 39](https://user-images.githubusercontent.com/31565966/57408718-167e2900-71ef-11e9-94ab-43122cf2fc1a.png)

Filter configuration:
![2019-05-09_00 09 49](https://user-images.githubusercontent.com/31565966/57408681-f2bae300-71ee-11e9-93de-c437b7b927a5.png)

Blue chest gets the acorns properly:
![2019-05-09_00 10 01](https://user-images.githubusercontent.com/31565966/57408682-f2bae300-71ee-11e9-809c-8e821ec54f0c.png)

Red chest does not get the resin:
![2019-05-09_00 10 23](https://user-images.githubusercontent.com/31565966/57408684-f2bae300-71ee-11e9-926e-6bb504182c9b.png)

Yellow chest gets the resin, even though there's a filter for it on Red:
![2019-05-09_00 10 38](https://user-images.githubusercontent.com/31565966/57408685-f2bae300-71ee-11e9-9c7f-7f01da4d5c51.png)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2719060
