### ISSUE TITLE
Localization conflict about Cyclic

### ISSUE THREAD

**Issue by mcBegins2Snow** [Lothrazar/Cyclic#1142]
Minecraft Version:

- 1.12.2

Forge Version: 

- 14.23.5.2836

Mod Version: 

- Cyclic 1.19.9
- Biomes O' Plenty 7.0.1

Single Player or Server:

- Single Player

Describe problem (what you were doing; what happened; what should have happened):

1. I installed Biomes O' Plenty and Cyclic two mods;
2. I created a new word;
3. I got a Celestial Crystal and a Crystallized Obsidian, then I found Biomes O' Plenty's Celestial Crystal changed to Cyclic's Crystallized Obsidian. 
4. I went to Biomes O' Plenty's GitHub page, found
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/resources/assets/biomesoplenty/lang/en_US.lang#L429
`tile.crystal.name=Celestial Crystal`
For Cyclic:
https://github.com/Lothrazar/Cyclic/blob/develop/src/main/resources/assets/cyclicmagic/lang/en_US.lang#L159
`tile.crystal.name=Crystallized Obsidian`
The two files both have `tile.crystal.name`, because Cyclic doesn't have namespace on language file.
https://mcforge.readthedocs.io/en/latest/concepts/internationalization/#usage-with-blocks-and-items said:
`Unlike registry names, translation keys are not namespaced. It is therefore highly recommended to prefix your modid somewhere to the translation key (e.g. examplemod.example_item) to avoid naming conflicts. Otherwise, in the event of a conflict, the localization of one object will override the other.`
5. The two items are supposed to show their own name.

Video/images/gifs (direct upload or link): 
![2019-05-10_09 35 07](https://user-images.githubusercontent.com/37864486/57497309-add79f00-7309-11e9-823e-87a8c766e448.png)
![2019-05-10_09 35 17](https://user-images.githubusercontent.com/37864486/57497310-ae703580-7309-11e9-8901-2d6b59aa73b7.png)
![20190510100858](https://user-images.githubusercontent.com/37864486/57497779-a9ac8100-730b-11e9-9c4e-dfe280f0ce4b.png)

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports

Also forge fixes it by default in 1.14
