### ISSUE TITLE
Evoker Fangs do Not despawn

### ISSUE THREAD

**Issue by Inonedn** [Lothrazar/Cyclic#1143]
Turns out the evoker fang staff causes the fangs to stay there forever, but invisible

**Comment by Lothrazar** [comment]
How do you know they are still there if they are invisible? is there a command or way to detect them

**Comment by Lothrazar** [comment]
Looked into it a little bit. I literally summon net.minecraft.entity.projectile.EntityEvokerFangs.java . so if they are staying alive it seems to me its the same as vanilla when the mobs spawn them.

**Comment by resinate** [comment]
yea i just found this error also. it can spawn 1000s of them over time

**Comment by Lothrazar** [comment]
But does this happen with the evoker vanilla mobs?

**Comment by Lothrazar** [comment]
so when i use /kill @e it lists in chat every entity that died.

So. i use fang a dozen times

run the kill

Note the spider and player and item is listed

No evoker entities listed

How do i make these non dying entities? and how do i detect them?

![1143](https://user-images.githubusercontent.com/621529/58893084-44e30d00-86a4-11e9-8858-56b95fcfb710.gif)

**Comment by resinate** [comment]
press F3 after spamming it and ull see it under entities count

**Comment by resinate** [comment]
any word?

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
