### ISSUE TITLE
Issues with both Sensor Display and Text Projector

### ISSUE THREAD

**Issue by Kiefy** [Lothrazar/Cyclic#1146]
Minecraft Version: **1.12.2**

Forge Version: **14.23.5.2781**

Mod Version: **1.12.2-1.19.2**

Single Player or Server: **Dedicated Server**

Describe problem (what you were doing; what happened; what should have happened):

**Sensor Display:** I can't get it to show energy readouts on either Mekanism batteries or EnderIO conduits.  It always shows "- -". Which type of energy blocks does it support?

**Text Projector:** Any way to change the Solid black background, or maybe push the text forward 1 block so I can choose my own background?  Are you meant to place projectors like a wall?

**Comment by Lothrazar** [comment]
The first issue with the sensor not reading energy:  can be fixed with the help of this https://github.com/Lothrazar/Cyclic/issues/1126 

Second one, ill do it now if its easy, otherwise ill figure it out later. background would be great

**Comment by Lothrazar** [comment]
You can place like them as a wall. For example you could have the top left text projector make some giant text and the other ones are "not used" except for a background 
![1146](https://user-images.githubusercontent.com/621529/58755914-6c6a8780-84a2-11e9-8f4e-b9090c753527.PNG)

**Comment by Lothrazar** [comment]
Depending on how EnderIO conduits are implemented, they might not show a reading  regardless would need some testing

**Comment by Lothrazar** [comment]
"Text Projector: Any way to change the Solid black background, or maybe push the text forward 1 block so I can choose my own background? Are you meant to place projectors like a wall?" 
I see what you mean now, some offset in that direction perpendicular to the screen ...

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2719060
