### ISSUE TITLE
Uncrafting Grinder not uncrafting anything [? iron axe ]

### ISSUE THREAD

**Issue by wwaisath** [Lothrazar/Cyclic#1147]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2837

Mod Version: 1.19.9

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
The uncrafting grinder says no recipe found for anything placed into it, including vanilla items like stone axe, iron axe, and iron sword.

Log file link:

Video/images/gifs (direct upload or link): 
![Uncrafting Grinder](https://user-images.githubusercontent.com/47764764/57648648-efbb4c00-757a-11e9-8050-962105de982c.png)

**Comment by SaiyanKirby** [comment]
Having the same issue, same version.

**Comment by Lothrazar** [comment]
Works for me.

Two things could cause this.

1- the blacklist in config might have this item listed

2- if there is any NBT data such as enchantments, and if theres no recipe that produces that data.

![1147](https://user-images.githubusercontent.com/621529/58756459-e8b69800-84ad-11e9-9a0f-69bdb8424a9a.gif)

**Comment by wwaisath** [comment]
Sorry for the delay in addressing more of this issue. I am not using a modpack, so that is definitely not the issue.

The following is copy/pasted from my cyclicmagic.cfg file (specifically the Uncrafting Grinder lists):

 ##########################################################################################################
    # uncrafter
    #--------------------------------------------------------------------------------------------------------#
    # Blacklists and other tweaks for the Uncrafting Grinder.   (Use F3+H to see the details, it is always 'modid:item')
    ##########################################################################################################

    uncrafter {
        # Items that cannot be uncrafted.   [default: [minecraft:end_crystal], [minecraft:magma], [minecraft:elytra], [forge:bucketfilled], [astralsorcery:itemwand], [progressiveautomation:WitherDiamond], [progressiveautomation:WitherGold], [progressiveautomation:WitherIron], [progressiveautomation:WitherStone], [progressiveautomation:WitherWood], [techreborn:uumatter], [spectrite:spectrite_arrow], [spectrite:spectrite_arrow_special]]
        S:BlacklistInput <
            minecraft:magma
            minecraft:elytra
            forge:bucketfilled
            progressiveautomation:WitherDiamond
            progressiveautomation:WitherGold
            progressiveautomation:WitherIron
            progressiveautomation:WitherStone
            progressiveautomation:WitherWood
            techreborn:uumatter
            spectrite:spectrite_arrow
            spectrite:spectrite_arrow_special
         >

        # If a mod id is in this list, then nothing from that mod will be uncrafted  [default: [projecte], [flammpfeil.slashblade], [resourcefulcrops], [spectrite]]
        S:BlacklistMod <
            projecte
            flammpfeil.slashblade
            resourcefulcrops
            spectrite
         >

        # Items that cannot come out of crafting recipes.  For example, if milk is in here, then cake can be uncrafted, but you get all items except the milk buckets.   [default: [minecraft:milk_bucket], [minecraft:water_bucket], [minecraft:lava_bucket], [minecraft:nether_star], [minecraft:elytra], [forge:bucketfilled], [abyssalcraft:cloth], [abyssalcraft:transmutationgem], [botania:manatablet], [extrautils2:glasscutter], [harvestcraft:juiceritem], [harvestcraft:mixingbowlitem], [harvestcraft:mortarandpestleitem], [harvestcraft:bakewareitem], [harvestcraft:saucepanitem], [harvestcraft:skilletitem], [harvestcraft:potitem], [harvestcraft:cuttingboarditem], [ic2:forge_hammer], [ic2:cutter], [minecolonies:sceptergold], [mysticalagriculture:infusion_crystal], [mysticalagriculture:master_infusion_crystal], [techreborn:uumatter]]
        S:BlacklistOutput <
            minecraft:milk_bucket
            minecraft:water_bucket
            minecraft:lava_bucket
            forge:bucketfilled
            abyssalcraft:cloth
            abyssalcraft:transmutationgem
            harvestcraft:juiceritem
            harvestcraft:mixingbowlitem
            harvestcraft:mortarandpestleitem
            harvestcraft:bakewareitem
            harvestcraft:saucepanitem
            harvestcraft:skilletitem
            harvestcraft:potitem
            harvestcraft:cuttingboarditem
            ic2:forge_hammer
            ic2:cutter
            minecolonies:sceptergold
            techreborn:uumatter
         >

        # If you change this to true, then the uncrafting will just take the first of many options in any recipe that takes multiple input types.  For example, false means chests cannot be uncrafted, but true means chests will ALWAYS give oak wooden planks. [default: true]
        B:PickFirstMeta=true
##############################################################################

As to the issue with Zenscript, I don't use it and all the items I have tried to uncraft have recipes.

As to the NBT data, there shouldn't be any, as the axe I used was one I crafted and immediately tried to uncraft. I have also tried it with other unused items with the same (lack of) results.

With the update, I was able to uncraft a Large Storage Crate from Actually Additions, as well as a few other items from Cyclic, Vanilla, and other mods, but Vanilla tools still seem to be an issue (tried with a stone pickaxe, iron pickaxe, wooden axe, and bow). All of them are still giving me No Recipe Found, as are the charms from Cyclic, Not Enough Wands wands, Automatic Torch, Cyclic Building Scepter, Engraved Thunder and Rod of Elevation from Cyclic, the Ender Bucket from Ender Utilities, and many others. Other things are successful, such as the Vanilla furnace and jukebox, Cyclic's Heart Container, and the Pickaxe Kit from Forestry.

I appreciate you looking into this. I am going to try this in a new instance without other mods and see if there is something oddly conflicting between Cyclic and the other mods I have installed.

**Comment by GoldenHashtag** [comment]
i thought we had the same issue. items dropped from mob kills, playing on along with many other mods.
next time I'm free I'll write a full steps of reproduction.

**Comment by Lothrazar** [comment]
If the iron axe has any NBT data such as enchants, it wont find a recipe.  By default with no scripts or modpacks it uncrafts plain iron axes.  It only works if theres an existing plain crafting-table recipe.  Closing as stale and working as intended
