### ISSUE TITLE
Tanks acting funny [should only output downwards to other tanks, not pipes/other blocks ]

### ISSUE THREAD

**Issue by thill19** [Lothrazar/Cyclic#1148]
Minecraft Version: 1.12/2

Forge Version:  14.23.5.2836

Mod Version: Cyclic-1.12.2-1.19.9.jar

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):

after 1 tank is full the fluid will flow through all of the tanks connected to the same pipe

Log file link:

Video/images/gifs (direct upload or link): https://youtu.be/68a6bes6ViE

**Comment by Lothrazar** [comment]
Oh yeah. the tanks have a feature where they try to drain down-wards and fill the machine or tank below them.  

But it doesnt realize that the thing below is a pipe and not a machine .  So i either need to add a way for player to disable this. or have it look for pipes and stop doing it. or some other solution

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2719060
