### ISSUE TITLE
[Suggestion] Config option to tone down/disable Fire Charm's visual effect?

### ISSUE THREAD

**Issue by katubug** [Lothrazar/Cyclic#1149]
Minecraft Version: 1.12.2

Forge Version: forge-1.12.2-14.23.5.2825-universal

Mod Version: Unsure, but this isn't a bug so I don't think it's crucial

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
The effect of the fire charm takes up a good 50% of the screen, which means that it *looks* like I'm on fire and I can't see what I'm doing. I have the option to remove first-person potion effects turned on in Quark, but it doesn't seem to affect the Fire Charm. Is there any way we can remove the effect or make it smaller? Or change it so that it doesn't look like I'm burning, instead of burning-immune?

**Comment by Lothrazar** [comment]
The charm has no effect by itself, i think the fire effect is from vanilla-being-on-fire.

But yes, if you arent taking damage, having the flames go away would be very good

**Comment by GoldenHashtag** [comment]
@Lothrazar 
To be consistent with #1171 , this can be added into your mechanism changes mod, something like "suppress all burning effect when there is fire resistant potion effect".

**Comment by katubug** [comment]
I do think there is validity in that suggestion. However, speaking
personally, I'd rather have this be "built in" to the charm than to have to
add another mod to get that functionality.

**Comment by Lothrazar** [comment]
This is still a great idea and id love to implement it. But currently it relies just on native fire protection. so the particles and fire effects are baked into the game, and theres no super clean easy way to hack in there to hide those rendering effects in this case .  
By default, if you are on fire but immune to fire, it doesnt care it just shows all the things.  
Also, non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports

**Comment by katubug** [comment]
Totally reasonable, thank you for looking into it!
