### ISSUE TITLE
issues with candles

### ISSUE THREAD

**Issue by resinate** [Lothrazar/Cyclic#1151]
running 1.12.2

can u added config to disable the following:
1. disable additional candles from spawning
2. disable console spam when a mob is spawned
3. candle also replace ANY block with a new candle

**Comment by Lothrazar** [comment]
1. what do you mean additional candles? Do you mean something like only 1 per chunk allowed.

2. yep

3. not sure what you mean "replace any block" ?

**Comment by resinate** [comment]
no when using stuff like wand accel or time in bottle it spawns extra candles around the area and replaces any block they spawn in

**Comment by Lothrazar** [comment]
Yeah wand of acceleration works just fine with the candle so im not sure what you mean .  If you want to place extra candles then go ahead .

"replaces any block" no the candle does not place or replace any blocks. it only spawns mobs. thats all 

 Can you maybe make a recording of the problem if its a bug https://screentogif.com

**Comment by resinate** [comment]
u mustve fixed it without knowing it lol cuz now it wont happen anymore
