### ISSUE TITLE
[Suggestion] Additional Nether/End ore

### ISSUE THREAD

**Issue by Hexblood** [Lothrazar/Cyclic#1152]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.9

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

I am looking for an ore to be added to the list of Nether and End ores. Currently I am looking for Zinc (Various mods, but my current want is for use with the FuturePack mod). 

Log file link:
N/A

Video/images/gifs (direct upload or link): 
N/A

**Comment by Lothrazar** [comment]
There are tons of modded ores in cyclic_ores.cfg they are just disabled by default. so already in game!

**Comment by Lothrazar** [comment]
Actually now that I look at it, Zinc is missing from this file i forgot about this ore.


@Hexblood  any other mods other than Zinc i should add to this?  make a full list of anything missing  (and what mods they are used by - i will need the oredictionary key) and ill check them out

**Comment by Hexblood** [comment]
Actually I did come up with another. Tritanium (oreTritanium) from Matter Overdrive.

The only other thing that comes to mind are some of the Base Metals ores but they have their own Nether and End ore mods so probably not necessary for you to add them on your end.

**Comment by Lothrazar** [comment]
I can do more very easily only takes a handful of minutes. but ok so Zinc and Tritanium

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2720719
