### ISSUE TITLE
Fluid Filters (Question)

### ISSUE THREAD

**Issue by MonfGeiger** [Lothrazar/Cyclic#1153]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2768 (its what MultiMC recommends I use)

Mod Version: 1.19.8

Single Player or Server: Server/Single Player

This is less of an issue entry and more of a question. Do there exist filters to make the fluid extraction cable ONLY pull a certain liquid from any tank/block with multiple liquid inputs/outputs? I only ask because the version of sf4 the server I play on uses doesn't have the mekanism mechanical pipes enabled, and they banned the thermal dynamics item/fluid/flux ducts while pseudo banning the opaque versions because server plugin bugs

I got 2 mekanism brine making vats and I can't use the extraction cable on the brine tanks without pulling the water out before the brine; I only want the brine.

**Comment by Lothrazar** [comment]
No filters currently but this is a great feature to add

**Comment by Lothrazar** [comment]
WIP
![2019-06-03_07 30 45](https://user-images.githubusercontent.com/621529/58809857-953d6a80-85d1-11e9-9364-e3656ada9484.png)

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/labels
