### ISSUE TITLE
Unintended Mod Interaction between Cyclic and FTB Utilities

### ISSUE THREAD

**Issue by katubug** [Lothrazar/Cyclic#1155]
Minecraft Version: 
1.12.2

Forge Version: 
forge-1.12.2-14.23.5.2838-universal

Mod Version: 
- Cyclic-1.12.2-1.19.9
- FTBUtilities-5.4.0.96

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
Okay so this is a bit weird. With FTB Utilities you can change your ingame nickname by using /nick. However, due to the way Cyclic saves its extended inventory data, this means if you /nick [something], you lose access to your extended inventory. You can /nick and it will give you access again.

However, that's not the big thing. The big thing is that if you /nick [another player's name], you can access THEIR extended inventory. It even works on players who aren't currently online.

I'll also be reporting this to FTB Utilities, just in case.

**Comment by LatvianModder** [comment]
Simple fix, either save using UUID or getName() instead of getDisplayName()

**Comment by Lothrazar** [comment]
Yeah it uses player.getDisplayNameString()  inside of playerdata a file such as _Lothrazar.invo

I was planning to switch to UUID in 1.13, since if i do it now without any data porting players would lose their items

**Comment by LatvianModder** [comment]
I think if you switch it now to getName() it should be mostly fine, how many people actually use /nick function, like 20? :P I say it's better to break it for those 20 than allow someone else to steal your items

**Comment by katubug** [comment]
I'm inclined to agree with that. 1.12.2 is probably going to continue to be
the dominant version for at least a while until performance on newer
versions improves. I think if you put a Header-sized warning in the
changelog, or perhaps on the front page of the mod, then if people lose
their items it's their own fault.

And at least for myself, I don't put anything crucial in that inventory
anyway.

**Comment by LatvianModder** [comment]
Also another variant is
```java
File file = new File("whatever/path/" + uuid + ".invo")

if(!file.exists())
{
  File oldFile = new File("whatever/path/" + displayNameString + ".invo");
  if(oldFile.exists()) oldFile.rename(file);
}

//read file now
```

**Comment by Lothrazar** [comment]
Yeah good call if im careful enough like that it should be fine.  

Also even if the worst case happens and somebody "loses" their stuff, a server admin or whatever can just rename their playername file to their uuid since i wont delete anything.

**Comment by Lothrazar** [comment]
Hm looks like i started to go down this path but my logic is out of order. it is creating and writing both files , the UUID and the playername so maybe its an easy change then https://github.com/Lothrazar/Cyclic/blob/05b5f8ca47f74ae51555481036ad27f90f75a3ac/src/main/java/com/lothrazar/cyclicmagic/util/UtilPlayerInventoryFilestorage.java#L185

**Comment by Lothrazar** [comment]
SO you will see existing UUID.cyclicinvo files there that it was already saving and writing to every event i just stripped out all the playername.invo references

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/labels
