### ISSUE TITLE
Inventory Upgrade & Hippogryph from Ice & Fire Conflict

### ISSUE THREAD

**Issue by TimBobWe** [Lothrazar/Cyclic#1158]
Minecraft Version: 
1.12.2

Forge Version: 
14.23.5.2836

Mod Version: 
Cyclic: 1.12.2-1.19.9
Ice & Fire: 1.7.1-1.12.2
Enigmatica 2: Expert 1.64d

Single Player or Server: Both

If you have eaten an Inventory Upgrade, thus unlocking the extra inventory slots and functionality, riding a Hippogryph from Ice & Fire breaks the player inventory. No items can be picked up and the player is unable to interact with Crafting Tables. Hippocampus do not seem to cause the same issue. All other mobs are untested.

Player is forced to Relog in order to rectify the situation.

**Comment by Lothrazar** [comment]
@TimBobWe  if theres a crash or error is there any error logs?

**Comment by TimBobWe** [comment]
There is neither a crash nor error AFAIK. It just disallows the player from acquiring dropped items and the use of crafting tables or chests. 

Upon retesting right now I am finding the bug to be less consistent than previously experienced.
The most consistenly unusable non-player inventory is the "Crafting Station" from Tinker's Construct.

The bug occurs after dismounting, not sporadically while mounted. This is a major oversight in my original description. My apologies.

**Comment by Lothrazar** [comment]
As far as i can tell Fire and ice uses and probably replaces some player data at some point, and cyclic relies on this player data for these screens.  
"The most consistenly unusable non-player inventory is the "Crafting Station" from Tinker's Construct."

WIth so many other mods it seems like there must have been a bug in ice & fire. good luck :)
