### ISSUE TITLE
Dungeons, Dragons, Space Shuttles - particles from sprinklers?

### ISSUE THREAD

**Issue by Seth0067** [Lothrazar/Cyclic#1159]
Minecraft Version: 1.12
Forge Version: 2836
Mod Version: 1.19.8
Single Player or Server: sp

Describe problem (what you were doing; what happened; what should have happened):

I'm using the sprinklers in the "Dungeons, Dragons, and Space Shuttles" modpack, They are placed and rotating, but I am not seeing water particles. I think they are "working" based on  crop growth and perhaps a mod interaction is preventing particles, but any way to verify this?  

Have you come across any issues with other mods preventing particle display.  I am using Fancy Block Particles, but have tried disabling this to see if this was causing problems (doesnt seem like this was the problem.)

Thanks, Lothrazar, hope you are well.

**Comment by Lothrazar** [comment]
They just spawn normal water splash particles, vanilla particles its not anything custom. If crops are getting growth then its working.  Yeah not sure about mod conflicts 

to disable particles that spew from sprinklers you can sneak-right click on them.  Its kind of a hidden feature since i didnt want to add a whole inventory/GUI to the block.  Maybe thats related?

**Comment by Seth0067** [comment]
Yes - I saw that great little feature.  I tried despawning them and the re-enabling, but nothing.  No worries, as long as the growth effect works.  

Here's a video that i made to attach but was having problems with Google outage yesterday.
[Sprinkler Video](https://youtu.be/bTiNQAc_ZxU)

**Comment by Lothrazar** [comment]
Thanks for the video.  Glad to hear growth works.  In a new world it appears to spray at least for me . version 5.0 of modpack,  
![1159](https://user-images.githubusercontent.com/621529/58923219-9666b880-86f3-11e9-8a89-4d71f9fe9b34.gif)

**Comment by Seth0067** [comment]
ok - i dunno whats up then. thx for the attention. :)
