### ISSUE TITLE
1000s upon 1000s of enities with involker wand

### ISSUE THREAD

**Issue by resinate** [Lothrazar/Cyclic#1161]
1.12.2 latest mod version: 

when spamming wand it creates entities and doesnt despawn them. hard to explain, just go in a world with nearby mob spawner and use wand ALOT of times.

**Comment by Lothrazar** [comment]
How do you detect the entities? 

https://github.com/Lothrazar/Cyclic/issues/1143

**Comment by Lothrazar** [comment]
closed as duplciate. bug still open in other thread
