### ISSUE TITLE
Issue with Auto Crafter

### ISSUE THREAD

**Issue by CLeaR911** [Lothrazar/Cyclic#1162]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2838
Mod Version: 
Sky Factory 4
Single Player or Server:
Aternos Server
Describe the problem (what you were doing; what happened; what should have happened):
Can't Understand why there is no fuel slot for the auto crafter

Log file link:
?

Video/images/gifs (direct upload or link): 
https://user-images.githubusercontent.com/51393864/58929696-12212f00-870d-11e9-9cdc-3cf6ae4e1f2b.png

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Yes in old versions of the mod , back when forge did not support Energy i invented my own fuel system.

Now that Forge support energy and i dont need to depend on 17 thermal mods at once it just takes energy.  So any battery or generator block beside the machine. or run it in with cables

**Comment by CLeaR911** [comment]
ok thanks so much
