### ISSUE TITLE
Compatability with Tinkers' Construct Smeltery and Fluid Tank? 

### ISSUE THREAD

**Issue by BluFlameBird** [Lothrazar/Cyclic#1163]
Minecraft Version: 1.12.2

Forge Version: forge-14.23.5.2831

Mod Version: 	Cyclic-1.12.2-1.19.8.jar on Sky Factory 4.

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

I've been trying to find a way to put experience fluid into the smeltery in order to make Soul Sand. The only way I've found to do so is by manually interacting with the smeltery drain with a bucket of experience. I've tried using the faucet and the Fluid Extraction Cable, but that didn't seem to put any liquid experience into the smeltery.

Log file link:
n/a

Video/images/gifs (direct upload or link): 
n/a
If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by TheBlueTroll** [comment]
into the smeltery? by that do you mean the mini smeltery (the melter) or into a full size smelter?

additionally, why are you putting the experience liquid into the smelter? just pipe it into the casting basin with the fluid extraction cable like shown in the picture.
![TheShot](https://user-images.githubusercontent.com/9428136/59340516-81b89f00-8d49-11e9-91ad-42253299ecec.png)

showing a screenshot of you current would also help to rule out a bad setup.

**Comment by Lothrazar** [comment]
Looks like it should work as long as theres a recipe for it. ?

**Comment by Lothrazar** [comment]
looks like its working as intended
