### ISSUE TITLE
[Suggestion] Add metadata to Controlled Miner white/blacklist

### ISSUE THREAD

**Issue by TheRealWebGremlin** [Lothrazar/Cyclic#1166]
An option to take metadata into account on the white- or blacklist of the controlled miner would be a welcome addition.

I suggest this because I wanted to use the miner to automate the production of livingwood and stone of Botania. I've built a structure around my setup made out of livingwood planks, glimmering livingwood, etc. Basically all different kinds of livingwood bar the actual raw livingwood. However all variants have the same item ID, just different metadata. The miner does not discriminate based on that. The result is the miner will try to mine parts of the structure rather than just the stone and wood the pure daisies generate. Hence I think a metadata feature would be useful.

Thanks for considering :)

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports. <3
