### ISSUE TITLE
[Suggestion] Game mechanic changes should be separated from Cyclic

### ISSUE THREAD

**Issue by GoldenHashtag** [Lothrazar/Cyclic#1171]
Cyclic is having more and more contents, and instead of being a collection of all your creations, Cyclic itself should be mainly focusing on adding new blocks, weapons, tools, items and stuff like that. And create a new mod for only game mechanic changes.

**Comment by Lothrazar** [comment]
100% agree

**Comment by Lothrazar** [comment]
in 1.14 entire mod is getting rebuild and any non physical content will get split out like this, slow process. existing long term plan. no changes to 1.12 so we dont break existing worlds
