### ISSUE TITLE
Cyclic will not follow configurations from server

### ISSUE THREAD

**Issue by GoldenHashtag** [Lothrazar/Cyclic#1172]
Minecraft Version: 
1.12.2

Forge Version: 
14.23.5.2838

Mod Version: 
1.19.11

Single Player or Server:
Related to Server, but it's a client-side issue.

Describe problem (what you were doing; what happened; what should have happened):
What's the problem:
When joining a server with configurations different than the local one, Cyclic will not follow the server settings, instead it keeps using local settings, this causes conflicting when syncing with server.
1.
What happened:
When server and client has different settings of I:HeartContainerMax, Heart Container behaves incorrectly.
When server set to HeartContainerMax=100, client set to HeartContainerMax=30, you can't have heart more than 30.
When server set to HeartContainerMax=30, client set to HeartContainerMax=100, you still can't have heart more than 30.
What to be expected:
When server set to HeartContainerMax=100, you should be able to have heart for up to 100 regardless of client settings.
2.
What happened:
When server and client has different settings of "Faster Ladders", it will always follow local settings.
What to be expected:
When server and client has different settings of "Faster Ladders", it should always follow server settings.

Solution:
Don't load configuration when in main menu.
When logging into game, download configuration from server and apply it (without changing local settings).

Log file link:
No log file.

Video/images/gifs (direct upload or link): 
Not yet, I'll attach one later.

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler
Not related to performance.

**Comment by LoganDark** [comment]
You can't. Certain things in the config like which items are enabled can't be changed while the game is running.

**Comment by GoldenHashtag** [comment]
Then just ban it.
If server has items client hasn't enabled, then ban client from joining that server.
If client has items server hasn't enabled, mod doesn't have to do anything.
If server has different configs than clients' then follow server config.

**Comment by Lothrazar** [comment]
yeah this is just the way it is for servers and forge , config is hooked up the standard way.  Server should have master copy and clients get a copy the same time they get the modpack. some settings are client only but not anything for "solid content"
