### ISSUE TITLE
[Bug] [Repeatable] Equipable item duplication with Auto User.

### ISSUE THREAD

**Issue by avangelion** [Lothrazar/Cyclic#1173]
Minecraft Version: **1.12.2**

Forge Version: **2825-universal**

Mod Version: **1.18.5**

Single Player or Server: **Multiplayer server**

Describe problem (what you were doing; what happened; what should have happened):

**Placing a piece of enchanted gear (weapon/armor) into a Cyclic Auto User and having it attack [Electroblob's Wizardry](https://minecraft.curseforge.com/projects/electroblobs-wizardry)'s "Wizard" mobs are then duplicating the gear when picked up with the Cyclic Item Collector.**

Log file link: **No appearance of anything odd in the log file**

Video/images/gifs (direct upload or link): **I can take a video if needed [here](https://drive.google.com/open?id=1UGGRL_HahlkbDkLTMaVwf4-P6eyY67kp)'s images of the items that were duplicated, and the related blocks.**

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler: **I have Sampler available to me but this isn't lag related.**

**Comment by Lothrazar** [comment]
So, if im reading this right.  Whatever weapon the machine is using, when it kills one of those wizard mobs , the mob drops a copy of the weapon?

**Comment by Lothrazar** [comment]
Looked into it but forgot to update earlier.  Its only this one Wizard mob doing this and not any other mob that i tested, modded or vanilla. so bug is something weird the wizard is doing
