### ISSUE TITLE
Mattock dosen't get affected by fortune

### ISSUE THREAD

**Issue by DragonmasterDJ** [Lothrazar/Cyclic#1174]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.12.2-1.19.9

Single Player or Server: server

I decided to spend ages getting fortune onto the mattock, though after a recent discovery, and a waste of XP and emeralds to get the fortune 3 book. it seems as if the mattock breaking blocks dosen't get affected by fortune. I think this is because it just simply breaks the blocks around the main block being targeted, not caring if they're affected by any enchantments.

Log file link:
-

Video/images/gifs (direct upload or link): 
https://drive.google.com/file/d/1TOA59qDvgx9wFFddLEQLSA4dbh8skrIX/view?usp=sharing

As the video shows, it may not be too obvious, but I only got 3-4 extra quarts from the block I broke, while I only got 4-3 from the others I broke from the 3x3!

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler
-

**Comment by Lothrazar** [comment]
Ill set up a 9x9 of ore with the middle as dirt.

If fortune does not work, i should get exactly 8 coal items.  


Fortune 3 in video:

![1174](https://user-images.githubusercontent.com/621529/59902954-79e5a400-93b4-11e9-85bb-1376c66ce5c6.gif)
