### ISSUE TITLE
 Cyclic Piston Scepter Duplicates Flux Points and Plugs

### ISSUE THREAD

**Issue by NillerMedDild** [Lothrazar/Cyclic#1175]
Minecraft Version: 
- 1.12.2
Forge Version: 
- 1.12.2-14.23.5.2836
Mod Version: 
- Cyclic-1.12.2-1.19.9
Single Player or Server:
Both I believe
Describe problem (what you were doing; what happened; what should have happened):
Shift-right-clicking a Flux Point or Plug from Flux Networks with a Cyclic Piston Scepter in Push or Pull mode will cause it to shift over by a block (as expected) but also drop a copy as an item. 

Log file link:
I don't have a log, but I don't mind asking the original reporter for one if you should need it.

Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1243

**Comment by Lothrazar** [comment]
I am calling setblockToAir and destroyBlock with  "dropBlock=false" https://github.com/Lothrazar/Cyclic/blob/93198c9ff1fd5213594ab7cdd4ccbde03efdb077/src/main/java/com/lothrazar/cyclicmagic/util/UtilPlaceBlocks.java#L252 so this might be an issue on flux networks side.  

ill look into adding a config solution maybe

**Comment by NillerMedDild** [comment]
Oh no, it's probably Tool Progression causing it then ^^'
