### ISSUE TITLE
Can't pipe items into an automated user

### ISSUE THREAD

**Issue by gafusss** [Lothrazar/Cyclic#1177]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.12.2-1.19.11

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):

Can't pipe items into automated user.

I'm playing SkyFactory 4.  
On version 4.0.3 (Cyclic 1.19.6) I had a setup which piped cobblestone using cyclic item extraction cable and bundled cables into an automated user, which then placed it into a cauldron for lava generation.

Once I updated to 4.0.8 (Cyclic 1.19.11) the system stopped working. No cobblestone is being piped into the automated user.

Integrated tunnels item exporter instead of cyclic cables does not work either (note: transfers more than a single item at a time).

Using a hopper works (note: transfers a single item).

Replacing the cyclic cables (which sets item extraction cable's transfer rate to 1) works, but is slow. Increasing trasfer rate to any other value breaks the system (resetting it to 1 does not help).

Cables output items properly into, e.g., a chest -> probably not a cable issue

Might be somehow related to changes in 1.19.9 (maybe AU does not accept items if there are more than 1 in cable/pipe/whatever's inventory)

**Comment by Lothrazar** [comment]
hopper can pipe things into the left three slots for me. extraction cables work as well. very weird? 
![1177](https://user-images.githubusercontent.com/621529/59968173-178ebf80-94ea-11e9-88a5-6672ddd3f038.png)
.

**Comment by gafusss** [comment]
@Lothrazar what's the transfer rate on that extraction cable? Works for me with 1 only

**Comment by gafusss** [comment]
Just made a new 1.12.2 instance with forge 14.23.5.2838 and cyclic 1.12.2-1.19.11 only, new creative world.
Same thing, freshly placed extraction cable works, until I change the transfer rate.


![output](https://user-images.githubusercontent.com/17786071/59968695-6702d900-9546-11e9-9d5c-4d37e3339b68.gif)

**Comment by gafusss** [comment]
Same issue on 1.19.9. works properly on 1.19.8

**Comment by TheRealWebGremlin** [comment]
Same issue on 1.19.12 in Enigmatica 2: Expert; Can't pipe in items from any side with EIO conduits or TE itemducts. Workaround is to put a downgrade on so it pipes one item at a time.

**Comment by Lothrazar** [comment]
seems ok with hoppers 
![hoppers](https://user-images.githubusercontent.com/621529/61919846-41356f00-af0c-11e9-8055-d39ca0526f11.gif)

**Comment by TheRealWebGremlin** [comment]
> seems ok with hoppers
That's probably because hoppers transport one item at a time, which is the issue. If more than one item is being extracted at a time the automated user won't accept the items at all. That's why Gafusss had to change the transfer rate and I had to use speed downgrades.

**Comment by Lothrazar** [comment]
"That's probably because hoppers transport one item at a time, which is the issue. If more than one item is being extracted at a time the automated user won't accept the items at all. That's why Gafusss had to change the transfer rate and I had to use speed downgrades."

I didn't respond right away but thanks for the update.  So it does work in at least this way . I think for now this is good enough, i dont see any easy fix for it and the machine is pretty stable otherwise.  non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. 1.12 will still get fixes for major stuff (item loss or crashes or the like). Working on brand new mods and 1.14+ ports
