### ISSUE TITLE
Harvester does not harvest additional seeds from Mystical Agriculture crops

### ISSUE THREAD

**Issue by curiosity-a** [Lothrazar/Cyclic#1179]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2825

Mod Version: 1.19.2

Modpack: Mystical Skies 1.7.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I set up the harvester to process a plot of crops from Mystical Agriculture. After a while, I have noticed that despite collecting a lot of essence, the harvester didn't produce any additional seeds (whereas if I harvest said plot manually, I usually get at least one).
So I looked in the code and noticed one peculiar thing:
https://github.com/Lothrazar/Cyclic/blob/e85e37abc8aa4e72cc9eb3ce1dc590f5dbe38cec/src/main/java/com/lothrazar/cyclicmagic/util/UtilHarvester.java#L350
You are deleting the item stack completely. Which would mean that vanilla crops must be returning one item per stack, since it works with wheat. So I went to look at how Mystical Agriculture crop generates drops:
https://github.com/BlakeBr0/MysticalAgriculture/blob/255cda0a606078b627a767bb6d6877dc6deb2cd3/src/main/java/com/blakebr0/mysticalagriculture/blocks/crop/BlockMysticalCrop.java#L136
Turns out that it makes a stack with the total number of seeds in it from the start.
I am certain that this is the cause of the issue.

**Comment by Tntdruid** [comment]
You only get extra if the player break the plants.

**Comment by Lothrazar** [comment]
Yep this is working as intended. It consumes one seed as a cost to mimic the re-plant of the crop.  If you need seeds then farm a few by another method and then return to automation

**Comment by curiosity-a** [comment]
It may consume more than one seed. Is this really intended?

**Comment by curiosity-a** [comment]
I guess I will have to make a new issue when I'm back on a supported MC version. Farewell.

**Comment by IpFruion** [comment]
> 
> 
> Yep this is working as intended. It consumes one seed as a cost to mimic the re-plant of the crop. If you need seeds then farm a few by another method and then return to automation

If this is working as intended than it should only delete 1 seed as @Lothrazar specified. However, in the code it removes the entire `ItemStack.` So when mods generate more than one seed in the `ItemStack(..., 2)` it deletes more than one. This seems to not be "working as intended" as per the comment from the Owner.

Currently in SF4 it deletes the extra seeds that you get from mystical agriculture. Other mods that use "harvesters" (like industrial foregoing) work with the extra seeds that are generated.
