### ISSUE TITLE
Support for Quark's Chest Buttons

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1183]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Mod Version: 1.19.12
[Quark Version](https://quark.vazkii.net/): r1.5-168

Describe problem: 
- Support for Quark's Sort, Deposit, and Merge Chest buttons for the Extended Inventory and the Storage Bag would be nice. 
- I could add it through Quark's config file, but items are deleted if the sort button is pressed in the Extended Inventory GUI and the buttons overlap in the Storage Bag's color buttons.
- The link takes you to the Quark website, the buttons are found under the management tab.

**Comment by WenXin20** [comment]
I forgot to mention that for both Inventory Tweaks and Inventory Sorter, the Middle Button Click-to-Sort feature doesn't work in the Extended Inventory GUI either.

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports

**Comment by WenXin20** [comment]
That's fine, I've moved on to 1.14 at this point too.
