### ISSUE TITLE
Opening the storage bag doesn't count as an action

### ISSUE THREAD

**Issue by curiosity-a** [Lothrazar/Cyclic#1185]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.12

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
When I open a storage bag, I expect the item in my other hand not to be used, just like with any other item that has a use action.

To test this, put a storage bag in your main hand and any block into your secondary hand. Aim at where you would be able to place the block (e.g. the clear ground nearby), then open the storage bag. Observe the block being placed.

**Comment by Lothrazar** [comment]
this affects lots of items, but i tried tweaking the return and it doesnt change hmm

**Comment by curiosity-a** [comment]
If it helps, satchels from Thermal Expansion don't have this issue.

**Comment by Lothrazar** [comment]
Currently working as intended in latest version, does not place block 
![1185](https://user-images.githubusercontent.com/621529/71599966-f1ce1d00-2b01-11ea-98e6-9c474666e965.gif)
