### ISSUE TITLE
Exchange Scepters retarget every use

### ISSUE THREAD

**Issue by Nightcaste** [Lothrazar/Cyclic#1186]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.12

Single Player or Server:  Server

Describe problem (what you were doing; what happened; what should have happened):
This is happening in the Mystical Skies pack.  When I try to replace Thaumcraft Arcane Stone blocks with Storage Drawers Trim, the block swaps, but as soon as I pick up the Arcane Stone, the block the scepter has selected as the block to place from my inventory changes to Arcane Stone.

**Comment by curiosity-a** [comment]
The scepter always changes blocks to the first block in your inventory left to right, top to bottom. Make sure you have your materials in the top row and a place for the block you are replacing to go (e.g. partial stacks, empty hotbar slots).

**Comment by Lothrazar** [comment]
yeah the item doesnt have its own inventory so it takes from yours. must more simple and basic compared to more advanced mods.  Not sure about the "retarget" thing ?  

Normal use

![1186 retarget](https://user-images.githubusercontent.com/621529/61929522-080ef600-af30-11e9-91ef-2783d90a37c2.gif)

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports

when this item is remade in 1.14 it will work differently
