### ISSUE TITLE
Recipe Book Issues w/ Inventory Crafting

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1187]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Cyclic Version: 1.19.12

Describe problem:
- The buttons for the inventory crafting and the extended inventory disappear when the recipe book is open.
- In the inventory crafting GUI, clicking on the recipe book button won't open the book.

**Comment by Lothrazar** [comment]
The first one is working as intended,hiding it when crafting book is open. I could add this i guess


Second one is a bug, button is also under the armor slots and does nothing.  should be hidden OR moved & working

**Comment by Lothrazar** [comment]
![1187 a](https://user-images.githubusercontent.com/621529/62480429-ae46d100-b764-11e9-9d2e-45fbad127c0e.PNG)
![1187b](https://user-images.githubusercontent.com/621529/62480430-ae46d100-b764-11e9-803c-3d03d2e6c568.PNG)

**Comment by WenXin20** [comment]
That's odd, for the second one for me, the button does move to the proper spot. Could it be that it's not moving when there's a potion effect on?

**Comment by Lothrazar** [comment]
OH yeah youre right, i have a potion effect on. thats a third case

**Comment by Lothrazar** [comment]
Currently works as intended and button gets hidden 
![1187 works](https://user-images.githubusercontent.com/621529/71597703-21c4f280-2af9-11ea-883c-bc4cdc16bc3b.gif)
