### ISSUE TITLE
Saturation potion (all three types) don't work.

### ISSUE THREAD

**Issue by Ecthelon** [Lothrazar/Cyclic#1188]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2825

Mod Version: 1.12.2-1.18.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Drank saturation potion. It should give me saturation. It did nothing. I've found others discussing this issue online. This includes the splash and lingering versions.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Yep can confirm bug is real.

Somehow, the potion does trigger correctly in Pharos Beacon

**Comment by Timeslice42** [comment]
This is still an issue. ><

**Comment by Lothrazar** [comment]
This item still works in the Pharos beacon it gives all players real saturation, no idea whats up with it not working normally.  every other potion effect is fine except this special one

**Comment by Timeslice42** [comment]
Maybe because, unlike the other potion effects, the vanilla saturation effect is actually specified in ticks, not seconds.

Or, wait, it looks like the potion isn't applying the vanilla saturation effect. Is there a reason for that?

**Comment by Timeslice42** [comment]
I did some testing, and I have no idea. If I use the command ``/effect @p 23 3600`` then it works as expected. However, if I make a custom potion with ``/give timeslice minecraft:potion 1 0 {CustomPotionEffects:[{Id:23b,Ambient:0b,Amplifier:0b,Duration:3600,ShowIcon:1b,ShowParticles:1b}],Potion:"cyclicmagic:saturation"}`` then it doesn't work.
Changing the Id to 16 (night vision) works as expected.

Looking through old Mojang issues, it looks like saturation has never worked as a potion effect. If Emoniph was still around they could tell you how the Witchery saturation potion works, but that's not possible.
I do know that if you add the effect directly to the player's ActiveEffects NBT entry then the saturation works fine.

**Comment by Timeslice42** [comment]
FYI, https://bugs.mojang.com/browse/MC-169197
