### ISSUE TITLE
Tooltips Render Below JEI

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1190]
Minecraft v1.12.2
Forge v14.23.5.2838
Cyclic v1.19.12
Singleplayer

In the Merchant Almanac GUI, the tooltips of items tend to render below JEI items instead of above.

![2019-07-23_18 53 56](https://user-images.githubusercontent.com/12000593/61755355-d0138180-ad7c-11e9-87e1-41ce78e72de0.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
