### ISSUE TITLE
Player launcher 

### ISSUE THREAD

**Issue by avidgamer5918** [Lothrazar/Cyclic#1191]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.12.2-1.19.12

Single Player or Server: server

Describe problem (what you were doing; what happened; what should have happened):
When Using a player launcher in combination with the slime sling from tinkers Construct you can travel thousands of blocks in a second.  

Video/images/gifs (direct upload or link): https://www.twitch.tv/videos/458089294

**Comment by Lothrazar** [comment]
Yep, this is working as intended.  Both items MULTIPLY some numbers , so both together is just crazy.   I dont even know what I would change, just dont use both at once LOL. Its like using two jetpacks at once
