### ISSUE TITLE
Fluid Extraction Cable removes water source blocks when full

### ISSUE THREAD

**Issue by TherminatorX** [Lothrazar/Cyclic#1192]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.11

Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
What it says on the tin. Other water gens in the pack weren't cutting it, so I decided to use the FEC to pick up infinite water sources instead.
What happened: the water pickup action doesn't stop after the tank I was using and the pipes are full, causing particles, sound effects, and water flowing physics to constantly happen.
Expected behavior: once everything is full, the FEC would stop trying to pick up the regenerating source blocks and the noise/flowing water would stop.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2755366

**Comment by TherminatorX** [comment]
Been a hot minute since I paid attention to my water setup, but using version 1.19.17 in MC 1.12.2 and I still have this issue happening.

Pic of water gen setup, happens even when the drum is removed so it's not an issue with the other mod's tank methods
![image](https://user-images.githubusercontent.com/7256249/67719970-dc713100-f9a0-11e9-8aa4-d2efb016e6ef.png)

**Comment by TherminatorX** [comment]
@Lothrazar Updated to 1.19.18, issue still present.
