### ISSUE TITLE
Automated User Null Pointer

### ISSUE THREAD

**Issue by lukyky414** [Lothrazar/Cyclic#1195]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831 
Server Sky Factory 4 v4.0.5

Mod Version: 1.19.8

Describe problem:
To make salt, you need to Right Click a Cauldron with Sand.
If the automated user is empty and try to right click (wich is every game tick if you didn't configure it), you get a null pointer exception. (maybe if the cauldron is empty too but I'm not sure).
If you have null pointer exception 20x per second, the server begin to lag.
Should be easy to fix, if inventory is empty, do not right click.

A second bug (I will make an other issue) force me to use slightly often than provide item (item every 60tick, use at most 59 tick). So I will get NullPointer every time.

Error:
[https://pastebin.com/e8bz2nws](https://pastebin.com/e8bz2nws)

**Comment by AAlphaDEV** [comment]
Same problem here with a Skyfactory 4 modpack server. This issue forces server to crash after a few minutes.

**Comment by Lothrazar** [comment]
Reference to 1.19.8 tag version https://github.com/Lothrazar/Cyclic/blob/e24e27fb3e5fea4087e7d97582eb36ed2d8789a3/src/main/java/com/lothrazar/cyclicmagic/block/autouser/TileEntityUser.java#L257

**Comment by Lothrazar** [comment]
I can do a small part on my side, but I think triumph my have some change to do as well in case of fake players 

java.lang.NullPointerException: null
    at com.bloodnbonesgaming.triumph.advancements.criterion.trigger.RightClickBlockTrigger$Instance.test(RightClickBlockTrigger.java:191) ~[RightClickBlockTrigger$Instance.class:?]

**Comment by Lothrazar** [comment]
Cross posted https://bitbucket.org/bloodnbonesgaming/triumph/issues/28/possible-crash-from-fake-player
