### ISSUE TITLE
Bug: Block Reach enchantment is broken in Roguelike Adventures and Dungeons modpack

### ISSUE THREAD

**Issue by Yossarian3217** [Lothrazar/Cyclic#1197]
Minecraft Version: 1.12.2

Forge Version: 1.12.2

Mod Version: 1.19.12

Single Player or Server: Singleplayer (internal server)

Describe problem (what you were doing; what happened; what should have happened):
I enchanted my chestplate with the block reach enchantment and then I wasn't able to destroy blocks. Weirdly enough, I could break sand with a shovel and harvest crops, but I couldnt break anything else with any other tool.

**Comment by Lothrazar** [comment]
Are you in a modpack? or do you have a mod list? For me it works fine by itself, so i have to assume some other mod is messingw ith similar data 

![1197](https://user-images.githubusercontent.com/621529/62441318-6abe7980-b708-11e9-97d6-fb18ad02841f.gif)

**Comment by cowdouble** [comment]
Same issue identified, Using the Roguelike Adventures and Dungeons modpack with the twitch launcher, seems to affect block damage progression, one hit breakable blocks can be broken, such as grass or glowstone, but for other blocks, first breaking animation frame plays then returns to regular block, despite holding down mouse button.
Hope this helps.

**Comment by jahmyrr** [comment]
Confirm and reiterate what cowdouble says.  Roguelike Adventures and Dungeons w/ Block Reach wont allow blocks to be broken.  If you take off the chest plate with the enchantment, blocks break as normal.  Tested trying to break blocks with different tools (modded and standard) from different distances.

**Comment by TDGBullDog** [comment]
Confirmed here as well. Roguelike Adventures and Dungeons Version: 1.31 Minecraft Version: 1.12.2.

**Comment by MrAlexand0r** [comment]
I have the same problem with Roguelike Adventures and Dungeons

**Comment by cheshyrp** [comment]
Same problem here with Roguelike Adventures and Dungeons. I don't know if the bug is related to the mod pack, or Minecraft 1.12.2 in general, but it is a nasty one. I wasted a long time trying to "fix" my broken character before I realized it was an enchanted piece of armor causing the issue.

**Comment by cheshyrp** [comment]
Lothrazar, please remove the "cannot replicate" tag as it's a blatant lie. Download Roguelike Adventurse & Dungeons modpack in Twitch, cheat in the Block Reach enchantment, and try to mine. You'll replicate it within 15 minutes.

**Comment by Lothrazar** [comment]
Something in the modpack is breaking it but i havent been able to nail down what it is sorry . works standalone and in other packs.

**Comment by Lothrazar** [comment]
Same root cause as https://github.com/Lothrazar/Cyclic/issues/1158, the Ice and Fire dragons mod https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons replaces some player data at some point, and cyclic relies on this player data for many things such as inventory upgrades, block reach, auto stepping, and various things
