### ISSUE TITLE
Automated User

### ISSUE THREAD

**Issue by HeberonYT** [Lothrazar/Cyclic#1198]
Minecraft Version: 1.12.2

I want to make a brief suggestion.
On a dedicated server, stability and resource use are very important, for that reason, it would be useful if blocks such as the “Automated user” can be configured in the configuration file of the mod, for example, to eliminate faster speeds in ticks and thus prevent the user from selecting a less than 20 ticks for example.

This allows the "clickmachine" mod to be done and thus avoid server-side delays.

    # The possible speeds of the auto clicker, from 0-8.  Must have 9 values. [default: [Ljava.lang.String;@52889dde]
    S:Speeds <
        500
        200
        100
        50
        20
        10
        5
        2
        1
     >

It would also be useful for the server administrator to limit the range of the machine.

**Comment by Lothrazar** [comment]
Right, this makes sense becuase in some modpacks going once per tick can cause issues with other machines.  Or just be overpowered for game balance.

Also for servers it could cause lag so disabling that would make sense.

If not a list of numbers, at least a max min makes sense

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
