### ISSUE TITLE
Cyclic + Inspirations: Harvester does not collect heartbeet from beetroot

### ISSUE THREAD

**Issue by Semenar** [Lothrazar/Cyclic#1201]
**Minecraft Version**: 1.12.2.

**Forge Version**: 14.23.5.2838.

**Mod Version**: 1.19.11.

**Single Player or Server:** Single Player.

**Describe problem** (what you were doing; what happened; what should have happened):
Placed harvester and planted beetroot in front of it. Provided harvester with power.
Expected behaviour: harvester collects beetroot, beetroot seeds and heartbeet (rare drop added by Inspirations).
Actual behaviour: harvester collects only beetroot and beetroot seeds.

This link might be useful: https://github.com/KnightMiner/Inspirations/issues/56

**Log file link**: no logs written during actual play.

**Video/images/gifs (direct upload or link)**: none needed, I believe.

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports
