### ISSUE TITLE
Controlled Miner not working (filters)

### ISSUE THREAD

**Issue by Roach009** [Lothrazar/Cyclic#1202]
Minecraft Version: 1.14.4
Forge Version: 14.23.5.28.31
Mod SkyFactory4 Version:  1.14.4
     Mod Version: 1.19.8
Single Player or Server:  Server

The control miner is not mining ResourceHogs truffles in a 13x13 area set to blacklist (the fence for the pigs and item cables).  Yet it will mine at the 9x9 setting with blacklisting and mine the 13x13 area set to whitelist the truffles.  The issue is that I have ten different truffles that need to be mined and there are only four slots for the miner's blacklist/whitelist without any type of upgrades.  This is all set up in a 13x13x13 compact machine.  I have used no pickax to even a diamond pickaxe with the same results.

**Comment by Lothrazar** [comment]
Can you explain this a bit mroe clearly? I have tried to set up similar tests. One side ignoring torches. one side set to only find truffles.   Both sides ignore truffles and mine things


![1202](https://user-images.githubusercontent.com/621529/63641615-0be48400-c666-11e9-9cf0-8ac1d01b513b.gif)

**Comment by Roach009** [comment]
Yes, let me tell you how I have it set up.  I have a 13x13x13 compact machine that I have placed the controlled miner on each floor against the outlet wall with a one high mining level and have it black listing fences.  Then I have the collector on the opposite wall.  I have fore resource hogs sitting on a 1x1 cube with fences around them.  I have this set up on four different floors inside the compact machine.  My goal is for the controlled miner to break only the truffles and the cyclic collector to ship them out using the Cyclic item cables.  Every time I set the controlled miner to 13x13 it will not mine the truffles.  Only on the 11x11 will it collect.  I was using the Cyclic power cables, but have changed to flux points thinking there isn’t enough power

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eHoward1996** [comment]
Can reproduce this effect in my Minecraft world as well. Will send pics of my setup tomorrow.

**Comment by Lothrazar** [comment]
oops had this mis-labelled as 1.14 instead of 1.12 moved it over

**Comment by Lothrazar** [comment]
Should work in latest versions; try reporting to modpack tracker itself
