### ISSUE TITLE
Bag of Holding Crash

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1203]
Minecraft v1.12.2
Forge v14.23.5.2838
Cyclic v1.19.14
[Curio](https://www.curseforge.com/minecraft/mc-mods/curio) v1.0.4
Single Player

Description:
I shift-right-clicked the Pedestal from Curio with the Empty Bag of Holding when I got this crash. I had a similar error, but no crash, after shift-right-clicking the Display Case from [Miniheads](https://www.curseforge.com/minecraft/mc-mods/miniheads),

Log file link:
[Crash Report](https://gist.github.com/WenXin20/b841f3f7444c232e506e8359f03922f3)
[Full Log](https://gist.github.com/WenXin20/159c3653a4c1fcf39622934b9680dced)

**Comment by Lothrazar** [comment]
I dont see if there is anything i can fix in my end. it does interact with the Pedestal but the log mentions  where curio can do a null pointer check


java.lang.NullPointerException
    **at com.denbukki.curio.tiles.TileEntityPedestal.baublesUpdate(TileEntityPedestal.java:136)
    at com.denbukki.curio.tiles.TileEntityPedestal.update(TileEntityPedestal.java:89)**

**Comment by WenXin20** [comment]
Alright, thanks. I went ahead and reported it to Curio.
