### ISSUE TITLE
Mining dynamite ignores FTB claims

### ISSUE THREAD

**Issue by bluelightning32** [Lothrazar/Cyclic#1204]
Minecraft Version: 1.12.2

Forge Version: forge-1.12.2-14.23.5.2836-universal.jar

Mod Version: Cyclic-1.12.2-1.19.12.jar

Sponge Version: spongeforge-1.12.2-2838-7.1.7-RC3785.jar

Modpack: Dungeons, Dragons, and Space Shuttles version 5.5a.

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
A player used mining dynamite on my server to steal from another player's base. They used mining dynamite to blow up the storage drawers inside the player's claim, then picked up the items off the ground.

Log file link: No relevant logs

Video/images/gifs (direct upload or link): 

This is what the player's base looked like before the dynamite:
![image](https://user-images.githubusercontent.com/21202621/62681730-38628580-b96f-11e9-903b-83b750f58799.png)

This is what it looked like afterwards:
![image](https://user-images.githubusercontent.com/21202621/62681748-40bac080-b96f-11e9-8304-7c7ccc12c2a5.png)

**Comment by ktole1999** [comment]
did he have permission to place the block?

**Comment by Lothrazar** [comment]
Ok.  How do i check claims, do they have an API or a suggested event i need to hook into?  I assume this FTB mod has some way of dealing with all the mods out there doing their own thing


Just to be clear its this one? https://www.curseforge.com/minecraft/mc-mods/ftb-utilities

**Comment by ktole1999** [comment]
im not a coder so not sure how to answer that question. if person was trusted in the claim then there is no bug. if person was not trusted then its an ftb util issue not a cyclic issue right?

**Comment by bluelightning32** [comment]
The player did not have permission through ftb.

**Comment by Lothrazar** [comment]
This mod does use the  net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate event, which does pass along the current entity, which has the "throwing player" stored as the ' Entity exploder;'

So i suggest any mods implementing a permission type system check this event for explosions.

There should be everything they need already provided (see link below) But to assist i will add a public 'getter' function on this private variable in case that helps 

https://github.com/Lothrazar/Cyclic/blob/6f402c4c3e7d779b00a7dd1932fb99e6ab3d15d4/src/main/java/com/lothrazar/cyclicmagic/item/dynamite/ExplosionMining.java#L145

**Comment by Lothrazar** [comment]
Adding a hook to 

ExplosionEvent.Start 

Before exploding to allow cancellation of explosion which will prevent it
