### ISSUE TITLE
Weapon balance

### ISSUE THREAD

**Issue by Temenat** [Lothrazar/Cyclic#1205]
Minecraft Version: 1.12.2

Forge Version :.2838

Mod Version: 1.19.13

Single Player or Server: Single player

Describe problem (what you were doing; what happened; what should have happened):
I don't think mattock is supposed to be better than a Crystallized Obsidian sword, especially considering the low cost of it. It does 7.5 damage and it's speed is almost double the speed of a sword, which makes it a weapon with a DPS of 22.5 in contrast to the DPS of 16 of a crystal obsidian sword. With sharpness the gap is increased:  the Mattock has a DPS of 31.5 and the sword only 20.8(less than base mattock) with sharpness V applied. 
I think you should fix it by simply giving the mattock a speed similiar to an axe, even less considering how cheap it is to produce and the fact that it's already extremely useful for digging.
Some of the magic staves/wands are also a bit too powerful IMO, as they are incredibly durable, cheap, and can do a lot of damage, so I think you should greatly reduce their durability and maybe their damage too. I'm talking of the evoker fang,  snowballs and spirit staves in particular, but lightning and dark fire are also very powerful, so I'd consider a durability tweak on them too.
The multi shot enchantment needs to be reworked too, as it's arrows don't travel far and it gives the bow an absurd amount of damage if spamming harming 2 arrows. I would honestly consider removing it.
Charms are way too powerful, as they are too cheap and durable and you can have them all active at once: I tried air(which I think could directly give creative flight instead of it's weird flight mechanic) and something like 10 speed charms toghether, I could travel thousands of blocks in no time XD. They would be very cool in form of(VERY EXPENSIVE) single armor upgrades or enchantments, so you could have a maximum of 4 active charms. I love the Void charm mechanic anyway :)
It also appears the nether and end ores aren't compatibile with mods that add machinery for automatic ore excavation such as Industrial Foregoing's laser drill and Environmental Tech's miner. This is weird since other mods that add nether and end ores usually have them added
automatically(maybe the ores from this mod are not added to Ore Dictionary, while the ores from other mods are, I don't know how it works anyway).
I hope you'll consider my suggestions, thanks for making this great mod anyway, I love the useful stuff it adds :)

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
ok yeah the mattok should not do fat combat damage , thats one item

**Comment by Lothrazar** [comment]
a lot of this would be good fodder for 1.14 remake.  people are so used to 1.12 how it is would be jarring for such a change. lots of it makes sense tho
