### ISSUE TITLE
block miner + sticky piston crashes server.

### ISSUE THREAD

**Issue by nodeSpace** [Lothrazar/Cyclic#1206]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.13

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Trying to move the block miner with a sticky piston causes the server to crash.
Seems to be reproducible every time. 

Log file link: Not the owner of the server so I don't have it.

**Comment by xerberus333** [comment]
Hi there.
Was curious about this and tried to recreate it. Sure enough, it's a consistent crash. Placing the redstone signal source on the block miner seems to produce a crash all the same.
Meaning:
use a signal on piston = crash
use a signal on block miner = crash

Upon reloading the save, the block miner becomes missing, replaced with a permanently darkened spot. It's not invisible, it's just gone, meaning there's no collision, you can place a new block there, etc. But a darkened spot remains, as shown below:
https://imgur.com/a/ZcQHSUV

Here's my log. Hope it helps:
https://pastebin.com/tb1jbxJW

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
