### ISSUE TITLE
Multi-jump works wrong with certain boots

### ISSUE THREAD

**Issue by Dachius** [Lothrazar/Cyclic#1207]
Minecraft Version: ATM3 (1.12.2)

Forge Version: 14.23.5.2825

Mod Version: 1.18.5

Single Player or Server: Singleplayer

**Describe problem (what you were doing; what happened; what should have happened):**

I am using some wyvern boots with multi-jump 4 on them. I am able to use a supposedly random number of mid-air jumps >= 4. I have observed between 4 and 24. 

The issue appears to persist for other levels of multi-jump and on Draconic boots.

**Comment by Lothrazar** [comment]
This enchant uses the standard built in 'cooldown' system on the item to stop the jumps. if other modded boots use the cooldown system on their own there isnt really an easy work around.  Content still works just a bit of a weird overlap :)
