### ISSUE TITLE
My game crashed when using cyclic frostbolt wand (when hit water?), and it makes an aweful noise when i use it.

### ISSUE THREAD

**Issue by uraniumcrystalsmaster** [Lothrazar/Cyclic#1209]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2831

Mod Version: 1.12.2-1.19.14

Single Player or Server: Single Player

Problem:
I was fighting the snow queen from twilight forest and my game crashed soon after I used the wand. For some reason my computer was acting worse than usual (mouse movements were choppy, my frame rate was 32, and mob damage took a second to register), and I had restarted the computer to try to fix this issue, but nothing happened. Soon after it crashed, I opened the game again and same problem. I really want to able to play my modpack, and if it requires removing the item go ahead. Also, the sound of this wand is extremely annoying. Can you change the sound, lower the volume, or equalize the sound. 

Log file link: https://paste.dimdev.org/akuricihag.mccrash

**Comment by Lothrazar** [comment]
Something happened when it hit water

    at com.lothrazar.cyclicmagic.item.snowmagic.EntitySnowballBolt.onHitWater(EntitySnowballBolt.java:171)
    at com.lothrazar.cyclicmagic.item.snowmagic.EntitySnowballBolt.processImpact(EntitySnowballBolt.java:95)

And ill see about turning the volume down a tad i guess

**Comment by uraniumcrystalsmaster** [comment]
Thank you a lot!
