### ISSUE TITLE
Armor and toughness bar disabling

### ISSUE THREAD

**Issue by Smartaros** [Lothrazar/Cyclic#1211]
it would be nice to be disable this so that I can use other mods
![12](https://user-images.githubusercontent.com/26225365/63207949-0ff92a80-c0d7-11e9-9f5c-0240a90f8536.png)

**Comment by Lothrazar** [comment]
What mods are you using? I didnt think i had any code touching the armor bar

**Comment by Tfarcenim** [comment]
that looks like rustic, disable it in their config
