### ISSUE TITLE
Piston Sceptor Can (Still) move protected blocks

### ISSUE THREAD

**Issue by FallenEagle1** [Lothrazar/Cyclic#1212]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.14
FTBU 5.4.0.100

Single Player or Server: Server

When in a claimed chunk (ftbutilities) a player can bypass the claims system with the piston scepter and use it to move any blocks in the claimed chunks

**Comment by Lothrazar** [comment]
Adding a check to call EntityPlayer : 
    public boolean canPlayerEdit(BlockPos pos, EnumFacing facing, ItemStack stack) 

to make sure player is allowed
