### ISSUE TITLE
Item Collector freezes game upon shift clicking item into player inventory.

### ISSUE THREAD

**Issue by TheDarkPreacher** [Lothrazar/Cyclic#1213]
Minecraft Version: 1.14.4

Forge Version: 28.0.45

Mod Version: Cyclic-1.14.4-0.0.2

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened): Shift clicked item out of Item Collector, game froze, should have taken item from Item Collector and placed in inventory.

Log file link: No log output in game output, no crash log produced. Tested in both survival and creative mode. Forced closed, got `Process crashed with exit code -805306369` in game output log.

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2765041
