### ISSUE TITLE
[1.14.4] Shift clicking into collected locks up minecraft

### ISSUE THREAD

**Issue by darkphan** [Lothrazar/Cyclic#1214]
Minecraft Version: 1.14.4

Forge Version: 28.0.45

Mod Version: 1.14.4-0.0.2

Single Player or Server: Single player

Accidentally shift clicked an item into the collector while in it's inventory and it locked up Minecraft, causing it to not respond.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2765041
