### ISSUE TITLE
Fatally missing registry value

### ISSUE THREAD

**Issue by Dandei** [Lothrazar/Cyclic#1215]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.14

Single Player or Server: Single player LAN server. 

Describe problem (what you were doing; what happened; what should have happened): Friend and I have the same mod pack. Everything works fine and is compatible. Except when we add the newest version of Cyclic. It gives my friend the error of "Fatally missing registry values". No clue how to fix. Any help would be appreciated. 

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
do you have a full mod list, or link to modpack

**Comment by Lothrazar** [comment]
stale; old version; and cannot replicate
