### ISSUE TITLE
Clumps and Experience Boost doesn't play very well

### ISSUE THREAD

**Issue by artubi** [Lothrazar/Cyclic#1217]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2838
Mod Version: 
Cyclic-1.12.2-1.19.13
Single Player or Server:
Single player
Describe problem (what you were doing; what happened; what should have happened):
When using Experience Boost while Clumps mod is present, in some situations it leads into issue just like #421 , that player is still capable of getting XP that "doesn't exist". In my findings, this mostly affects mob farms since it happening only in spots where most mobs are killed. XP is still present and can be collected in the "blocks" where mobs were killed even though F3 screen reports no entities. Reloging will cause massive lag as all the XP is spawned.
https://i.imgur.com/w0umhhS.jpg
Trying to kill all entities will kill only visible XP orbs, but most of them will be "still there/invisible", even though entity count doesn't report them.

Steps to reproduce in smaller scale:

Mods used: 
Cyclic-1.12.2-1.19.13
Clumps-3.1.2

1. Build this mob farm https://i.imgur.com/TUywOdZ.jpg
2. Enchant sword with Experience Boost 3
3. Increase RandomTickSpeed to something like 10000 - 50000 to get steady line of zombie pigmen.
4. Stand behind the cobblestone wall, aggro the zombie pigmen and start slaying them
5. Do it for few minutes
6. Revert RandomTickSpeed to small numbers to stop pigmen from spawning
7. Step on the blocks/hoppers behind the cobblestone wall
8. After getting all visible XP drops, you should start getting XP out of nowhere only in these two spots and F3 screen shows no entities

This doesn't happen when Clumps mod is not present and removing it will cease this issue to exist.

**Comment by Lothrazar** [comment]
the boost enchant just adds more XP orbs to the world, just copies of teh same entity. im not sure about clumps, i think it just joins them together?

**Comment by jaredlll08** [comment]
My guess is your issue is the "setPositionAndUpdate" over here
https://github.com/Lothrazar/Cyclic/blob/develop/src/main/java/com/lothrazar/cyclicmagic/enchant/EnchantXpBoost.java#L116

Why not just use the parameter constructor that lets you set all of that?

```java
public EntityXPOrb(World worldIn, double x, double y, double z, int expValue)
```

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2769179
