### ISSUE TITLE
Punching fan destroys it instantly 1.14.4

### ISSUE THREAD

**Issue by Yamza** [Lothrazar/Cyclic#1219]
Minecraft Version: 
1.14.4
Forge Version: 
28.0.55
Mod Version: 
1.14.4-0.0.5
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
Punching a fan with an empty hand deletes it in a single hit.

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
yes, it has that issue.  Looks like this is fixed in 0.0.7
