### ISSUE TITLE
Pattern Replicator drops redstone dust if placed before supporting block.

### ISSUE THREAD

**Issue by IMarvinTPA** [Lothrazar/Cyclic#1220]
Minecraft Version:  1.12.2

Forge Version: 2838

Mod Version:  1.19.14

Single Player or Server:  SP, but probably both.

Describe problem (what you were doing; what happened; what should have happened):

I was trying to make Compact Machine Walls using a Pattern Replicator and the redstone gets placed before the iron block, causing it to pop out of the air into an item.  (The pattern is redstone dust placed on an iron block in the Miniaturization field. )

Log file link: N/A

Video/images/gifs (direct upload or link):   N/A

----
The Pattern Replicator needs to not place redstone or other attached items until the supporting block has been place.  If possible, an option to build from the bottom up instead of randomly would be enough.

Thanks.

**Comment by Lothrazar** [comment]
can you make a few screenshots of what its building?

**Comment by IMarvinTPA** [comment]
I'm trying to copy the iron block and redstone dust on top of it.
![2019-08-24_21 02 51](https://user-images.githubusercontent.com/4486117/63644249-ad91c280-c6b2-11e9-96f1-ef3d417ea8a1.png)

**Comment by IMarvinTPA** [comment]
Example of a miss:
![2019-08-24_21 07 28](https://user-images.githubusercontent.com/4486117/63644271-3a3c8080-c6b3-11e9-8e8e-0895131dc9a5.png)
There are two redstone on the ground because the dropper tossed one onto the one that got placed before the iron block.
