### ISSUE TITLE
Further Compat for Enchantment Descriptions

### ISSUE THREAD

**Issue by bloodconfetti** [Lothrazar/Cyclic#1222]
Minecraft Version: 1.14.4

Forge Version: 28.0.56

Mod Version: Cyclic-1.14.4-0.0.9
Mod Compatibility With: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

Single Player or Server: Single

Describe request: 
When you have the time, and if you have the desire, I am very interested in seeing more of your enchantments included in the Enchantment Descriptions mod, thank you!!

![2019-08-29_10 23 43](https://user-images.githubusercontent.com/53692357/63958195-23958100-ca47-11e9-8bff-28f31e49ab21.png)

**Comment by Lothrazar** [comment]
oops :D
