### ISSUE TITLE
Corrupted Chorus Fruit allows teleportation

### ISSUE THREAD

**Issue by shinji257** [Lothrazar/Cyclic#1223]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Mod Version: 1.19.15
Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
When using the Corrupted Chorus Fruit it is possible to access the spectator menu after spamming Shift +1 or Space +1 (works better with the latter).  Once the menu is up you can teleport to any player on the server.

Log file link:

Video/images/gifs (direct upload or link):

**Comment by Lothrazar** [comment]
has been marked as 'cannot replicate' for a long time with no updates; closing to clean up tracker
