### ISSUE TITLE
Nether Ore Drops Nuggets

### ISSUE THREAD

**Issue by moiucihdaa** [Lothrazar/Cyclic#1226]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2825

Mod Version: 1.18.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Hello!  I'm a bit confused why nether ore drops nuggets instead of whole ore.  Is this something configurable in the config or something permanently changed by the mod?  I've read through the other issues and saw that you had mentioned increasing spawn rate of the ore BECAUSE it only gave nuggets but couldn't find an explanation as to why it only gave nuggets.  

Thanks in advanced!

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by FallenEagle1** [comment]
Curious about this as well, looking into options dealing with nether ores for modpacks (atm 3 remix at the moment, but for others as well)

**Comment by Lothrazar** [comment]
This is working as intended, you can Smelt in furnace for ingot using silk touch. or change drops with crafttweaker etc etc :D

**Comment by FallenEagle1** [comment]
It may be working as intended, but personally don't like it, so some config options would be nice. For now they will just be disabled and a different mods ores will be used.
