### ISSUE TITLE
Cant make temped glass 

### ISSUE THREAD

**Issue by IchigoGames** [Lothrazar/Cyclic#1227]
Minecraft Version: 1.14.4

Forge Version: 28.0.93-any

Mod Version: Cyclic-1.14.4-0.0.10

Single Player or Server: both 

Describe problem (what you were doing; what happened; what should have happened):
Cant Craft Tempered glass when you have ironchest-1.14.4-9.0.4
![2019-09-07_00 07 53](https://user-images.githubusercontent.com/11888162/64470134-aa132800-d103-11e9-8ac4-5b615e0fbcc3.png)

**Comment by Lothrazar** [comment]
ill just move obsidian to a different spot in the recipe
