### ISSUE TITLE
Garden Scythe Compat w/ Pizzacraft

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1228]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Cyclic Version: 1.19.16

Pizzacraft Version: 2.0.16.16

Describe problem: 
- Currently, the Garden Scythe will not harvest any crops from Pizzacraft, except for corn. 
- Corn is being harvested, but it is a two-block-tall crop, so the scythe harvest both the top and bottom of the crop, which leaves the top block floating.

**Comment by Lothrazar** [comment]
All harvested items are exposed as a data pack, so in a wold you can add your own 

https://github.com/Lothrazar/Cyclic/tree/up114/src/main/resources/data/cyclic/tags/blocks


Also, yes i will slowly update these defaults with more mods i have to collect some ID tags of all the items first

**Comment by WenXin20** [comment]
I don't think Datapacks are in 1.12.2, are they? Pizzacraft is for 1.12.2.

**Comment by Lothrazar** [comment]
oh i misread that

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
