### ISSUE TITLE
Glowing Chorus Fruit Causing Invincibility, Untargetability

### ISSUE THREAD

**Issue by Aetheo** [Lothrazar/Cyclic#1229]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.12

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

Under unknown circumstances, the glowing chorus fruit causes the player to be unable to take damage from any source (Tested: lava, fire, other players, falling, starving, void, explosions, mobs, projectiles[dispenser], drowning) or go through portals. When the flight counter runs out, normal damage mechanics resume with no catchup. Unknown cause but replicated by accident on 2 singleplayer worlds and in multiplayer. Things in common: Fire Charm (removed, does not stop this), Botania ring of magnetization (Same thing) Heart Amulet (Baubley Heart Canisters [Varying amounts inside, same removal process as the others])

Log file link: No crashes or Cyclic mentions in logs (outside the mod list)- I can produce but am unsure if this would be helpful.

Edit: Specifically occurs when dying with flight time but without flight active

**Comment by Lothrazar** [comment]
Tested this various different ways. including having 5+ mins of flight left but both with and without flight active, dying multiple times. creepers skeletons lava etc still kill me

**Comment by Lothrazar** [comment]
has been marked as 'cannot replicate' for a long time with no updates; closing to clean up tracker
