### ISSUE TITLE
Stacking of non stackable items and item duplication

### ISSUE THREAD

**Issue by dr4ds** [Lothrazar/Cyclic#1230]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2768

Mod Version: 1.19.16

Single Player or Server: both 

Video/images/gifs (direct upload or link): 
https://youtu.be/y6UV11_DhEQ

Works with block placer and structure builder

**Comment by Lothrazar** [comment]
I can lock it down to not open unless stack size is 1. stack merging is another can of worms to get into later

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2798325 i sitll have ot go further in the future and changes how the machines move items
