### ISSUE TITLE
Storage Bag nesting

### ISSUE THREAD

**Issue by dr4ds** [Lothrazar/Cyclic#1231]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2768

Mod Version: 1.19.16

Single Player or Server: both

Describe problem (what you were doing; what happened; what should have happened):
Storage Bag auto pick up funtion is not checking whether item being picked up is another bag.

Video/images/gifs (direct upload or link): 
https://youtu.be/CYz0Nzhz5jU

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2798325

**Comment by Lothrazar** [comment]
If it fails or new issue come back anytime
