### ISSUE TITLE
[Minor] Non-localized name for "Player was slain by cyclicmagic.fake_player.spikes!"

### ISSUE THREAD

**Issue by katubug** [Lothrazar/Cyclic#1235]
**Minecraft Version**: 1.12.2

**Forge Version**: 2846 (server), 2838 (singleplayer)

**Mod Version**: 1.19.16

**Single Player or Server**: both

**Describe problem (what you were doing; what happened; what should have happened):**
It's so minor I almost hate to report it, but I figured it'd at least be an easy fix. When a player is killed by the Diamond Spikes, it prints to the chatlog "Katubug was slain by cyclicmagic.fake_player.spikes!"

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2798325
