### ISSUE TITLE
When removing mob spawner from the blacklist on the Exchange Scepter I am still unable to pick up spawners. 

### ISSUE THREAD

**Issue by nnytak** [Lothrazar/Cyclic#1238]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.15

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
In the configs I removed the mob spawner form the blacklist. This should have let me use the wand on the spawner. Instead, I am still unable to use the wand on it.

**Comment by Lothrazar** [comment]
Sadly this is working as intended, it doesnt use 'silk touch' or anything to pick up, it just mines the block normally.  Sack of holding can pick up a spawner

**Comment by nnytak** [comment]
> Sadly this is working as intended, it doesnt use 'silk touch' or anything to pick up, it just mines the block normally. Sack of holding can pick up a spawner

ah, okay. weird that it's blacklisted if it can't actually be interacted with haha.
