### ISSUE TITLE
[1.12.2] Block Reach Enchantment oddity.

### ISSUE THREAD

**Issue by Z-Tunic** [Lothrazar/Cyclic#1241]
I'm aware that there were already reports of this bug before where you can only mine the block for a split second before it stops mining if you have this enchantment on your armor. I've pinned it down to these mods here...

Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 4
Cyclic-1.12.2-1.19.17
jei_1.12.2-4.15.0.279
PotionCore-1.7_for_1.12.2
QualityTools-1.0.7_for_1.12.2

-----

Potion Core makes use of the "generic.reachDistance" attribute which checks of how far of a reach you'll get with attacking, mining blocks, etc. However... if Cyclic is added alongside Potion Core then the Block Reach Enchantment breaks where you're unable to fully mine blocks unless your Mining Speed is fast to instant-break the block if equipped.

I've also tested Aether Legacy since you'll have access to Valkyrie Tools which have an Extra Reach Distance alongside Cyclic and apparently the Valkyrie Tools Extra Reach Distance breaks if you equip & unequip a Block Reach Enchantment while holding the tool... although you can still somehow attack mobs from a distance with the Valkyrie Tool but the mining distance is as if it was at the default range, only way to fix this is to re-log into the world.

Using Aether Legacy & Potion Core together... the "generic.reachDistance" stacks on top of the Valkyire Tool's Extra Reach Distance, thus allowing you to reach out further than before.

-----

Would it be possible to have the Block Reach Enchantment make use of the "generic.reachDistance" attribute? That should make it compatible with other mods that use that attribute so it'll stack with other "generic.reachDistance" attributes. I'm not sure of the Attribute value but I see that the Block Reach Enchantment extends to an extra 11-12 Blocks from the default range so I think it would be...

amount: '11.0' OR '12.0', operation: 0

...unless I got the values wrong or something, just making a rough guess of the distance.

**Comment by Lothrazar** [comment]
using "generic.reachDistance"  would be more compatible with other mods and such, and doesnt sound too impossible to implement it.  

Similar to hearts, it could instead of forcing a fixed value just increment whats there.  Ill have to research

**Comment by Lothrazar** [comment]
1.12 also uses that property "generic.reachDIstance".  but there is a few bits of code related to NetHandlerPlayClient that i will refactor or remove 

https://github.com/Lothrazar/Cyclic/blob/dc34e1a80479b3916f4fe4714c56d8a97ad605d5/src/main/java/com/lothrazar/cyclicmagic/proxy/CommonProxy.java#L84
