### ISSUE TITLE
Inventory Crafting Table disconnects player upon opening.

### ISSUE THREAD

**Issue by Pikablu42** [Lothrazar/Cyclic#1242]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: SkyFactory 4 v4.0.8 (Twitch Launcher)

Cyclic version: 1.19.11

Single Player or Server: Client side disconnect from server; works fine in single player worlds.

Describe problem (what you were doing; what happened; what should have happened):
Related to #624
Upon opening the inventory crafting table, every time, the client is disconnected from the server with an error screen reading:
"Connection Lost"
"A fatal error has occurred, this connection is terminated". The player can reconnect to the server, as the crash does not crash the server or client.
No crash log was attainable.

(Extra Info: Haven't tested on any other servers yet, but I am experiencing this on the Minewonderland server. A staff member has told me they know about the bug, and it "sometimes can crash clients (depends on client hardware)". Will attempt testing on an alternative computer later.
Also similar to #624, the inventory upgrade works fine. 
When tested in a single player world, including a LAN server with no other players, crafting worked fine both in the inventory and normal crafting methods. On the server, the Advancements tab disappears, followed by the 3x3 grid appearing in place of the 2x2, followed by an immediate disconnect to the error screen. I can then reconnect to the server via the normal means.)

**Comment by Lothrazar** [comment]
Sorry this is still a complete mystery if therse no crash logs or anything.  Ive played on and also watched SF4 server playthroughs with no issues, very strange.

non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports
