### ISSUE TITLE
[1.14.4] Energy cables and batteries don't drop when broken and lack hardness.

### ISSUE THREAD

**Issue by ProsperCraft** [Lothrazar/Cyclic#1244]
Minecraft Version: 1.14.4

Forge Version: forge-1.14.4-28.1.26

Mod Version: Cyclic-1.14.4-0.0.12

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
if you touch a cyclic cable with your bare hand it disappears and doesn't drop, same with a pick.
This is a common problem for mods porting to 1.14 as the loot tables changed in forge.

**Comment by riatzukiza** [comment]
I  have also encountered this problem

**Comment by jjcurry812** [comment]
Was this fixed?  I'm also having this problem.  Breaking Energy cable voids the cable instead of dropping it.
Minecraft 1.14.4
Forge 28.1.109
Cyclic 1.14.4 - 0.0.12

**Comment by Lothrazar** [comment]
Yep newer versions have a fix @jjcurry812
