### ISSUE TITLE
Certain Blocks Render Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1246]
Minecraft v1.14.4
Forge v28.1.44
Cyclic v0.0.12

Describe the problem:
- Placing Energy Cables, Iron Spikes, Tempered Glass, Fans, Trash Voids, Item Collectors, Scaffolding & Block Breakers render incorrectly when placed underwater.
- Allowing these blocks to be waterlogged should fix most of the blocks.

Image: 
![2019-10-11_21 41 27](https://user-images.githubusercontent.com/12000593/66693568-e8a28200-ec6f-11e9-91d7-a5f51c5a825d.png)

**Comment by WenXin20** [comment]
Also discovered recently that the Tempered Glass will display inner seams when multiple glass blocks are placed next to each other.

**Comment by Lothrazar** [comment]
Yes these blocks dont get the waterlogged state in 1.14 :(
