### ISSUE TITLE
[Suggestion] Add a Mob Spawner system

### ISSUE THREAD

**Issue by Simba98** [Lothrazar/Cyclic#1247]
What if add some items / blocks for auto mob spawning and kill them, like Stabilized Mob Spawner in Draconic Evolution, or some other mods?
Or add a machine, you can input a Monster ball, then the machine spawn mob which is same as what was catched in the Monster ball.

Thanks for your patient.

**Comment by Lothrazar** [comment]
Ill keep this in mind for any new mods that i make, seems too overpowered for cyclic
