### ISSUE TITLE
[Suggestion] Fine tuning numerical range in config

### ISSUE THREAD

**Issue by djwoozie** [Lothrazar/Cyclic#1248]
Minecraft Version: 12.1.2

Forge Version: 14.28.5.2836

Mod Version: 1.19.9

Single Player or Server: Server

Could the ability to have a decimal number for certain entries in the config be added? For example, in my server I want the penalty for using Ender Books really high but I can't set the ratio any lower than 1. I tried 0.34 since the range is 0-100 but it overwrites that when I start the server.

**Comment by Lothrazar** [comment]
so like making EnderBookExpCostRatio accept decimals?

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2821917
