### ISSUE TITLE
Mod compatibility issue regarding Tech Reborn's cells and Cyclic's Magma Anvil

### ISSUE THREAD

**Issue by bunnyman14** [Lothrazar/Cyclic#1249]
**Minecraft Version:** 
1.12.2
**Forge Version:** 
8.0.99.99 (that's what appears for Forge Mod Loader on the Mod Options tab)
**Mod Version:** 
1.19.17
**Single Player or Server:**
Single player
**Describe problem** (what you were doing; what happened; what should have happened):
**_Rapidly_** using a Lava Cell from Tech Reborn on a full Magma Anvil from Cyclic (or one that's above 9,001mb of lava) consumes extra Lava Cells without giving back empty cells and does NOT fill the Magma Anvil further. Likely a bug on Cyclic's part! I'll post this there as well!

**What is expected to happen:** Lava Cell is not consumed NOR anvil filled, in other words nothing should happen at all.
**Log file link:**
No log file

**Video/images/gifs (direct upload or link):** 
Hard to prove with images, and I have no programs that can make gifs

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by bunnyman14** [comment]
![2019-10-14_19 59 48](https://user-images.githubusercontent.com/7276888/66790374-64453e80-eebd-11e9-9b9d-ba72808b4323.png)
Best image to describe issue. 9900b of lava, the EXACT item I was attempting to repair (now fully repaired)

**Comment by bunnyman14** [comment]
**UPDATE:** I just had this happen to my Tinkers Smeltery. This may very well be on Tech Reborn's end instead (or Forge). Posting it there now (unless it's already reported)!

**Comment by Lothrazar** [comment]
Seems good on my end with any other fluid container as well :)
