### ISSUE TITLE
Custom Enchantments Conflict with MultiMine

### ISSUE THREAD

**Issue by PiordaNautor** [Lothrazar/Cyclic#1250]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: Cyclic-1.12.2-1.19.17.jar

Single Player

Description:
VanillaFix pinpoints a conflict between Cyclic and MultiMine when attempting to use a **weirdly enchanted** Pickaxe, while the block broken will not be mined. The Enchantments are as follows:
<details> 
Unbreaking IV
Silk Touch
Fortune V
Miner's Fervor VI
Excavation VII
Magnet XVI
Unbreaking VII
Efficiency VI
Miner's Fervor V
Unbreaking VII
Efficiency VI

</details> 

Log file link:
https://paste.dimdev.org/natotajeza.mccrash

**Comment by Lothrazar** [comment]
Is it because of silk touch + fortune together in one? Can you try without both and see if the bug is there. hmm

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
