### ISSUE TITLE
[Suggestion] Redstone clock device could use an "Auto Reset Delay" feature

### ISSUE THREAD

**Issue by ZTagre** [Lothrazar/Cyclic#1251]
Minecraft Version: 1.12.2+

Forge Version: 

Mod Version: 

Single Player or Server:

Describe problem (what you were doing; what happened; what should have happened):
With the Redstone Clock, it seems that (logically) the last "delay" countdown  in progress continues (if the setting value(s) remain the same) when any redstone signal is removed and then reinstated. However, this may not always be the desired mode of operation! Sometimes,  via automation processes, any redstone signal applied to the redstone clock is stopped and then started at known times / intervals, and the last "delay countdown" is no longer valid! A new countdown would instead be the desired situation. This would be the case when (for example) the RC was on a redstone control line from a vanilla MC daylight sensor or what-have-you.
   It would / could be beneficial to have a clickable box in the gui of the Redstone Clock that would provide a "continue delay from previous / restart delay" type of setting (you could label this something like "Auto-reset delay on signal loss?"). Or, if this label is too "wordy", then simply "Redstone RS" with a tooltip explanation...

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Working as intended for now. , trying to stabilize 1.12 without new features. will reconsider for 1.15+
