### ISSUE TITLE
Fluid Extraction Cables Resetting to Blacklist After Quitting and Reloading World

### ISSUE THREAD

**Issue by TherminatorX** [Lothrazar/Cyclic#1252]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Mod Version: 1.19.17
Single Player or Server: SP

Describe problem (what you were doing; what happened; what should have happened):
Whitelisted a specific fluid to prevent a draining others from a block with multiple (Nuclearcraft Fusion Reactor), upon reloading a world it now is blacklisting that desired fluid and pulled the wrong fluid into the cable instead, clogging the system.
This does not happen with item extractors.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2821917
