### ISSUE TITLE
Fluid extraction cable filter changing from whitelist to blacklist after world reload

### ISSUE THREAD

**Issue by Guodlca** [Lothrazar/Cyclic#1253]
Minecraft Version: 1.12.2

Forge Version: ForgeMultipart-1.12.2-2.6.1.81-universal.jar

Mod Version: Cyclic-1.12.2-1.19.11.jar

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
I am playing the Sky Factory 4 modpack. I have fluid extraction cables with a single whitelisted fluid in the filter, which works fine until I save and exit the world and reload it, after which all the filters are set back to blacklist, effectively halting all production until I change them all back to whitelist.

**Comment by TherminatorX** [comment]
Already posted about this with #1252

**Comment by Lothrazar** [comment]
Thanks; see https://github.com/Lothrazar/Cyclic/issues/1252 for fix and updates
