### ISSUE TITLE
Can't undo inventory crafting table (food) effect

### ISSUE THREAD

**Issue by Zosyn** [Lothrazar/Cyclic#1254]
Minecraft Version: 12.2

Forge Version: 

Mod Version: 

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):
I'd like to get rid of the option to have 3x3 crafting from my inventory, but I'm unable to undo the effects of the 'food' that created this effect. Tried turning it off in the configs, but nothing changed. How can I undo it?

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2821917
