### ISSUE TITLE
Fluid Extraction Cable - Collect Infinite XP from Infinite Liquid XP source

### ISSUE THREAD

**Issue by agrinder** [Lothrazar/Cyclic#1256]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.14

Single Player or Server: Singleplayer Creative

Describe problem (what you were doing; what happened; what should have happened):

Created an infinite XP liquid source from buckets, then used the Fluid Extraction Cable over the spot where the two XP liquid sources meet.

Log file link:

Video/images/gifs (direct upload or link): 
![2019-11-09_13 57 56](https://user-images.githubusercontent.com/5076207/68534346-3951dd00-02f9-11ea-85a4-6f3d30bd8f98.png)

**Comment by agrinder** [comment]
This occurs for Crystallized Obsidian Bucket too.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
