### ISSUE TITLE
[Suggestion] Mod compatibility for Solidifier

### ISSUE THREAD

**Issue by ReiDaTecnologia** [Lothrazar/Cyclic#1257]
_This is a suggestion so i deleted the template, if i'm wrong and i shouldn't delete it, tell me and i will fix it._

For exemple:
Thermal Expansion
250mb Gelid Cryotheum>Cryotheum Dust
250mb Blazing Pyrotheum>Pyrotheum Dust
250mb Zephyrean Aerotheum>Aerotheum Dust
250mb Tectonic Petrotheum>Petrotheum Dust

And maybe others.

**Comment by Lothrazar** [comment]
Looked into it a bit trying to add default support, but idont want to mess up existing modpacks.  Ill just leave it as is.

You can always add these recipes and any others with zenscript / crafttweaker

https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/scripts_zen_example/solid.zs#L4

**Comment by ReiDaTecnologia** [comment]
> Looked into it a bit trying to add default support, but idont want to mess up existing modpacks. Ill just leave it as is.
> 
> You can always add these recipes and any others with zenscript / crafttweaker
> 
> https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/scripts_zen_example/solid.zs#L4

 I understand, thx.
