### ISSUE TITLE
Item Transfer Node dupes items into Filing Cabinets

### ISSUE THREAD

**Issue by XerxezBreak** [Lothrazar/Cyclic#1259]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2838
Mod Version: 
1.19.14
Single Player or Server:
Single
Describe problem (what you were doing; what happened; what should have happened):
Using an Item Transfer Node with a GPS set into a Filing Cabinet with the appropriate Folder causes the item to not be transferred while the Filing Cabinet gains infinite copies of the Item.

Log file link:
No Log file

Video/images/gifs (direct upload or link): 
https://imgur.com/ztiYSNv
https://imgur.com/OvrF6o7
https://imgur.com/oh4RYWT
If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
