### ISSUE TITLE
Fluid Collector / Lava Dupe

### ISSUE THREAD

**Issue by valarnin** [Lothrazar/Cyclic#1261]
**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2847

**Mod Version:** 1.19.12

**Single Player or Server:** Server

**Describe problem (what you were doing; what happened; what should have happened):**

Fluid Collector pumps infinite lava without removing the source blocks. I checked change logs for versions 1.19.13-1.19.18 and didn't see anything that would indicate that this behavior has changed.

- Playing the Enigmatica 2 Expert pack, version 1.71
- World seed 4401043735229492804
- Overworld Coordinates X 102, Z 298
- All missing lava source blocks from screenshots below were removed by me
- Block under collector is a lava source block, block south of collector under trash can is flowing
- No missing lava source blocks underground
- Never consumes the cobblestone placed inside
- Has collected well over 5000 buckets of lava so far
- Might have something to do with there being an infinite water source at the SW corner of the collector's area? Just a guess
- Did not test with other fluids, so not sure if it's a lava-specific issue
- Can provide a world backup if needed, but zip size is 170mb

**Video/images/gifs (direct upload or link):**

![2019-11-24_11 31 17](https://user-images.githubusercontent.com/6119598/69497736-52888b00-0eae-11ea-88f5-ccadf89ee1fd.png)
![Screenshot from 2019-11-24 11-32-58](https://user-images.githubusercontent.com/6119598/69497738-56b4a880-0eae-11ea-883f-f6460f88c722.png)
![Screenshot from 2019-11-24 11-32-50](https://user-images.githubusercontent.com/6119598/69497739-56b4a880-0eae-11ea-808f-dc6fdc01487e.png)
![Screenshot from 2019-11-24 11-32-42](https://user-images.githubusercontent.com/6119598/69497740-56b4a880-0eae-11ea-9a0c-629ae317dbe4.png)
![Screenshot from 2019-11-24 11-32-00](https://user-images.githubusercontent.com/6119598/69497741-56b4a880-0eae-11ea-8c97-f6a961198f10.png)

**Comment by Frikkle** [comment]
Any news on this? :)

**Comment by TheJaysH** [comment]
Can confirm works for other fluids. 

Tested with pryothium, distablized redstone.

Same pack as you. (Non expert)

**Comment by Lothrazar** [comment]
Thanks for patience, fix coming soon

**Comment by Lothrazar** [comment]
Fixed and tested, let me know if its good enough please https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2883487

**Comment by Chessus** [comment]
Works now, just tested it on my world

Edit: Actually, Bibliocraft is buggered with .20

.19 fixes the problem
