### ISSUE TITLE
Another Console Spam Issue

### ISSUE THREAD

**Issue by JohnCorby** [Lothrazar/Cyclic#1265]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.14

Single Player or Server: Server (SkyFactory 4 - 4.1.0)

Describe problem (what you were doing; what happened; what should have happened):
Cyclic seems to randomly spam numbers to the server console.
I don't know what causes this or what the numbers mean.
Relevant config section if you care:
![image](https://user-images.githubusercontent.com/26337121/70381859-b37c7e00-1906-11ea-80ad-ee03bcc94b9b.png)
I don't think this is a duplicate, because I looked at other issues about console spam and none of them seem to spam in the same way my server does. 

Log file link: See image below

Video/images/gifs (direct upload or link): 
![image](https://user-images.githubusercontent.com/26337121/70381836-4ff25080-1906-11ea-8dc3-a56266b7307e.png)

Sorry for such little info. I just have no clue what causes this.

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
