### ISSUE TITLE
Issue: Guide Book Recipe 

### ISSUE THREAD

**Issue by Yourname942** [Lothrazar/Cyclic#1267]
Minecraft Version: 
    1.12.2

Forge Version: 
    forge-14.23.5.2847

Mod Version: 
    Cyclic-1.12.2-1.19.18.jar
    jei_1.12.2-4.15.0.291.jar

Single Player or Server: 
    Single Player

Describe problem (what you were doing; what happened; what should have happened):
    I start a new world. 
    I press E to view Just Enough Items. 
    I click in the search bar and type, "cyclic guide"
    I click on the guide book icon in  the JEI menu
 
    Issue:
        The guide book recipe does not show up

Log file link:
    [latest.log](https://github.com/Lothrazar/Cyclic/files/3950567/latest.log)

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Yes , something changed in one of the previous versions. the guide book no longer has a recipe by default.  Most modpacks either disable it, let the player start with it, or add their own recipe.
