### ISSUE TITLE
Nullpointerexception in attempt to render sprinkler

### ISSUE THREAD

**Issue by chuggafan** [Lothrazar/Cyclic#1268]
Minecraft Version: 
1.12.2
Forge Version: 
14.23.5.2847
Mod Version: 
1.19.18
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):

The Sprinkler has been causing me problems on the DDSS modpack recently, I've crashed 3 times due to it and it's not consistent as to why. https://pastebin.com/R626k3Wt for the dump.

The relevant line that's being called to cause this NPE in rendering is: https://github.com/Lothrazar/Cyclic/blob/5782e0f79bd4f67d52cb03659b97771a315fc83a/src/main/java/com/lothrazar/cyclicmagic/block/sprinkler/SprinklerTESR.java#L79

Log file link:

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
