### ISSUE TITLE
Sack of Holding and RS's Crafters not keeping items

### ISSUE THREAD

**Issue by Rafii2198** [Lothrazar/Cyclic#1270]
Minecraft Version: 
- 1.12.2
Forge Version: 
- 14.23.5.2846
Mod Version: 
- 1.12.2-1.19.18
Single Player or Server:
- Server
Describe problem (what you were doing; what happened; what should have happened):

I used Sack of Holding to move Crafters from Refined Storage they were filled with patterns but when I placed them, they all were empty.

Logs only shows the loading of mods as well as dimensions and unloading them so nothing useful in this situation.

**Comment by Lothrazar** [comment]
Looks like its one of those blocks thats juts not compatible.  Almost all mods store data internal to their block tile NBT data, but some of RS blocks store then outside in the file system, and those data files point to the blocks, so items like this cant copy paste them.

Only thing to do is add to black list. ill add to default list in code but modpacks can also block with config
disk_drive was already in there, so modpacks should add a few more such as


        "refinedstorage:disk_manipulator",
        "refinedstorage:disk_drive",
        "refinedstorage:crafter",

into 

`
    # Containers that cannot be lifted up with the Empty Sack of Holding.  Use block id; for example minecraft:chest [default: [extracells:fluidcrafter], [extracells:ecbaseblock], [extracells:fluidfiller], [refinedstorage:disk_drive], [parabox:parabox], [immersivengineering:metal_device1]]
    S:SackHoldingBlacklist <`
