### ISSUE TITLE
can autonomous user be used as a miner?  

### ISSUE THREAD

**Issue by DoomSquirter** [Lothrazar/Cyclic#1271]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2847
Mod Version: Cyclic-1.12.2-1.19.17
Single Player

Describe problem (what you were doing; what happened; what should have happened):
Autonomous user using pick to mine a block

use/attack mode, nothing happens with a block of coal in front of it and a diamond pick in it's input inventory

**Comment by Lothrazar** [comment]
Yeah use does right click action but attack just attacks with damage it doesnt try to left-click blocks . at least not in current version

**Comment by Lothrazar** [comment]
Working as intended for now. will reconsider for 1.15+
