### ISSUE TITLE
Crash during launch when Slowfall and Wing Charm are disabled.

### ISSUE THREAD

**Issue by SiliconEnt** [Lothrazar/Cyclic#1272]
### Context:
Minecraft: 1.12.2
Forge: 4.23.5.2847
Cyclic: 1.19.19
Single Player
Purpose-built testing instance – no other mods present.
No changes to config beyond those described.

### Description:
Game crashes during launch when both Wing Charm and Slowfall potion effect are disabled in config. Other potions and charms can be disabled without any negative consequence.

I have a hunch this has to do with the Wing Charm's use of the Slowfall effect. I would understand perfectly if disabling Slowfall while leaving the Wing Charm enabled crashed the game; the Wing Charm's functionality depends on the Slowfall effect being registered. However, I would expect that disabling both would at the very least fail gracefully.

If the problem does, in fact, spring from the Wing Charm's dependency on Slowfall, I can think of two possible approaches.
1. Patch the crashing code directly. I have no idea how this would work, as I'm not familiar with this mod's code.
2. Slowfall could be registered – regardless of config – as a backend, potionless effect similar to Vanilla's Glowing or Nausea effects. This seems a bit hackier to me, but it also seems that it would keep each feature in its own space.

### Logs:
Game log: https://gist.github.com/SiliconEnt/105058108d5af7fac02a7c575d8e20bd
Debug log: https://gist.github.com/SiliconEnt/44b63d2d993968445ba08c5233e287b6
Crash report: https://gist.github.com/SiliconEnt/ac5758aa873a4fca3575ae96db21c39e

**Comment by SiliconEnt** [comment]
After using Crafttweaker's potion effect dump command, I've become aware that even effects disabled in config are still invisibly registered. The embarrassing part is that I've used that command with Cyclic installed before, and noticed the same thing. 

So my second suggestion is in fact dumb, considering that:
1. It's been implemented the whole time.
2. I _knew_ that.
3. It didn't prevent this bug.

**Comment by Lothrazar** [comment]
Thanks for your patience, fix is on the way

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2883487 let me know if anything else breaks
