### ISSUE TITLE
[1.14.4] Crash while loading cyclic on a server.

### ISSUE THREAD

**Issue by Gbergz** [Lothrazar/Cyclic#1274]
Minecraft Version: 1.14.4

Forge Version: 28.1.107

Mod Version: 0.1.0 (Newest one released as of this moment)

Single Player or Server: On Server

Describe problem (what you were doing; what happened; what should have happened):
Starting server w/ the mod installed yields a crash. "Exception in server tick loop"
What should've happened is no error. Server starting normally. 

Log/crashreport file link:
[https://gist.github.com/Gbergz/165a5d6f7da96e40742e371a1f3b9449](https://gist.github.com/Gbergz/165a5d6f7da96e40742e371a1f3b9449)

**Comment by carlucci9660** [comment]
SAME ISSUE WITH ME

**Comment by Lothrazar** [comment]
fix on the way out

**Comment by Lothrazar** [comment]
should work https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2856653
