### ISSUE TITLE
Bouncy Potion allows unbounded acceleration, now with Slime Boots

### ISSUE THREAD

**Issue by NillerMedDild** [Lothrazar/Cyclic#1275]
### Minecraft Version: 
- 1.12.2

### Forge Version: 
- 1.12.2-14.23.5.2847

### Mod Version: 
- Cyclic-1.12.2-1.19.19

### Single Player or Server:
Single Player

### Describe problem (what you were doing; what happened; what should have happened):
Very similar to #725 - Having the Bouncy effect while wearing Slime Boots, and jumping from anything over 3 blocks, will result in incredible speed - The player who reported this travelled 8000 in a BoP world, 12.000.000 blocks in a Super Flat world in 5-10 seconds.

**Comment by Lgmrszd** [comment]
Looks similar to https://github.com/Lothrazar/Cyclic/issues/1191 as well

**Comment by NillerMedDild** [comment]
Ah, I see it marked as working as intended, thanks for the link, my bad.
