### ISSUE TITLE
crash place energy cable

### ISSUE THREAD

**Issue by tiphilou17** [Lothrazar/Cyclic#1276]
Minecraft Version: 1.14.4

Forge Version: 111

Mod Version: Cyclic-1.14.4-0.1.1.jar

Server:

Describe problem (what you were doing; what happened; what should have happened):

crash minecraft client when i place an energy cable

Log file link:
https://gist.github.com/tiphilou17/5aced2b529039515bb0ac6a0b285d7ea

**Comment by Boomflex** [comment]
Came here to post the same issue

https://pastebin.com/UPs2bj33

**Comment by Lothrazar** [comment]
try this build https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2858446

**Comment by Boomflex** [comment]
Working now for me on the latest ver 01.2!

Thanks Loth :)
