### ISSUE TITLE
Tempered Glass & Fluid Tanks Display Inner Seams

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1277]
`Minecraft v1.14.4`
`Forge v28.1.111`
`Cyclic v0.1.1`
- Single Player

Describe problem (what you were doing; what happened; what should have happened):
- Tempered Glass & Fluid Tanks will both display inner seams when placed next to each other, which should be hidden.

Image:
![2020-01-12_10 27 55](https://user-images.githubusercontent.com/12000593/72222155-833c8680-3527-11ea-8d9a-686e2b1d8537.png)

**Comment by Lothrazar** [comment]
tanks will be changing a lot. glass isnt so bad as its more of a functional block. but yeah it should be more like normal glass.

**Comment by Lothrazar** [comment]
Yep as said above its not a connected texture in 1.14. for fluid tank see https://github.com/Lothrazar/Cyclic/issues/1278
