### ISSUE TITLE
Fluid Tank Render Issues

### ISSUE THREAD

**Issue by WenXin20** [Lothrazar/Cyclic#1278]
`Minecraft v1.14.4`
`Forge v28.1.111`
`Cyclic v0.1.1`
- Single Player

Describe problem (what you were doing; what happened; what should have happened):
- Tanks render fluids a lot darker than they should be.
- This includes both vanilla & modded liquids.

Image:
Lava is in this tank:
![2020-01-12_10 30 16](https://user-images.githubusercontent.com/12000593/72222198-d1518a00-3527-11ea-890c-d22ee2918aa2.png)

**Comment by Lothrazar** [comment]
This is fixed in 1.15 , but wont be fixed in 1.14 . 1.15 has a whole new rendering engine, and everyones moving on anyway

**Comment by WenXin20** [comment]
Yep, that's fine, I've already moved to 1.15 too.
