### ISSUE TITLE
Disable Always On?

### ISSUE THREAD

**Issue by Yourname942** [Lothrazar/Cyclic#1279]
Minecraft Version: 12.2.2
Forge Version: 14.23.5.2847
Mod Version: Cyclic-1.12.2-1.19.19.jar
Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
Is it possible to disable the always on option for the cyclic machines? The "requires redstone" already exists, but I want to force players to not have the option for always on, as it is not balanced. Thank you.

**Comment by Lothrazar** [comment]
But a lever is only one stick and one cobblestone. How is it more balanced to make them put a lever or redstone block on the outside?  

Anyway , just trying to stabilize 1.12 with as few bugs as possible so not ading new features.  Ill think about it for 1.15+ but i still dont see how using a lever affects balance :S
