### ISSUE TITLE
Get disconnected after opening inventory in LAN multiplayer

### ISSUE THREAD

**Issue by HydrogenC** [Lothrazar/Cyclic#1280]
Minecraft Version: 1.12.2

Forge Version: 14.3.5.2847

Mod Version: 1.19.19

Single Player or Server: Open to LAN with a single player world

Describe problem (what you were doing; what happened; what should have happened):
I opened a LAN server (with Server.Properties for LAN mod) on my first PC, and my second PC could join the multiplayer game successfully. But if I open my inventory on my second PC, my second PC will be disconnected. 

Log file link:
[Latest.log of First PC](https://paste.ubuntu.com/p/NFBRhJZw2T/) (Line 2696)
[Latest.log of Second PC](https://paste.ubuntu.com/p/7wnk3pM6hr/)
Fixes if I remove Cyclic

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by HydrogenC** [comment]
Added link of latest.log

**Comment by Lothrazar** [comment]
Snipped of main error on line 2696 as mentioned. for reference
https://gist.github.com/Lothrazar/26a6920514bfb5065b4cb85a915d9b0a

**Comment by HydrogenC** [comment]
Many thanks

**Comment by Lothrazar** [comment]
Cant find any root causes for this or any fixes. Apparently its common knowledge that LAN can be buggy with modpacks . also nothing in log points specifically to cyclic so im sorry wish i could help
