### ISSUE TITLE
Harvester spams console

### ISSUE THREAD

**Issue by LezChap** [Lothrazar/Cyclic#1281]
Minecraft Version: 
1.14
Forge Version: 
28.1.109
Mod Version: 
1.14.4-0.1.2
Single Player or Server:
Server

While running, the Harvester is spamming the server console every second...looks like it's this line here:
https://github.com/Lothrazar/Cyclic/blob/11e1a1a51aacff33a4229a6d4dbe9426ebf87767/src/main/java/com/lothrazar/cyclic/block/harvester/TileHarvester.java#L105

**Comment by Lothrazar** [comment]
Latest release has fix
