### ISSUE TITLE
Can't see Preview Lines from Nodes With shader anymore

### ISSUE THREAD

**Issue by Lopi13** [Lothrazar/Cyclic#1282]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: Cyclic-1.12.2-1.19.19.

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):

while Using a Shader i coudn't see the preview Lines from the nodes Anymore

Video/images/gifs (direct upload or link): 

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
Hey i know its been a while, thanks for your patience.

optifine with shaders does a whole bunch of stuff with lighting that changes things around so its hard to predict what different shaders will do.  I dont even know if theres anything i can do.

Would help to have screenshots and link to exactly which shader and optifine version. But aside from guessing and trying to make it brighter or a different colour theres not many options when it comes to this type of rendering

**Comment by Lothrazar** [comment]
Shaders gonna shade not much that OPENGL can do about it .  I play with shaders too i just disable them for a few minutes while setting up a complex automation, then turn shdders back on later
