### ISSUE TITLE
1.15.1 Crash on server loading

### ISSUE THREAD

**Issue by Yamza** [Lothrazar/Cyclic#1284]
Minecraft Version: 1.15.1

Forge Version: 30.0.41

Mod Version: 	Cyclic-1.15.1-0.1.3.jar

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Server crashed during load.

Log file link: https://hatebin.com/wjwoymgzyb

**Comment by carlucci9660** [comment]
1.14.4 server crash on loading.....see crash reports FORgE 28.1.115

[crash-2020-01-20_20.58.51-server.txt](https://github.com/Lothrazar/Cyclic/files/4088881/crash-2020-01-20_20.58.51-server.txt)
[crash-2020-01-20_21.02.24-server.txt](https://github.com/Lothrazar/Cyclic/files/4088882/crash-2020-01-20_21.02.24-server.txt)
[crash-2020-01-20_21.04.24-server.txt](https://github.com/Lothrazar/Cyclic/files/4088883/crash-2020-01-20_21.04.24-server.txt)
[crash-2020-01-20_21.05.43-server.txt](https://github.com/Lothrazar/Cyclic/files/4088884/crash-2020-01-20_21.05.43-server.txt)
[crash-2020-01-20_20.35.58-server.txt](https://github.com/Lothrazar/Cyclic/files/4088885/crash-2020-01-20_20.35.58-server.txt)
[crash-2020-01-20_20.57.16-server.txt](https://github.com/Lothrazar/Cyclic/files/4088886/crash-2020-01-20_20.57.16-server.txt)

**Comment by Lothrazar** [comment]
1.15 crash fixed in Cyclic-1.15.1-0.1.4.jar

**Comment by Lothrazar** [comment]
As for the second issue, the 1.14 one, energizing rod tile isnt cyclic 

java.lang.NoSuchMethodError: owmii.lib.util.Ticker.<init>(D)V
	at owmii.powah.block.energizing.EnergizingRodTile.<init>(EnergizingRodTile.java:21) ~[?:0.2.3] {re:classloading}
	at owmii.powah.block.energizing.EnergizingRodBlock.createTileEntity(EnergizingRodBlock.java:92) ~[?:0.2.3] {re:classloading}
