### ISSUE TITLE
Soundproofing doesn't work with the Ember Bore

### ISSUE THREAD

**Issue by cheshyrp** [Lothrazar/Cyclic#1285]
Minecraft Version: 1.12

Forge Version: 14.23.5.2847

Mod Version: 112.2.119.19

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):

The Soundproof block does nothing to reduce the noise from Ember Rekindled's Ember Bore. I suspect this is related to the Bore itself, as destroying the bore it while it's running continues to play the sound until I relog.

**Comment by Lothrazar** [comment]
Yeah, this is a bug with the Bore. 

There is a standard normal way to 
- Register your sound with forge
- Play your registered sound with the minecraft sound engine.
- This is where Soundproofing (and any forge mod) can hook into that sound playing event. 

If their sounds bypass this or play in a custom way, my blocks dont even know the sound exists.  Like you noticed. the sound is even somehow disconnected to the Bore.
