### ISSUE TITLE
Excessive chunk updates caused by certain Cyclic blocks

### ISSUE THREAD

**Issue by DennisCorvers** [Lothrazar/Cyclic#1286]
Minecraft Version: 1.12.2 (Modpack Dungeons Dragons & Space Shuttles)

Mod Version: Cyclic-1.12.2-1.19.19

Single Player or Server: Both

Describe problem (what you were doing; what happened; what should have happened):
A list of certain Cyclic blocks causes massive amounts of chunk updates. Some of these are the harvester, automatic user, powered enchanter, diamond (powered) anvil.

Just placing down one of these machines in a freshly created world will bump the chunk updates up to 120. Placing multiple of these machines in separate chunks spread apart will cause roughly 120 chunk updates per harvester. As a result, when playing in a world with a few harvesters in visible proximity, the chunk updates can easily exceed 500 and render the game unplayable.

**Comment by Coji4000** [comment]
Just to add to this you can see this in action by opening task manager, opening minecraft with cyclic on 1.19.19 staring at the grass until CPU levels out then placing the powered anvil or harvester and watch the CPU jump up by quite a bit.

the same issue cannot be recreated in 1.19.18

**Comment by niceone548** [comment]
I made a vid of it
https://www.youtube.com/watch?v=br_qZxJL5eU

**Comment by Lothrazar** [comment]
OK ill check out what changed between *.18 and *.19 that would cause this, might be easy to revert 

EDIT: found the cause https://github.com/Lothrazar/Cyclic/commit/015e59a87013a5e5956f4351f1b00264c1f9e2e3#diff-bd4af37e3cc8f3cc2dbb10681f202a2eR674

**Comment by Lothrazar** [comment]
fantastic video BTW


made some changes

![2020-02-16_15 48 30](https://user-images.githubusercontent.com/621529/74615242-dc25ae80-50d3-11ea-9adb-3f3ffef1c6c6.png)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2883487
