### ISSUE TITLE
Duplicate Recipes for Multiple Items [1.15.1]

### ISSUE THREAD

**Issue by Millificent** [Lothrazar/Cyclic#1287]
Minecraft Version:  1.15.1

Forge Version: 30.0.43

Mod Version: 	Cyclic-1.15.1-0.1.5.jar

Single Player or Server: Single and Server

Describe problem (what you were doing; what happened; what should have happened):
All items share the same recipe:
Ender Wing Prime
Ender Orb Translocator
Ender Orb

Video/images/gifs (direct upload or link): 
https://yoosk.pl/LKD58orP.png 
https://yoosk.pl/LgSWhUIi.png 
https://yoosk.pl/22T4tMoJ.png

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
is everything fixed in latest https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2869262
