### ISSUE TITLE
[1.14.4] Crash using the Excavate Enchantment. (?)

### ISSUE THREAD

**Issue by Gbergz** [Lothrazar/Cyclic#1288]
Minecraft Version: **1.14.4**

Forge Version: **28.1.107**

Mod Version: **0.1.3**

Single Player or Server: **Server**

Describe problem:
One of our players on the server were using the Excavate Enchantment, no further information available.

Crash report: https://gist.github.com/Gbergz/94594fe531f36e7b187079c55b3d3f97

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Cyclic/issues/1283

**Comment by Lothrazar** [comment]
1.15 fix https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2882784
