### ISSUE TITLE
[Question] How to use the Dehydrator?

### ISSUE THREAD

**Issue by IanKemp** [Lothrazar/Cyclic#1289]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Mod Version: 1.19.14

Single Player or Server: single player

Describe problem (what you were doing; what happened; what should have happened):

I'm trying to make Vines in Sky Factory 4 by dehydrating Jungle Saplings as per this recipe:

![image](https://user-images.githubusercontent.com/1726434/73137047-36d76780-404c-11ea-9b0e-860da73e0da7.png)

I have a Dehydrator connected to power, but when I put the Jungle Saplings in, I get Sticks instead:

![image](https://user-images.githubusercontent.com/1726434/73137237-f547bc00-404d-11ea-8a38-9dc756ae33e2.png)

The description text for the Dehydrator also mentions using lava, but I can't figure out how to get that into the Dehydrator, and/or if not having lava is the reason this isn't working.

**Comment by Lothrazar** [comment]
There could be some recipe conflicts.  Tank can be filled and emptied . lava thing might have changed .

**Comment by Lothrazar** [comment]
also i have to check in the pack, for the recipes in https://github.com/DarkPacks/SkyFactory-4/

**Comment by BoozeAndMidgets** [comment]
This is almost two years later, but there is a recipe conflict. 

Sticks have a recipe in the dehydrator that is jungle saplings>sticks and also jungle saplings>vines. 

Unfortunately the stick one takes priority.
