### ISSUE TITLE
Suggestion: Config to make Experience Pylon void excess XP Orbs

### ISSUE THREAD

**Issue by Nonsanity** [Lothrazar/Cyclic#1290]
The Experience Pylon sucks up XP Orb drops and stores them as a counter internally. Then sugar can be right-clicked on the pylon to extract the XP as an edible item. This is ideal for mob farms where the killing mechanic acts as a player and generates XP drops.

However, the Pylon only seems to hold 4096 xp points (about 80 sugar hits) and then excess XP Orbs remain in the world. This can cause massive slowdowns on servers if the XP isn't being handled.

By having the Pylon continue to absorb dropped XP but void it if it has reached it's (configurable?) limit, servers will be better protected.

Even without a configuration to turn this feature on and off, I'd personally prefer it to void be default.

**Comment by Lothrazar** [comment]
in latest release it has much higher capacity so this problem wont happen. also working adding back in the fluid system from 1.12
