### ISSUE TITLE
Pattern Replicator preview and redstone mode not working

### ISSUE THREAD

**Issue by Wxrlds** [Lothrazar/Cyclic#1296]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Mod Version: 1.19.19

Single Player or Server: Both

Describe problem:
When toggling the preview or redstone mode button of the Pattern Replicator it toggles for (probably) 1 tick and then changes back.

Video/images/gifs (direct upload or link): 
![Technocratica 2020-01-31 22-33-01](https://user-images.githubusercontent.com/42120270/73576367-9386b800-447a-11ea-9894-c0e7c4804c33.gif)

**Comment by Lothrazar** [comment]
I can see there is an issue from your gif for sure.  

Trying to replicate it locally... 

So on my server with almost no other mods it goes like this

![1296](https://user-images.githubusercontent.com/621529/74616734-6b37c400-50de-11ea-897d-f55faa648797.gif)


I dont know why im not seeing it

What modpack are you using or is there a list of mods?

**Comment by Wxrlds** [comment]
I don't know what you did but after updating Cyclic to [1.19.20](https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2883487) it seems to work again.
I'm playing [Technocratica v2.0.37](https://www.curseforge.com/minecraft/modpacks/technocratica/files/2881663) in case you still want to take a look at it.
