### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by krelios** [Lothrazar/Cyclic#1297]
Minecraft Version: 1.15.2

Forge Version: 31.0.19

Mod Version: Cyclic-1.15.2-0.1.7.jar

Single Player or Server: Server

Trying to start server, crash in Cyclic

Log file link: 
https://pastebin.com/LRvM9J7u

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2875245
