### ISSUE TITLE
[1.15.2] Crash when using Auto Torch.

### ISSUE THREAD

**Issue by Gbergz** [Lothrazar/Cyclic#1298]
Minecraft Version: 1.15.2

Forge Version: 31.1.0

Mod Version: 0.1.8

Single Player or Server: Singleplayer, sure it works on MP too.

Describe problem (what you were doing; what happened; what should have happened):
I was using the Auto Torch item that is placing torches in darkness around you. Then i crashed.

Crash report: https://gist.github.com/Gbergz/70f7448c6d34d24f8572b819210d8447

 Any ideas?

- Gbergz

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2882784

**Comment by EPIICTHUNDERCAT** [comment]
:*
