### ISSUE TITLE
Incomplete server tags on reJoin [HARD TO DEBUG]

### ISSUE THREAD

**Issue by TheMartinfer22** [Lothrazar/Cyclic#1906]
![plants](https://user-images.githubusercontent.com/66142507/131229651-e955d509-9374-44b7-8f9f-71026d55f5d2.png)
Hello, I am witnessing a problem that does not occur all the time, only when the server is restarted and between 20 people 1 or 2 the problem occurs, it is related to forge:plants.

Message when rejoining server: **Incomplete server tags, disconnecting. Missing: {minecraft:block=[forge:plants]}**

I saw in your source that you are using the same TAG and in the mods list is the only one that is pointing to this reference, could it be something related to the last update or there is no relationship?

Minecraft Version: 1.16.5
Forge Version: 36.2.2
Mod Version: 1.3.6
Single Player or Server: Server

Log Entries

```
[B#683] 2021/08/28 15:36:01 [INFO]  [15:36:01.014] [Render thread/INFO] [immersivepetroleum/]: Loading Distillation Recipes. 
[B#683] 2021/08/28 15:36:01 [INFO]  [15:36:01.018] [Render thread/INFO] [immersivepetroleum/]: Loading Reservoirs. 
[B#683] 2021/08/28 15:36:01 [INFO]  [15:36:01.021] [Render thread/INFO] [immersivepetroleum/]: Loading Coker-Unit Recipes. 
[B#683] 2021/08/28 15:36:01 [INFO]  [15:36:01.024] [Render thread/INFO] [immersivepetroleum/]: Loading Sulfur Recovery Recipes. 
[B#683] 2021/08/28 15:36:01 [INFO]  [15:36:01.109] [Render thread/INFO] [lollipop/Wiki]: Started wikis recipes collecting... 
[B#683] 2021/08/28 15:36:05 [INFO]  [15:36:05.056] [Render thread/INFO] [lollipop/Wiki]: Wiki recipes collecting completed in : 3947 ms 
[B#683] 2021/08/28 15:36:05 [INFO]  [15:36:05.732] [Render thread/INFO] [minecolonies/]: Finished discovering compostables 
[B#683] 2021/08/28 15:36:05 [INFO]  [15:36:05.732] [Render thread/INFO] [ModSetup/]: onRecipesUpdatedEvent 
[B#683] 2021/08/28 15:36:05 [INFO]  [15:36:05.816] [Render thread/INFO] [Botany Pots/]: Loaded 259 botanypots:crop recipes from 11 namespaces 
[B#683] 2021/08/28 15:36:05 [INFO]  [15:36:05.816] [Render thread/INFO] [Botany Pots/]: Loaded 4 botanypots:fertilizer recipes from 4 namespaces 
[B#683] 2021/08/28 15:36:05 [INFO]  [15:36:05.816] [Render thread/INFO] [Botany Pots/]: Loaded 58 botanypots:soil recipes from 8 namespaces 

> [B#683] 2021/08/28 15:36:05 [INFO]  [15:36:05.924] [Render thread/WARN] [network.play.ClientPlayNetHandler/]: Incomplete server tags, disconnecting. Missing: {minecraft:block=[forge:plants]}

[B#683] 2021/08/28 15:36:06 [INFO]  [15:36:06.136] [Render thread/INFO] [backend.Backend/]: No shader config found. 
[B#683] 2021/08/28 15:36:06 [INFO]  [15:36:06.164] [Render thread/INFO] [STDOUT/]: [xaero.common.XaeroMinimapSession:cleanup:67]: Minimap session finalized. 
[B#683] 2021/08/28 15:36:06 [INFO]  [15:36:06.174] [Render thread/INFO] [Astral Sorcery/]: Client cache cleared! 
[B#683] 2021/08/28 15:36:06 [INFO]  [15:36:06.178] [Render thread/INFO] [minecolonies/]: Removed all colony views 
[B#683] 2021/08/28 15:36:25 [INFO]  [15:36:25.853] [Render thread/INFO] [Minecraft/]: Stopping! 
```

**Comment by aAndrew3030** [comment]
I am receiving the same incomplete set of tags error with 1.3.6, but on a single player world

**Comment by TheMartinfer22** [comment]
> I am receiving the same incomplete set of tags error with 1.3.6, but on a single player world. I believe the error is with the harvester

Yes, solution is download release 1.3.5... and wait solve...

**Comment by Lothrazar** [comment]
I think i closed in on this.  WHen adding compatibility tags i referenced

forge:grass

tag, here https://github.com/Lothrazar/Cyclic/blob/trunk/1.16/src/main/resources/data/forge/tags/blocks/plants.json#L6

But this tag doesnt exist by defualt in forge, and i didnt create at least a  default version. so it can be an unknown.  Might be a way to fix with data paks but Im working on a mod fix for this real soon

**Comment by Lothrazar** [comment]
1.3.7 should resolve https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3445215
