### ISSUE TITLE
Question [porting fish-hook from 1.10.2 to 1.18.2+ ?]

### ISSUE THREAD

**Issue by Kasia1403** [Lothrazar/Cyclic#2130]
Where is fishhook ?

**Comment by Lothrazar** [comment]
Yeah good callout, that was a fun item back in i think 1.10.2 or 1.12.2 . no idea when but i am keeping track of these unported items here https://github.com/Lothrazar/Cyclic/projects/6 and this one wasnt listed so im adding it

**Comment by Lothrazar** [comment]
![fishhook](https://user-images.githubusercontent.com/621529/179315774-96fa3f4d-5f29-410a-9275-d64318cf5c1f.png)

**Comment by Kasia1403** [comment]
What about porting to 1.12.2 ? Or this item is in 1.12.2 already ?

**Comment by Lothrazar** [comment]
yeah i will look into doing another 1.12.2 issue later so ill leave this other one open https://github.com/Lothrazar/Cyclic/issues/2135
