### ISSUE TITLE
Suggestion [on porting 1.10.2 content to 1.12.2+]

### ISSUE THREAD

**Issue by Kasia1403** [Lothrazar/Cyclic#2135]
To port alluring fishhook from Mincraft 1,10.2 to 1.12.2 ( this is because I can't find it in 1.12.2 ).

**Comment by Lothrazar** [comment]
yeah when i have some time after doing other stuff, i want to look into the differences of 1.10.2 vs 1.12.2 some more

**Comment by Lothrazar** [comment]
update: Was added to 1.18.2-1.7.4+

**Comment by Kasia1403** [comment]
When it will be added also to 1.12.2 ?

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/4075832
