### ISSUE TITLE
Glitchy minecart rendering

### ISSUE THREAD

**Issue by Ithronyar** [Lothrazar/Cyclic#745]
Minecraft version: 1.12.2
Mod version: 1.14.3
Singleplayer

The minecarts added by Cyclic look kind of broken. They seem to work fine, but they split into two de-synced duplicates when moving. This is most noticeable when the minecart is turning corners.

**Comment by PrinceOfAmber** [comment]
Yeah I noticed this a little while ago, not sure when or where it came from.

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.

if minecarts ever come back in 1.14+ it will be in a standalone mod
