### ISSUE TITLE
Items in Inventory automatically move after changing IME

### ISSUE THREAD

**Issue by RisingInIris2017** [Lothrazar/Cyclic#824]
Minecraft version & Mod Version:
1.12.2, Mod version 1.15.7

Single player or Server:
Single Player.

Describe problem (what you were doing / what happened):
1. change these hotkeys to NONE:
Item Shift Down
Item Shift Up
2. change the IME to input some Chinese characters in game, for example, in a Sign's input box. 
3. Open the Inventory, seeing items **in the fifth column** move automatically. Then every time the Inventory is opened, they move again.

[In this video](https://streamable.com/ewi6s), the bug is shown in detail.

Crash log (if any):
This bug doesn't crash the game.

**Comment by PrinceOfAmber** [comment]
I will look into it, but im not really sure how to debug this.

If you want the feature fully gone and the keybinds not even showing up in the menu, you can use this config set to false. around line 720 of config

`KeybindInventoryShift=true`

**Comment by PrinceOfAmber** [comment]
Do you know how to enable those characters in my on-screen keyboard? I am in windows 10

**Comment by RisingInIris2017** [comment]
Thanks for your help! It does work.
And for on-screen keyboard, click Windows-Key first, and then click the space bar can change the IME from  one to another. Besides, I think any character can reproduce that bug, rather than particular ones.

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle . Glad we found a workaround, and i was never sure where to start anyway
