### ISSUE TITLE
When Valkyrien Warfare is installed, the Rainbow Cannon's projectile holds still instead of flying.

### ISSUE THREAD

**Issue by TeetoKaziim** [Lothrazar/Cyclic#851]
Minecraft version & Mod Version:
Minecraft: 1.12.2
Forge: 14.23.4.2708
Cyclic: 1.15.11

The rest of the modlist:
Valkyrien Warfare: 0.9_prerelease_5[Optimization update]

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
When Valkyrien Warfare is installed, The Rainbow Cannon (the cool new laser?), when fired, the projectile hangs in the air instead of flying forward.

Thank You and the best to ya! I'm going to post this on their issue tracker too and link it here, since I don't know whoms'es "fault" this is.

EDIT: https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/171

**Comment by Darkmega18** [comment]
huh, so thats what did it that one time. I thought it was just a work in progress weapon and it was wigging out. xD

**Comment by Darkmega18** [comment]
probably needs an item that transfers energy to it. like an actually additions battery or something.

**Comment by Julie226** [comment]
Okay, I'll try that and get back to you by tomorrow probably.

**Comment by Julie226** [comment]
Thank you so much Darkmega18. I thought I was missing something in the cyclic mod itself.

**Comment by Darkmega18** [comment]
nah. Cyclic just doesn't have too many ways to make power, despite requiring it itself. Extra utils, actually additions or some other tech mod is usually a good combo.

**Comment by PrinceOfAmber** [comment]
@Darkmega18  correct, the only block that charges up items like the rainbow cannon is the Battery from cyclic in its item slot.  Other mods have more diverse options

**Comment by Lothrazar** [comment]
Other mod appears abandoned, no response since Jun 16, 2018 . Closing as there is nothing to do on my end

**Comment by TeetoKaziim** [comment]
Yeah, I only opened it on both trackers because at the time, I wasn't sure "who could fix".

In the intervening months, I've discovered VW's current release version has a similar effect on several projectiles from the "Embers" mod, including the ember bursts used to transmit ember power, rendering that mod completely unplayable.

Thanks for your time, patience, and attention.
