### ISSUE TITLE
Duplicate Language key with some mods

### ISSUE THREAD

**Issue by TartaricAcid** [Lothrazar/Cyclic#874]
### Here is the list:
`potion.effect.wither`
- cofh `Potion of Decay`
- cyclicmagic `Potion of Wither`

`splash_potion.effect.wither`
- cofh `Splash Potion of Decay`
- cyclicmagic `Splash Potion of Wither`

`tipped_arrow.effect.wither`
- cofh `Arrow of Decay`
- cyclicmagic `Arrow of Wither`

`fluid.xpjuice`
- cyclicmagic `Experience`
- enderio `Liquid XP`

`tile.block_enchanter.name`
- cyclicmagic `Powered Enchanter`
- enderio `Enchanter`

`tile.fluid_pump.name`
- cyclicmagic `Fluid Extraction Cable`
- fp `Pump`

`tile.item_pump.name`
- cyclicmagic `Item Extraction Cable`
- embers `Item Extractor`

`tile.item_pipe.name`
- cyclicmagic `Item Cable`
- embers `Item Pipe`

`tile.imbuer.name`
- cyclicmagic `Imbue Station`
- roots `Imbuer`

`tile.fluid_pipe.name`
- car `Fluid Pipe`
- cyclicmagic `Fluid Cable`

**Comment by PrinceOfAmber** [comment]
So what is the result of this issue?  If I have both "car" and cyclic installed, do both items from both mods get called "Fluid Cable" ?

**Comment by TartaricAcid** [comment]
yes, so each language key should be unique to avoid the question, forge will handle all language in a hashmap.

**Comment by Lothrazar** [comment]
forge is just this way out of the box. non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.
1.14 + has this working by default
