### ISSUE TITLE
[1.12.2] Preview darkness differences

### ISSUE THREAD

**Issue by TheSnowyChickens** [Lothrazar/Cyclic#879]
Minecraft version & Mod Version:
1.12.2
Cyclic 1.16.2
Forge 14.23.4.2732

Single player or Server: -> Singleplayer

Describe problem (what you were doing / what happened):
I don't know, if this is a bug, but in 1 direction the preview from the harvester has some darker sides and in the other direction is it a smooth continuous color.
![2018-07-14_23 05 19](https://user-images.githubusercontent.com/29357962/42728433-68348f70-87ba-11e8-9c54-c0cbb7ac2dca.png)

The continuous color version looks better, btw. :)

**Comment by PrinceOfAmber** [comment]
yeah the overlap is inconsistent, sometimes it shadows

**Comment by Lothrazar** [comment]
At this point im going to call it working as intended .  its fine for now, i might overhaul OPENGL rendering in 1.13 though
