### ISSUE TITLE
I hope to have a liquid/magma collector machine

### ISSUE THREAD

**Issue by AsleepSnake** [Lothrazar/Cyclic#889]
New machines need too much magma
I am very painful to collect magma.
I hope to make a machine that automatically collects magma.
One or one collection magma like an automatic harvester
I hope to carry it simply
I hope you are getting better and better

**Comment by Lothrazar** [comment]
Created this in a recent update :D 

![fluid collector](https://user-images.githubusercontent.com/621529/54102793-0e3c7580-4387-11e9-92b0-01921885fb20.gif)

**Comment by AsleepSnake** [comment]
Fantastic ！！！
