### ISSUE TITLE
Add blacklist for Block Placer

### ISSUE THREAD

**Issue by monodemono** [Lothrazar/Cyclic#897]
So from the sound of it, https://github.com/PrinceOfAmber/Cyclic/issues/865 is kind of a big issue to fix, and not entirely on your end. In the mean time, can we get a blacklist for the block placer in the config so we can prevent this from happening?

This could potentially be useful in other ways too, such as blocking players from placing things that we don't allow them to place themselves too.

**Comment by PrinceOfAmber** [comment]
If i get it fixed with the fake user strategy ill default  the blacklist is empty, but yeah it will be good to have regardless

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. the big modpacks have gotten by without it
