### ISSUE TITLE
Auto Crafter not properly utilising items with durability.

### ISSUE THREAD

**Issue by xetcalin** [Lothrazar/Cyclic#898]
**Minecraft version & Mod Version:**

MC: 1.12.2
Mod : 1.16.8

**Single player or Server:**
Single Player

**Describe problem (what you were doing / what happened):**
The auto crafter has an issue wherein if your recipe uses a multi-use crafting item, it will move it from the left side, of the "ingredients", to the right side, of the "products", thus making auto-crafting with these items a massive pain. 

The example I was having issues with was the Bio-Mash recipe for Actually Additions. In manual crafting, you put a knife in the center, and foodstuff around the knife. However, the knife is not consumed upon crafting instead loses some durability. 

In the Auto Crafter, instead of remaining in the left "ingredients" section, it is moved to the right AND does not consume any durability in the process either, when it does during manual crafting.

**Comment by Lothrazar** [comment]
thanks for your patience , fixed in latest version https://minecraft.curseforge.com/projects/cyclic/files/2663412
