### ISSUE TITLE
Excavation doesn't work on Redstone Ore

### ISSUE THREAD

**Issue by Lykrast** [Lothrazar/Cyclic#935]
**Minecraft version & Mod Version:** 1.12.2-1.17.1

**Single player or Server:** server

**Describe problem (what you were doing / what happened):** Breaking Redstone Ore with a Pickaxe with Excavation does not break the whole vein like other blocks.

**Comment by PrinceOfAmber** [comment]
Yeah it gets confused when the redstone lights up and has particles and shifts state.  I cant promise when i can get a fix in, but in the meantime this mod was created specifically for that redstone issue for other excavators https://www.curseforge.com/minecraft/mc-mods/mundane-redstone-ore

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle
