### ISSUE TITLE
Nether ores of vanilla types do not spawn in BOP biomes with soul_sand as filling block

### ISSUE THREAD

**Issue by donqixot** [Lothrazar/Cyclic#940]
Minecraft version & Mod Version: MC 1.12.2, Cyclic-1.12.2-1.15.12

Single player or Server: single

I am playing FS Lost Souls modpack and noticed that nether_iron_ore (and other vanilla types) do not spawn at some BiomesOPlenty biomes, like "Corrupted Sands". Could it be due to the fact that filling material in those biomes is not netherrack, but soul_sand? Is there any chance to change that thru config?

**Comment by PrinceOfAmber** [comment]
its not the biome, its the target block. so anywhere in dimension = 1 with block netherrack .  

its not currently a config but , yeah having it spawn in modded blocks it could be done

**Comment by PrinceOfAmber** [comment]
The easy way out is to make the exact same block (with netherrack texture pulled in with the transparent overlay) spawn in, but that would look ugly.  I could do that but could take longer for a better way

Trying to see how theres a way where i can swap out the visual texture/model for the block in the biome from some other mod , which also means you could in theory put it in soulsand or gravel or grass or anything.  IDK how to do that yet tho
