### ISSUE TITLE
Energy Transfer Node

### ISSUE THREAD

**Issue by Shadocat** [Lothrazar/Cyclic#948]
Minecraft version & Mod Version:
Twitch launcher Minecraft 1.12.2  Stoneblocks Modpack

Single player or Server:  Server

Describe problem (what you were doing / what happened):  
    I placed the Energy Transfer Node down next to (touching) an "Integrated Dynamics Energy Battery".
It does not take on any energy into the node.

    I tried using the GPS devices.  I set one to the Energy battery.  I also tried setting a second one directly to the Magmatic Generator.  It does not seem to respond to either device.

    I played with all the settings, and searched for hours on the web.  

*Does this device work with Redstone Flux (RF) Power?

    After going over the modpack, I suspect that maybe it requires some power source called (FE).  But there is no documentation, or mention of energy requirements anywhere.   
If this is designed for a specific type of energy, I recommend something in the item's descriptors that lets an end user know what type of power it uses.

    JEI shows me an item called Cyclic Guide Book.  It might contain some answers, but there is no apparent crafting recipe to create the book.

Crash log (if any): None

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)
    There is a suggestion in here, but really I don't know if the mod is working as intended, and hope you can enlighten me.   The real problem might just be communication, or maybe I'm just missing a detail.
Thanks for your time.

**Comment by PrinceOfAmber** [comment]
![energy cables](https://user-images.githubusercontent.com/621529/46901772-6588f900-ce6e-11e8-8a2e-401493b69c5b.gif)

**Comment by TheSnowyChickens** [comment]
I have some more bugs relating to the wireless system:
- Mekanism machines are "air" ("Detect target block" button message)
- the "Detect target block" button ignore the state of thermal machines. (always "basic", but its higher)

**Comment by Lothrazar** [comment]
Looked into it a bit. For some reasonss those specific mods add crazy NBT data to block/item drops to reuse the same block id, so unless they implement "getDisplayName" i cant get it.  


So for my side i added the blocks registry id to the end of the chat so its like this:

Laser Cell <cyclicmagic:laser>

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312

**Comment by SinisterGenocide** [comment]
im still having issues with the energy transfer node sending power to most of the mekanism machines. i thought this was fixed in 1.17.11? makes skyfactory 4 a pain in the ass

**Comment by MatoCL** [comment]
> im still having issues with the energy transfer node sending power to most of the mekanism machines. i thought this was fixed in 1.17.11? makes skyfactory 4 a pain in the ass

You're not alone Sinister :(
