### ISSUE TITLE
[Suggestion] Config to change size of storage bag or make size NBT tag

### ISSUE THREAD

**Issue by Goldenlion5648** [Lothrazar/Cyclic#950]
Would it be possible to make the storage bag have either varying sizes or be able to change it in the config? 77 slots is a bit much.

**Comment by PrinceOfAmber** [comment]
Config might work, but it would need GUI screen work to handle any size thats in there.  

I could make a few different sizes (maybe 2 or 3? not sure) where the texture shows it getting bigger, and config could turn on both or just one or none.

**Comment by Goldenlion5648** [comment]
I know some mods allow a config to change the size of the bag to any number below the max amount (amount it is now). You don't have to have a dynamic GUI necessarily, it could be up to the pack maker to either put X's on the unusable slots or make their own textures

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.  maybe 1.14+ or standalone mod would be cool for this. but theres that existing mod that does this already in sky factory 4 for bags and chests
