### ISSUE TITLE
No modded villagers spawning naturally when village generates

### ISSUE THREAD

**Issue by shadinx2** [Lothrazar/Cyclic#952]
Minecraft version & Mod Version: 1.12.2 Minecraft and Cyclic-1.12.2-1.17.3.jar

Single player or Server: Single Player

Describe problem (what you were doing / what happened): No modded villagers spawn in villages, neither from this mod nor from extra utilities. Modded structures spawn in village.

Crash log (if any): Nope
Mod list: AI improvements, apple core, apple skin, auto reg lib, battle towers, baubles, better fps, bookshelf, chunk animator, clumps, coroutil, cyclic, darkutils, dungeon tactics, enchanting plus, extrautils 2, farseek, foamfix, fps reducer, guide api, hunger overhaul, hwyla, infernal mobs, iv toolkit, jei, journey map, justenoughids, nutrition, optifine, plants, quark, recurrent complex,  roguelike dungeons, roughmobs 2, serene seasons, Spice of life, spice of life: carrot edition, streams, texfix, tickdynamic, tough as nails, vanilla fix, zombie awareness

These are just some mechanics and structure generation mods( I plan to add way more) and while testing these I saw that villagers from mods don't spawn(though they do from eggs).

 Probably not from your mod, but maybe you know from which one it may be.

**Comment by PrinceOfAmber** [comment]
Thanks for all the details.  In the past ive tested and seen them spawn in vanilla terrain at least, superflat and normal but i havent tested in a while.  

I will check it out using forge version  14.23.4.2760

**Comment by shadinx2** [comment]
It's not your mod. It's any mod that adds villager that are not connected to a structure somehow(eg Forestry). It's forge. I have opened a forge discussion on their bugs and errors forum: http://www.minecraftforge.net/forum/topic/66864-mod-based-villagers/

**Comment by PrinceOfAmber** [comment]
Yeah i just created a bunch of superflat worlds, and you are right none of them have modded villagers.  This used to work, and they DO still come from spawn eggs... so

Either forge has a bug,
or forge changed so i have to do something new

**Comment by PrinceOfAmber** [comment]
Thats true, ive tested Actually additions and they get their jam houses with villagers, that would be a fix/workaround.  It does take a bit of work id have to make a building structure and hook that in but its not a bad idea

**Comment by PrinceOfAmber** [comment]
@shadinx2  do sage and druid show up from villager breeding? I have them in my survival world so this must be how they spawned I bet

**Comment by shadinx2** [comment]
Tommorow

**Comment by Lothrazar** [comment]
Checked forge documentation, everything i have correctly registers villagesr

Looks like the latest forge does use the correct profession enum and not vanilla 

https://github.com/MinecraftForge/MinecraftForge/blob/af98088d04186452cb364280340124dfd4766a5c/patches/minecraft/net/minecraft/world/gen/feature/structure/VillagePieces.java.patch#L78

Which picks from the list that includes modded villagers

https://github.com/MinecraftForge/MinecraftForge/blob/af98088d04186452cb364280340124dfd4766a5c/patches/minecraft/net/minecraft/entity/passive/EntityVillager.java.patch#L77


But it still doesnt make sense. I can create a new world and use /locate Village and none of them are modded.  I need to find a sledgehammer solution

**Comment by Lothrazar** [comment]
update : found a solution i cna borrow https://github.com/Ellpeck/ActuallyAdditions/blob/29534764a952a34ebf4d599142a5254342e2596f/src/main/java/de/ellpeck/actuallyadditions/mod/gen/village/component/VillageComponentJamHouse.java#L230

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2685793
