### ISSUE TITLE
SFX Block Suggestion - config setting for if it broadcasts to everyone or only to the owner/placer 

### ISSUE THREAD

**Issue by GldnSabre74** [Lothrazar/Cyclic#955]
Suggestion to allow the SFX block to be heard by anyone other than the placer. Maybe make it a config option.

**Comment by PrinceOfAmber** [comment]
Also it seems like the one you pick doesnt save on world reload too

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312
