### ISSUE TITLE
Permissions issue cyclic/ftbutils

### ISSUE THREAD

**Issue by krisjenner** [Lothrazar/Cyclic#969]
Minecraft version & Mod Version: 1.12.2 / 1.17.5

Single player or Server: Server

Describe problem (what you were doing / what happened): /home command won't work for anyone even when set correctly in permissions - can see Cyclic messages pop up when running a debug and notice Cyclic has /home commands. Any way to override these entirely in favour of FTBUtils?

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by krisjenner** [comment]
Update: disabled home command in configs and fixed issue. Also added ForgedPerms to server for anyone else struggling with this problem

**Comment by PrinceOfAmber** [comment]
Currently the mod has settings to just say "OPs only" or "everyone" so yeah looks like you found that.

As for custom integration  of custom with FTButils permissions, i didnt know that was a thing . is that an API thing or a server setting ? is this the latest wiki? https://ftbwiki.org/FTB_Utilities
