### ISSUE TITLE
Cyclic hotbar sorting bug

### ISSUE THREAD

**Issue by Gamertech** [Lothrazar/Cyclic#972]
Minecraft version & Mod Version:
1.12.2 & 1.17.7

Single player or Server:
Both

Describe problem (what you were doing / what happened):
If Cyclic Item Shift/Row Shift keybinds are unset and KeybindInventoryShift is set to true in the config, there's a random bug that causes the inventory rows to shift every time a random button is pressed.

No known trigger as to what starts the issue as yet.

Video timestamp of the issue:
https://www.twitch.tv/videos/332054212?t=03h46m05s

**Comment by PrinceOfAmber** [comment]
I cant replicate this in my testing but i can see where it could be happening.  im adding extra checks on the config being disabled to force-stop the event from firing.

**Comment by PrinceOfAmber** [comment]
https://github.com/PrinceOfAmber/Cyclic/issues/824

**Comment by Lothrazar** [comment]
appears fixed in 1.17.10 as noted above. if happens again let me know

**Comment by NillerMedDild** [comment]
I'm afraid this issue was reported by one of my users on `Cyclic-1.12.2-1.18.6`
