### ISSUE TITLE
[NOTABUG] Doc issue and UI, transfer node confusion

### ISSUE THREAD

**Issue by ericcotelnu** [Lothrazar/Cyclic#974]
Hello,

Documentation? Is there an in-game manual? I did a _doh!_ and didn't check (it's late as I write this).
Probably just PEBKAC, but I can't figure out how the GPS marker and the fluid transfer nodes work. Do I 
stick the marker in the receiver or transfer node? Which slot does it go in, the left or right GPS slot? Do I need 2 nodes, or just 1? Should I use a fluid pipe of some sort, or can I send directly from the node to an item with an internal fluid tank?

I noticed it wouldn't receive water if I planted it directly next to an endervoir (the new name for reservoirs in EIO).

Anyway, I'm really confuzzled and have a buncha questions ;).

TIA

PS: they're cool - wireless *fluid* transfer :D.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312
