### ISSUE TITLE
Vision Helmet

### ISSUE THREAD

**Issue by OfMCMXXXVII** [Lothrazar/Cyclic#975]
Minecraft version & Mod Version:
1.12.2, 1.17.3

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Vision Helmet does not clear night vision correctly
Taking the helm off will keep the night vision repeatedly at 0 seconds and will have constantly flashing between night vision effect and regular

**Comment by PrinceOfAmber** [comment]
Works good for me in the latest version and forge_version=14.23.5.2768

![975](https://user-images.githubusercontent.com/621529/48927990-b9d0c100-ee8f-11e8-8a1c-64d06b0d96ca.gif)

**Comment by OfMCMXXXVII** [comment]
This is the pack it happened with:

**Comment by Saereth** [comment]
this is also happening in the FTB Interactions pack (Currently in beta)
https://www.youtube.com/watch?v=9yzwQj09vjM

any chance you can provide a full mod list @OfMCMXXXVII so we can compare and maybe help track down the mod

**Comment by Lothrazar** [comment]
I think there was a bug in forge that caused potions to not clear, i had a similar report on antidote charm  .  
 https://github.com/Lothrazar/Cyclic/issues/1010   
Regardless new versions still work fine for me 

Please repoen with detail if its still an issue in 1.18+

**Comment by l3th3lz0mbi3** [comment]
Is there a way to repair this item using an ore or something.  I can't find it and can't figure it out.
