### ISSUE TITLE
Draconic Evolution Helmet allows Heart container consumption to pass the preset limit

### ISSUE THREAD

**Issue by braingkk** [Lothrazar/Cyclic#976]
Stoneblock Modpack
Cyclic-1.12.2-1.17.7
Draconic-Evolution-1.12.2-2.3.17.321

Only tested on singleplayer

When wearing draconic evolution helm set to auto-feed with heart containers in inventory, it will feed you beyond the limit of 10 additional hearts. all you need to do is make yourself hungry and it will feed you the hearts.

Should i be posting this here, or on Drac Evo's github?

**Comment by PrinceOfAmber** [comment]
Does this new version work? https://minecraft.curseforge.com/projects/cyclic/files/2641400
