### ISSUE TITLE
Line breaks on Digital Typewriter

### ISSUE THREAD

**Issue by SirMoogle** [Lothrazar/Cyclic#977]
Minecraft version & Mod Version:
1.12.2 (Minecraft)
1.17.4 (Cyclic)

Single player or Server:
Server

Describe problem (what you were doing / what happened):
I recently crafted a digital typewriter but for the life of me can't figure out how to do line breaks voluntarily. Is there a key I'm neglecting to press?

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
yeah...  i kind of stopped adding features to it before i got to the whole line-breaks thing.  so the way it is now you just add tons of spaces to get lower.  Its on my list though

**Comment by SirMoogle** [comment]
Ah, okay. It's a really nifty little item and I spent over an hour in another mod to craft one of its components. Hope to see it fully fleshed out soon 👍

**Comment by Lothrazar** [comment]
This block has been basically trashed and totally rebuilt as "Text Projector" in 1.18+  please check it out
