### ISSUE TITLE
Automatic User dupe bug and unreliable usage

### ISSUE THREAD

**Issue by Gamertech** [Lothrazar/Cyclic#980]
Minecraft version & Mod Version:
1.12.2 & 1.17.7

Single player or Server:
Both

Describe problem (what you were doing / what happened):
Two issues:
1- The auto user has a dupe bug as demonstrated here: https://clips.twitch.tv/KitschyTawdryWolfCurseLit

2- Using the auto user to use the Woot hammer on an anvil repeatedly fails as the user only activates the item once instead of every time the delay bar cycles. It wont use the item again unless you manually take it out and put it back in. Adding multiple hammers makes no difference.

The User also activates the item the instant you put it in the input slot no matter where the delay bar is at.

Finally, actually completing the crafting action with using the automatic user on the Woot anvil is highly unreliable. Sometimes it will complete, other times it'll just use the item to no effect.

**Comment by PrinceOfAmber** [comment]
Thanks for the video clip. for #1 i havent tried that Dark Tank yet, but so far other tanks and buckets dont dupe like that... weird

For the delay action, when its just a block of dirt it doesnt get placed on equip, it waits until zero.  
 I havent used WOOT at all yet so ill be looking into that more in detail the way you laid it out

**Comment by PrinceOfAmber** [comment]
Am i doing this right? SO a dark tank and a sky resources fluid thing right? trying to make the dupe happen 

![980 maybe](https://user-images.githubusercontent.com/621529/48975325-51661900-f022-11e8-85a7-64c0996e86c3.gif)

**Comment by Gamertech** [comment]
That's not me in the video so this is second hand, but set the user to level placement, ie targeting the fluid dropper, put 2 dark tanks into the input slot, then right click on them to pickup 1 which triggers the dupe.

**Comment by Gamertech** [comment]
Okay, playing around with it myself, I can't get it to work quite as well as the original video, but by putting in a dark tank with a bucket of fluid in it, letting it cycle in and out of the dropper a few times then shift-dragging dark tanks between my inventory and the user (using mousetweaks), it slowly dupes the tanks.

The dupe I'm getting is a graphical issue though I think, as they vanish once I back out of the UI.

**Comment by trunksbomb** [comment]
I replicated this in my single player world with an Automatic user with buckets pointed at an EnderIO Tank. The buckets were duplicated.

Minecraft 1.12.2
Cyclic 1.17.4
Forge 14.23.5.2768

**Comment by Lothrazar** [comment]
Pretty sure this was a duplicate and the fix applies, testing works on my end.  Also fluid handlers were cleaned up more in 1.18+    https://github.com/Lothrazar/Cyclic/issues/949

Also i just tested in enderio  5.0.40   and it looks good  GIF below

![enderio test](https://user-images.githubusercontent.com/621529/54095182-15ea2300-4363-11e9-8512-ab26c53123d6.gif)
