### ISSUE TITLE
Some things remain in book when disabled

### ISSUE THREAD

**Issue by josephcsible** [Lothrazar/Cyclic#986]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic 1.17.7, Forge 14.23.5.2775

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
All enchantments always show up in the guidebook, even if they don't exist due to being disabled in the config. Also, the guidebook always mentions end and nether ores, even if all of them are disabled.

**Comment by PrinceOfAmber** [comment]
I disabled a few things like the Fan and harvester and a few things, they disappear nicely.

The world gen section i need to redo it , it should list every enabled block instead of those categories or something

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.
