### ISSUE TITLE
Fast ladder system requires improvement

### ISSUE THREAD

**Issue by mcBegins2Snow** [Lothrazar/Cyclic#996]
Minecraft version & Mod Version:
1.17.8

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
The player can climb up the ladder quickly, but he can't climb down the ladder quickly.
![issue](https://user-images.githubusercontent.com/37864486/48926871-87b17480-ef0c-11e8-89c6-433c251f7da4.jpg)

**Comment by PrinceOfAmber** [comment]
Love the graphic!  Initially i made it this way because Quark had the opposite feature, speed going down but not up.  But not every pack has quark so it makes sense to add both here

**Comment by Lothrazar** [comment]
probably making new mod in 1.16 for just this
